<?php

declare(strict_types=1);

namespace Dew\Acs\DlfNext;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result subscribe(array $arguments = [])
 * @method \Http\Promise\Promise subscribeAsync($arguments = [])
 * @method \Dew\Acs\Result describeRegions(array $arguments = [])
 * @method \Http\Promise\Promise describeRegionsAsync($arguments = [])
 * @method \Dew\Acs\Result getRegionStatus(array $arguments = [])
 * @method \Http\Promise\Promise getRegionStatusAsync($arguments = [])
 * @method \Dew\Acs\Result createCatalog(array $arguments = [])
 * @method \Http\Promise\Promise createCatalogAsync($arguments = [])
 * @method \Dew\Acs\Result getCatalog(array $arguments = [])
 * @method \Http\Promise\Promise getCatalogAsync($arguments = [])
 * @method \Dew\Acs\Result alterCatalog(array $arguments = [])
 * @method \Http\Promise\Promise alterCatalogAsync($arguments = [])
 * @method \Dew\Acs\Result dropCatalog(array $arguments = [])
 * @method \Http\Promise\Promise dropCatalogAsync($arguments = [])
 * @method \Dew\Acs\Result listCatalogs(array $arguments = [])
 * @method \Http\Promise\Promise listCatalogsAsync($arguments = [])
 * @method \Dew\Acs\Result getCatalogToken(array $arguments = [])
 * @method \Http\Promise\Promise getCatalogTokenAsync($arguments = [])
 * @method \Dew\Acs\Result getDatabase(array $arguments = [])
 * @method \Http\Promise\Promise getDatabaseAsync($arguments = [])
 * @method \Dew\Acs\Result createDatabase(array $arguments = [])
 * @method \Http\Promise\Promise createDatabaseAsync($arguments = [])
 * @method \Dew\Acs\Result alterDatabase(array $arguments = [])
 * @method \Http\Promise\Promise alterDatabaseAsync($arguments = [])
 * @method \Dew\Acs\Result dropDatabase(array $arguments = [])
 * @method \Http\Promise\Promise dropDatabaseAsync($arguments = [])
 * @method \Dew\Acs\Result listDatabases(array $arguments = [])
 * @method \Http\Promise\Promise listDatabasesAsync($arguments = [])
 * @method \Dew\Acs\Result getTable(array $arguments = [])
 * @method \Http\Promise\Promise getTableAsync($arguments = [])
 * @method \Dew\Acs\Result createTable(array $arguments = [])
 * @method \Http\Promise\Promise createTableAsync($arguments = [])
 * @method \Dew\Acs\Result alterTable(array $arguments = [])
 * @method \Http\Promise\Promise alterTableAsync($arguments = [])
 * @method \Dew\Acs\Result dropTable(array $arguments = [])
 * @method \Http\Promise\Promise dropTableAsync($arguments = [])
 * @method \Dew\Acs\Result listTables(array $arguments = [])
 * @method \Http\Promise\Promise listTablesAsync($arguments = [])
 * @method \Dew\Acs\Result batchGrantPermissions(array $arguments = [])
 * @method \Http\Promise\Promise batchGrantPermissionsAsync($arguments = [])
 * @method \Dew\Acs\Result batchRevokePermissions(array $arguments = [])
 * @method \Http\Promise\Promise batchRevokePermissionsAsync($arguments = [])
 * @method \Dew\Acs\Result listPermissions(array $arguments = [])
 * @method \Http\Promise\Promise listPermissionsAsync($arguments = [])
 * @method \Dew\Acs\Result createRole(array $arguments = [])
 * @method \Http\Promise\Promise createRoleAsync($arguments = [])
 * @method \Dew\Acs\Result getRole(array $arguments = [])
 * @method \Http\Promise\Promise getRoleAsync($arguments = [])
 * @method \Dew\Acs\Result updateRole(array $arguments = [])
 * @method \Http\Promise\Promise updateRoleAsync($arguments = [])
 * @method \Dew\Acs\Result deleteRole(array $arguments = [])
 * @method \Http\Promise\Promise deleteRoleAsync($arguments = [])
 * @method \Dew\Acs\Result listRoles(array $arguments = [])
 * @method \Http\Promise\Promise listRolesAsync($arguments = [])
 * @method \Dew\Acs\Result getUser(array $arguments = [])
 * @method \Http\Promise\Promise getUserAsync($arguments = [])
 * @method \Dew\Acs\Result listUsers(array $arguments = [])
 * @method \Http\Promise\Promise listUsersAsync($arguments = [])
 * @method \Dew\Acs\Result listRoleUsers(array $arguments = [])
 * @method \Http\Promise\Promise listRoleUsersAsync($arguments = [])
 * @method \Dew\Acs\Result updateRoleUsers(array $arguments = [])
 * @method \Http\Promise\Promise updateRoleUsersAsync($arguments = [])
 * @method \Dew\Acs\Result listUserRoles(array $arguments = [])
 * @method \Http\Promise\Promise listUserRolesAsync($arguments = [])
 * @method \Dew\Acs\Result grantRoleToUsers(array $arguments = [])
 * @method \Http\Promise\Promise grantRoleToUsersAsync($arguments = [])
 * @method \Dew\Acs\Result revokeRoleFromUsers(array $arguments = [])
 * @method \Http\Promise\Promise revokeRoleFromUsersAsync($arguments = [])
 * @method \Dew\Acs\Result getCatalogSummary(array $arguments = [])
 * @method \Http\Promise\Promise getCatalogSummaryAsync($arguments = [])
 * @method \Dew\Acs\Result getCatalogSummaryTrend(array $arguments = [])
 * @method \Http\Promise\Promise getCatalogSummaryTrendAsync($arguments = [])
 * @method \Dew\Acs\Result getDatabaseSummary(array $arguments = [])
 * @method \Http\Promise\Promise getDatabaseSummaryAsync($arguments = [])
 * @method \Dew\Acs\Result getTableSummary(array $arguments = [])
 * @method \Http\Promise\Promise getTableSummaryAsync($arguments = [])
 * @method \Dew\Acs\Result listPartitionSummaries(array $arguments = [])
 * @method \Http\Promise\Promise listPartitionSummariesAsync($arguments = [])
 */
final class DlfNextClient extends AcsClient
{
    //
}
