<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table.proto

namespace Dew\Acs\Tablestore\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.tablestore.table.UpdateTableResponse</code>
 */
class UpdateTableResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>required .acs.tablestore.table.ReservedThroughputDetails reserved_throughput_details = 1;</code>
     */
    protected $reserved_throughput_details = null;
    /**
     * Generated from protobuf field <code>required .acs.tablestore.table.TableOptions table_options = 2;</code>
     */
    protected $table_options = null;
    /**
     * Generated from protobuf field <code>optional .acs.tablestore.table.StreamDetails stream_details = 3;</code>
     */
    protected $stream_details = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Dew\Acs\Tablestore\Messages\ReservedThroughputDetails $reserved_throughput_details
     *     @type \Dew\Acs\Tablestore\Messages\TableOptions $table_options
     *     @type \Dew\Acs\Tablestore\Messages\StreamDetails $stream_details
     * }
     */
    public function __construct($data = NULL) {
        \Dew\Acs\Tablestore\Metadata\Table::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>required .acs.tablestore.table.ReservedThroughputDetails reserved_throughput_details = 1;</code>
     * @return \Dew\Acs\Tablestore\Messages\ReservedThroughputDetails|null
     */
    public function getReservedThroughputDetails()
    {
        return $this->reserved_throughput_details;
    }

    public function hasReservedThroughputDetails()
    {
        return isset($this->reserved_throughput_details);
    }

    public function clearReservedThroughputDetails()
    {
        unset($this->reserved_throughput_details);
    }

    /**
     * Generated from protobuf field <code>required .acs.tablestore.table.ReservedThroughputDetails reserved_throughput_details = 1;</code>
     * @param \Dew\Acs\Tablestore\Messages\ReservedThroughputDetails $var
     * @return $this
     */
    public function setReservedThroughputDetails($var)
    {
        GPBUtil::checkMessage($var, \Dew\Acs\Tablestore\Messages\ReservedThroughputDetails::class);
        $this->reserved_throughput_details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>required .acs.tablestore.table.TableOptions table_options = 2;</code>
     * @return \Dew\Acs\Tablestore\Messages\TableOptions|null
     */
    public function getTableOptions()
    {
        return $this->table_options;
    }

    public function hasTableOptions()
    {
        return isset($this->table_options);
    }

    public function clearTableOptions()
    {
        unset($this->table_options);
    }

    /**
     * Generated from protobuf field <code>required .acs.tablestore.table.TableOptions table_options = 2;</code>
     * @param \Dew\Acs\Tablestore\Messages\TableOptions $var
     * @return $this
     */
    public function setTableOptions($var)
    {
        GPBUtil::checkMessage($var, \Dew\Acs\Tablestore\Messages\TableOptions::class);
        $this->table_options = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .acs.tablestore.table.StreamDetails stream_details = 3;</code>
     * @return \Dew\Acs\Tablestore\Messages\StreamDetails|null
     */
    public function getStreamDetails()
    {
        return $this->stream_details;
    }

    public function hasStreamDetails()
    {
        return isset($this->stream_details);
    }

    public function clearStreamDetails()
    {
        unset($this->stream_details);
    }

    /**
     * Generated from protobuf field <code>optional .acs.tablestore.table.StreamDetails stream_details = 3;</code>
     * @param \Dew\Acs\Tablestore\Messages\StreamDetails $var
     * @return $this
     */
    public function setStreamDetails($var)
    {
        GPBUtil::checkMessage($var, \Dew\Acs\Tablestore\Messages\StreamDetails::class);
        $this->stream_details = $var;

        return $this;
    }

}

