<?php

declare(strict_types=1);

namespace Dew\Acs\Imp;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result getAuthToken(array $arguments = [])
 * @method \Http\Promise\Promise getAuthTokenAsync($arguments = [])
 * @method \Dew\Acs\Result listLiveRooms(array $arguments = [])
 * @method \Http\Promise\Promise listLiveRoomsAsync($arguments = [])
 * @method \Dew\Acs\Result listLiveRoomsById(array $arguments = [])
 * @method \Http\Promise\Promise listLiveRoomsByIdAsync($arguments = [])
 * @method \Dew\Acs\Result getLiveRoomStatistics(array $arguments = [])
 * @method \Http\Promise\Promise getLiveRoomStatisticsAsync($arguments = [])
 * @method \Dew\Acs\Result getLiveRoomUserStatistics(array $arguments = [])
 * @method \Http\Promise\Promise getLiveRoomUserStatisticsAsync($arguments = [])
 * @method \Dew\Acs\Result getLiveRecord(array $arguments = [])
 * @method \Http\Promise\Promise getLiveRecordAsync($arguments = [])
 * @method \Dew\Acs\Result createLiveRecordSliceFile(array $arguments = [])
 * @method \Http\Promise\Promise createLiveRecordSliceFileAsync($arguments = [])
 * @method \Dew\Acs\Result listLiveFiles(array $arguments = [])
 * @method \Http\Promise\Promise listLiveFilesAsync($arguments = [])
 * @method \Dew\Acs\Result deleteLiveFilesById(array $arguments = [])
 * @method \Http\Promise\Promise deleteLiveFilesByIdAsync($arguments = [])
 * @method \Dew\Acs\Result createLiveRoom(array $arguments = [])
 * @method \Http\Promise\Promise createLiveRoomAsync($arguments = [])
 * @method \Dew\Acs\Result deleteLiveRoom(array $arguments = [])
 * @method \Http\Promise\Promise deleteLiveRoomAsync($arguments = [])
 * @method \Dew\Acs\Result publishLiveRoom(array $arguments = [])
 * @method \Http\Promise\Promise publishLiveRoomAsync($arguments = [])
 * @method \Dew\Acs\Result updateLiveRoom(array $arguments = [])
 * @method \Http\Promise\Promise updateLiveRoomAsync($arguments = [])
 * @method \Dew\Acs\Result stopLiveRoom(array $arguments = [])
 * @method \Http\Promise\Promise stopLiveRoomAsync($arguments = [])
 * @method \Dew\Acs\Result getLiveRoom(array $arguments = [])
 * @method \Http\Promise\Promise getLiveRoomAsync($arguments = [])
 * @method \Dew\Acs\Result createClass(array $arguments = [])
 * @method \Http\Promise\Promise createClassAsync($arguments = [])
 * @method \Dew\Acs\Result deleteClass(array $arguments = [])
 * @method \Http\Promise\Promise deleteClassAsync($arguments = [])
 * @method \Dew\Acs\Result stopClass(array $arguments = [])
 * @method \Http\Promise\Promise stopClassAsync($arguments = [])
 * @method \Dew\Acs\Result updateClass(array $arguments = [])
 * @method \Http\Promise\Promise updateClassAsync($arguments = [])
 * @method \Dew\Acs\Result getClassDetail(array $arguments = [])
 * @method \Http\Promise\Promise getClassDetailAsync($arguments = [])
 * @method \Dew\Acs\Result listClasses(array $arguments = [])
 * @method \Http\Promise\Promise listClassesAsync($arguments = [])
 * @method \Dew\Acs\Result getClassRecord(array $arguments = [])
 * @method \Http\Promise\Promise getClassRecordAsync($arguments = [])
 * @method \Dew\Acs\Result updateShareScreenLayout(array $arguments = [])
 * @method \Http\Promise\Promise updateShareScreenLayoutAsync($arguments = [])
 * @method \Dew\Acs\Result createRoom(array $arguments = [])
 * @method \Http\Promise\Promise createRoomAsync($arguments = [])
 * @method \Dew\Acs\Result deleteRoom(array $arguments = [])
 * @method \Http\Promise\Promise deleteRoomAsync($arguments = [])
 * @method \Dew\Acs\Result updateRoom(array $arguments = [])
 * @method \Http\Promise\Promise updateRoomAsync($arguments = [])
 * @method \Dew\Acs\Result kickRoomUser(array $arguments = [])
 * @method \Http\Promise\Promise kickRoomUserAsync($arguments = [])
 * @method \Dew\Acs\Result setUserAdmin(array $arguments = [])
 * @method \Http\Promise\Promise setUserAdminAsync($arguments = [])
 * @method \Dew\Acs\Result cancelUserAdmin(array $arguments = [])
 * @method \Http\Promise\Promise cancelUserAdminAsync($arguments = [])
 * @method \Dew\Acs\Result getRoom(array $arguments = [])
 * @method \Http\Promise\Promise getRoomAsync($arguments = [])
 * @method \Dew\Acs\Result listRooms(array $arguments = [])
 * @method \Http\Promise\Promise listRoomsAsync($arguments = [])
 * @method \Dew\Acs\Result listRoomUsers(array $arguments = [])
 * @method \Http\Promise\Promise listRoomUsersAsync($arguments = [])
 * @method \Dew\Acs\Result createSensitiveWord(array $arguments = [])
 * @method \Http\Promise\Promise createSensitiveWordAsync($arguments = [])
 * @method \Dew\Acs\Result deleteSensitiveWord(array $arguments = [])
 * @method \Http\Promise\Promise deleteSensitiveWordAsync($arguments = [])
 * @method \Dew\Acs\Result listSensitiveWord(array $arguments = [])
 * @method \Http\Promise\Promise listSensitiveWordAsync($arguments = [])
 * @method \Dew\Acs\Result cancelBanAllComment(array $arguments = [])
 * @method \Http\Promise\Promise cancelBanAllCommentAsync($arguments = [])
 * @method \Dew\Acs\Result cancelBanComment(array $arguments = [])
 * @method \Http\Promise\Promise cancelBanCommentAsync($arguments = [])
 * @method \Dew\Acs\Result banAllComment(array $arguments = [])
 * @method \Http\Promise\Promise banAllCommentAsync($arguments = [])
 * @method \Dew\Acs\Result banComment(array $arguments = [])
 * @method \Http\Promise\Promise banCommentAsync($arguments = [])
 * @method \Dew\Acs\Result sendCustomMessageToAll(array $arguments = [])
 * @method \Http\Promise\Promise sendCustomMessageToAllAsync($arguments = [])
 * @method \Dew\Acs\Result sendCustomMessageToUsers(array $arguments = [])
 * @method \Http\Promise\Promise sendCustomMessageToUsersAsync($arguments = [])
 * @method \Dew\Acs\Result sendComment(array $arguments = [])
 * @method \Http\Promise\Promise sendCommentAsync($arguments = [])
 * @method \Dew\Acs\Result deleteComment(array $arguments = [])
 * @method \Http\Promise\Promise deleteCommentAsync($arguments = [])
 * @method \Dew\Acs\Result listComments(array $arguments = [])
 * @method \Http\Promise\Promise listCommentsAsync($arguments = [])
 * @method \Dew\Acs\Result deleteCommentByCreatorId(array $arguments = [])
 * @method \Http\Promise\Promise deleteCommentByCreatorIdAsync($arguments = [])
 * @method \Dew\Acs\Result deleteConference(array $arguments = [])
 * @method \Http\Promise\Promise deleteConferenceAsync($arguments = [])
 * @method \Dew\Acs\Result removeMember(array $arguments = [])
 * @method \Http\Promise\Promise removeMemberAsync($arguments = [])
 * @method \Dew\Acs\Result getConference(array $arguments = [])
 * @method \Http\Promise\Promise getConferenceAsync($arguments = [])
 * @method \Dew\Acs\Result listConferenceUsers(array $arguments = [])
 * @method \Http\Promise\Promise listConferenceUsersAsync($arguments = [])
 * @method \Dew\Acs\Result getStandardRoomJumpUrl(array $arguments = [])
 * @method \Http\Promise\Promise getStandardRoomJumpUrlAsync($arguments = [])
 * @method \Dew\Acs\Result describeMeterImpWatchLiveTimeByLiveId(array $arguments = [])
 * @method \Http\Promise\Promise describeMeterImpWatchLiveTimeByLiveIdAsync($arguments = [])
 * @method \Dew\Acs\Result describeMeterImpPlayBackTimeByLiveId(array $arguments = [])
 * @method \Http\Promise\Promise describeMeterImpPlayBackTimeByLiveIdAsync($arguments = [])
 * @method \Dew\Acs\Result createLive(array $arguments = [])
 * @method \Http\Promise\Promise createLiveAsync($arguments = [])
 * @method \Dew\Acs\Result deleteLive(array $arguments = [])
 * @method \Http\Promise\Promise deleteLiveAsync($arguments = [])
 * @method \Dew\Acs\Result publishLive(array $arguments = [])
 * @method \Http\Promise\Promise publishLiveAsync($arguments = [])
 * @method \Dew\Acs\Result updateLive(array $arguments = [])
 * @method \Http\Promise\Promise updateLiveAsync($arguments = [])
 * @method \Dew\Acs\Result stopLive(array $arguments = [])
 * @method \Http\Promise\Promise stopLiveAsync($arguments = [])
 * @method \Dew\Acs\Result getLive(array $arguments = [])
 * @method \Http\Promise\Promise getLiveAsync($arguments = [])
 */
final class ImpClient extends AcsClient
{
    //
}
