<?php

declare(strict_types=1);

namespace Dew\Acs\EiamDeveloperapi;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result generateToken(array $arguments = [])
 * @method \Http\Promise\Promise generateTokenAsync($arguments = [])
 * @method \Dew\Acs\Result generateDeviceCode(array $arguments = [])
 * @method \Http\Promise\Promise generateDeviceCodeAsync($arguments = [])
 * @method \Dew\Acs\Result getUserInfo(array $arguments = [])
 * @method \Http\Promise\Promise getUserInfoAsync($arguments = [])
 * @method \Dew\Acs\Result revokeToken(array $arguments = [])
 * @method \Http\Promise\Promise revokeTokenAsync($arguments = [])
 * @method \Dew\Acs\Result getApplicationProvisioningScope(array $arguments = [])
 * @method \Http\Promise\Promise getApplicationProvisioningScopeAsync($arguments = [])
 * @method \Dew\Acs\Result createOrganizationalUnit(array $arguments = [])
 * @method \Http\Promise\Promise createOrganizationalUnitAsync($arguments = [])
 * @method \Dew\Acs\Result patchOrganizationalUnit(array $arguments = [])
 * @method \Http\Promise\Promise patchOrganizationalUnitAsync($arguments = [])
 * @method \Dew\Acs\Result getOrganizationalUnit(array $arguments = [])
 * @method \Http\Promise\Promise getOrganizationalUnitAsync($arguments = [])
 * @method \Dew\Acs\Result deleteOrganizationalUnit(array $arguments = [])
 * @method \Http\Promise\Promise deleteOrganizationalUnitAsync($arguments = [])
 * @method \Dew\Acs\Result listOrganizationalUnits(array $arguments = [])
 * @method \Http\Promise\Promise listOrganizationalUnitsAsync($arguments = [])
 * @method \Dew\Acs\Result listOrganizationalUnitParentIds(array $arguments = [])
 * @method \Http\Promise\Promise listOrganizationalUnitParentIdsAsync($arguments = [])
 * @method \Dew\Acs\Result getOrganizationalUnitIdByExternalId(array $arguments = [])
 * @method \Http\Promise\Promise getOrganizationalUnitIdByExternalIdAsync($arguments = [])
 * @method \Dew\Acs\Result getGroup(array $arguments = [])
 * @method \Http\Promise\Promise getGroupAsync($arguments = [])
 * @method \Dew\Acs\Result createGroup(array $arguments = [])
 * @method \Http\Promise\Promise createGroupAsync($arguments = [])
 * @method \Dew\Acs\Result patchGroup(array $arguments = [])
 * @method \Http\Promise\Promise patchGroupAsync($arguments = [])
 * @method \Dew\Acs\Result deleteGroup(array $arguments = [])
 * @method \Http\Promise\Promise deleteGroupAsync($arguments = [])
 * @method \Dew\Acs\Result listGroups(array $arguments = [])
 * @method \Http\Promise\Promise listGroupsAsync($arguments = [])
 * @method \Dew\Acs\Result addUsersToGroup(array $arguments = [])
 * @method \Http\Promise\Promise addUsersToGroupAsync($arguments = [])
 * @method \Dew\Acs\Result removeUsersFromGroup(array $arguments = [])
 * @method \Http\Promise\Promise removeUsersFromGroupAsync($arguments = [])
 * @method \Dew\Acs\Result listUsersForGroup(array $arguments = [])
 * @method \Http\Promise\Promise listUsersForGroupAsync($arguments = [])
 * @method \Dew\Acs\Result createUser(array $arguments = [])
 * @method \Http\Promise\Promise createUserAsync($arguments = [])
 * @method \Dew\Acs\Result patchUser(array $arguments = [])
 * @method \Http\Promise\Promise patchUserAsync($arguments = [])
 * @method \Dew\Acs\Result getUser(array $arguments = [])
 * @method \Http\Promise\Promise getUserAsync($arguments = [])
 * @method \Dew\Acs\Result updateUserPassword(array $arguments = [])
 * @method \Http\Promise\Promise updateUserPasswordAsync($arguments = [])
 * @method \Dew\Acs\Result deleteUser(array $arguments = [])
 * @method \Http\Promise\Promise deleteUserAsync($arguments = [])
 * @method \Dew\Acs\Result listUsers(array $arguments = [])
 * @method \Http\Promise\Promise listUsersAsync($arguments = [])
 * @method \Dew\Acs\Result enableUser(array $arguments = [])
 * @method \Http\Promise\Promise enableUserAsync($arguments = [])
 * @method \Dew\Acs\Result disableUser(array $arguments = [])
 * @method \Http\Promise\Promise disableUserAsync($arguments = [])
 * @method \Dew\Acs\Result getUserIdByEmail(array $arguments = [])
 * @method \Http\Promise\Promise getUserIdByEmailAsync($arguments = [])
 * @method \Dew\Acs\Result getUserIdByPhoneNumber(array $arguments = [])
 * @method \Http\Promise\Promise getUserIdByPhoneNumberAsync($arguments = [])
 * @method \Dew\Acs\Result getUserIdByUserExternalId(array $arguments = [])
 * @method \Http\Promise\Promise getUserIdByUserExternalIdAsync($arguments = [])
 * @method \Dew\Acs\Result getUserIdByUsername(array $arguments = [])
 * @method \Http\Promise\Promise getUserIdByUsernameAsync($arguments = [])
 * @method \Dew\Acs\Result setUserPrimaryOrganizationalUnit(array $arguments = [])
 * @method \Http\Promise\Promise setUserPrimaryOrganizationalUnitAsync($arguments = [])
 * @method \Dew\Acs\Result addUserToOrganizationalUnits(array $arguments = [])
 * @method \Http\Promise\Promise addUserToOrganizationalUnitsAsync($arguments = [])
 * @method \Dew\Acs\Result removeUserFromOrganizationalUnits(array $arguments = [])
 * @method \Http\Promise\Promise removeUserFromOrganizationalUnitsAsync($arguments = [])
 * @method \Dew\Acs\Result listGroupsForUser(array $arguments = [])
 * @method \Http\Promise\Promise listGroupsForUserAsync($arguments = [])
 */
final class EiamDeveloperapiClient extends AcsClient
{
    //
}
