<?php

declare(strict_types=1);

namespace Dew\Acs\AgentRun;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result createAgentRuntime(array $arguments = [])
 * @method \Http\Promise\Promise createAgentRuntimeAsync($arguments = [])
 * @method \Dew\Acs\Result getAgentRuntime(array $arguments = [])
 * @method \Http\Promise\Promise getAgentRuntimeAsync($arguments = [])
 * @method \Dew\Acs\Result updateAgentRuntime(array $arguments = [])
 * @method \Http\Promise\Promise updateAgentRuntimeAsync($arguments = [])
 * @method \Dew\Acs\Result deleteAgentRuntime(array $arguments = [])
 * @method \Http\Promise\Promise deleteAgentRuntimeAsync($arguments = [])
 * @method \Dew\Acs\Result listAgentRuntimes(array $arguments = [])
 * @method \Http\Promise\Promise listAgentRuntimesAsync($arguments = [])
 * @method \Dew\Acs\Result createAgentRuntimeEndpoint(array $arguments = [])
 * @method \Http\Promise\Promise createAgentRuntimeEndpointAsync($arguments = [])
 * @method \Dew\Acs\Result listAgentRuntimeEndpoints(array $arguments = [])
 * @method \Http\Promise\Promise listAgentRuntimeEndpointsAsync($arguments = [])
 * @method \Dew\Acs\Result getAgentRuntimeEndpoint(array $arguments = [])
 * @method \Http\Promise\Promise getAgentRuntimeEndpointAsync($arguments = [])
 * @method \Dew\Acs\Result updateAgentRuntimeEndpoint(array $arguments = [])
 * @method \Http\Promise\Promise updateAgentRuntimeEndpointAsync($arguments = [])
 * @method \Dew\Acs\Result deleteAgentRuntimeEndpoint(array $arguments = [])
 * @method \Http\Promise\Promise deleteAgentRuntimeEndpointAsync($arguments = [])
 * @method \Dew\Acs\Result publishRuntimeVersion(array $arguments = [])
 * @method \Http\Promise\Promise publishRuntimeVersionAsync($arguments = [])
 * @method \Dew\Acs\Result listAgentRuntimeVersions(array $arguments = [])
 * @method \Http\Promise\Promise listAgentRuntimeVersionsAsync($arguments = [])
 * @method \Dew\Acs\Result createCodeInterpreter(array $arguments = [])
 * @method \Http\Promise\Promise createCodeInterpreterAsync($arguments = [])
 * @method \Dew\Acs\Result listCodeInterpreters(array $arguments = [])
 * @method \Http\Promise\Promise listCodeInterpretersAsync($arguments = [])
 * @method \Dew\Acs\Result getCodeInterpreter(array $arguments = [])
 * @method \Http\Promise\Promise getCodeInterpreterAsync($arguments = [])
 * @method \Dew\Acs\Result deleteCodeInterpreter(array $arguments = [])
 * @method \Http\Promise\Promise deleteCodeInterpreterAsync($arguments = [])
 * @method \Dew\Acs\Result createBrowser(array $arguments = [])
 * @method \Http\Promise\Promise createBrowserAsync($arguments = [])
 * @method \Dew\Acs\Result listBrowsers(array $arguments = [])
 * @method \Http\Promise\Promise listBrowsersAsync($arguments = [])
 * @method \Dew\Acs\Result getBrowser(array $arguments = [])
 * @method \Http\Promise\Promise getBrowserAsync($arguments = [])
 * @method \Dew\Acs\Result deleteBrowser(array $arguments = [])
 * @method \Http\Promise\Promise deleteBrowserAsync($arguments = [])
 * @method \Dew\Acs\Result createMemory(array $arguments = [])
 * @method \Http\Promise\Promise createMemoryAsync($arguments = [])
 * @method \Dew\Acs\Result getMemory(array $arguments = [])
 * @method \Http\Promise\Promise getMemoryAsync($arguments = [])
 * @method \Dew\Acs\Result updateMemory(array $arguments = [])
 * @method \Http\Promise\Promise updateMemoryAsync($arguments = [])
 * @method \Dew\Acs\Result deleteMemory(array $arguments = [])
 * @method \Http\Promise\Promise deleteMemoryAsync($arguments = [])
 * @method \Dew\Acs\Result listMemory(array $arguments = [])
 * @method \Http\Promise\Promise listMemoryAsync($arguments = [])
 * @method \Dew\Acs\Result retrieveMemory(array $arguments = [])
 * @method \Http\Promise\Promise retrieveMemoryAsync($arguments = [])
 * @method \Dew\Acs\Result listMemorySessions(array $arguments = [])
 * @method \Http\Promise\Promise listMemorySessionsAsync($arguments = [])
 * @method \Dew\Acs\Result getMemorySession(array $arguments = [])
 * @method \Http\Promise\Promise getMemorySessionAsync($arguments = [])
 * @method \Dew\Acs\Result createMemoryEvent(array $arguments = [])
 * @method \Http\Promise\Promise createMemoryEventAsync($arguments = [])
 * @method \Dew\Acs\Result getMemoryEvent(array $arguments = [])
 * @method \Http\Promise\Promise getMemoryEventAsync($arguments = [])
 * @method \Dew\Acs\Result listMemoryEvent(array $arguments = [])
 * @method \Http\Promise\Promise listMemoryEventAsync($arguments = [])
 */
final class AgentRunClient extends AcsClient
{
    //
}
