<?php

declare(strict_types=1);

namespace Dew\Acs\Sgw;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result createStorageBundle(array $arguments = [])
 * @method \Http\Promise\Promise createStorageBundleAsync($arguments = [])
 * @method \Dew\Acs\Result modifyStorageBundle(array $arguments = [])
 * @method \Http\Promise\Promise modifyStorageBundleAsync($arguments = [])
 * @method \Dew\Acs\Result describeStorageBundle(array $arguments = [])
 * @method \Http\Promise\Promise describeStorageBundleAsync($arguments = [])
 * @method \Dew\Acs\Result deleteStorageBundle(array $arguments = [])
 * @method \Http\Promise\Promise deleteStorageBundleAsync($arguments = [])
 * @method \Dew\Acs\Result describeStorageBundles(array $arguments = [])
 * @method \Http\Promise\Promise describeStorageBundlesAsync($arguments = [])
 * @method \Dew\Acs\Result openSgwService(array $arguments = [])
 * @method \Http\Promise\Promise openSgwServiceAsync($arguments = [])
 * @method \Dew\Acs\Result createGateway(array $arguments = [])
 * @method \Http\Promise\Promise createGatewayAsync($arguments = [])
 * @method \Dew\Acs\Result upgradeGateway(array $arguments = [])
 * @method \Http\Promise\Promise upgradeGatewayAsync($arguments = [])
 * @method \Dew\Acs\Result deleteGateway(array $arguments = [])
 * @method \Http\Promise\Promise deleteGatewayAsync($arguments = [])
 * @method \Dew\Acs\Result describeGateway(array $arguments = [])
 * @method \Http\Promise\Promise describeGatewayAsync($arguments = [])
 * @method \Dew\Acs\Result modifyGateway(array $arguments = [])
 * @method \Http\Promise\Promise modifyGatewayAsync($arguments = [])
 * @method \Dew\Acs\Result deployGateway(array $arguments = [])
 * @method \Http\Promise\Promise deployGatewayAsync($arguments = [])
 * @method \Dew\Acs\Result describeTasks(array $arguments = [])
 * @method \Http\Promise\Promise describeTasksAsync($arguments = [])
 * @method \Dew\Acs\Result describeGateways(array $arguments = [])
 * @method \Http\Promise\Promise describeGatewaysAsync($arguments = [])
 * @method \Dew\Acs\Result describeGatewayCategories(array $arguments = [])
 * @method \Http\Promise\Promise describeGatewayCategoriesAsync($arguments = [])
 * @method \Dew\Acs\Result describeGatewayTypes(array $arguments = [])
 * @method \Http\Promise\Promise describeGatewayTypesAsync($arguments = [])
 * @method \Dew\Acs\Result describeAccountConfig(array $arguments = [])
 * @method \Http\Promise\Promise describeAccountConfigAsync($arguments = [])
 * @method \Dew\Acs\Result describeGatewayImages(array $arguments = [])
 * @method \Http\Promise\Promise describeGatewayImagesAsync($arguments = [])
 * @method \Dew\Acs\Result triggerGatewayRemoteSync(array $arguments = [])
 * @method \Http\Promise\Promise triggerGatewayRemoteSyncAsync($arguments = [])
 * @method \Dew\Acs\Result describeRegions(array $arguments = [])
 * @method \Http\Promise\Promise describeRegionsAsync($arguments = [])
 * @method \Dew\Acs\Result describeGatewayClasses(array $arguments = [])
 * @method \Http\Promise\Promise describeGatewayClassesAsync($arguments = [])
 * @method \Dew\Acs\Result expandGatewayNetworkBandwidth(array $arguments = [])
 * @method \Http\Promise\Promise expandGatewayNetworkBandwidthAsync($arguments = [])
 * @method \Dew\Acs\Result createGatewayBlockVolume(array $arguments = [])
 * @method \Http\Promise\Promise createGatewayBlockVolumeAsync($arguments = [])
 * @method \Dew\Acs\Result describeGatewayBlockVolumes(array $arguments = [])
 * @method \Http\Promise\Promise describeGatewayBlockVolumesAsync($arguments = [])
 * @method \Dew\Acs\Result updateGatewayBlockVolume(array $arguments = [])
 * @method \Http\Promise\Promise updateGatewayBlockVolumeAsync($arguments = [])
 * @method \Dew\Acs\Result deleteGatewayBlockVolumes(array $arguments = [])
 * @method \Http\Promise\Promise deleteGatewayBlockVolumesAsync($arguments = [])
 * @method \Dew\Acs\Result createGatewayFileShare(array $arguments = [])
 * @method \Http\Promise\Promise createGatewayFileShareAsync($arguments = [])
 * @method \Dew\Acs\Result describeGatewayFileStatus(array $arguments = [])
 * @method \Http\Promise\Promise describeGatewayFileStatusAsync($arguments = [])
 * @method \Dew\Acs\Result describeGatewayFileShares(array $arguments = [])
 * @method \Http\Promise\Promise describeGatewayFileSharesAsync($arguments = [])
 * @method \Dew\Acs\Result updateGatewayFileShare(array $arguments = [])
 * @method \Http\Promise\Promise updateGatewayFileShareAsync($arguments = [])
 * @method \Dew\Acs\Result deleteGatewayFileShares(array $arguments = [])
 * @method \Http\Promise\Promise deleteGatewayFileSharesAsync($arguments = [])
 * @method \Dew\Acs\Result describeGatewayNFSClients(array $arguments = [])
 * @method \Http\Promise\Promise describeGatewayNFSClientsAsync($arguments = [])
 * @method \Dew\Acs\Result modifyGatewayFileShareWatermark(array $arguments = [])
 * @method \Http\Promise\Promise modifyGatewayFileShareWatermarkAsync($arguments = [])
 * @method \Dew\Acs\Result expandGatewayFileShare(array $arguments = [])
 * @method \Http\Promise\Promise expandGatewayFileShareAsync($arguments = [])
 * @method \Dew\Acs\Result createGatewaySMBUser(array $arguments = [])
 * @method \Http\Promise\Promise createGatewaySMBUserAsync($arguments = [])
 * @method \Dew\Acs\Result deleteGatewaySMBUser(array $arguments = [])
 * @method \Http\Promise\Promise deleteGatewaySMBUserAsync($arguments = [])
 * @method \Dew\Acs\Result describeGatewaySMBUsers(array $arguments = [])
 * @method \Http\Promise\Promise describeGatewaySMBUsersAsync($arguments = [])
 * @method \Dew\Acs\Result setGatewayDNS(array $arguments = [])
 * @method \Http\Promise\Promise setGatewayDNSAsync($arguments = [])
 * @method \Dew\Acs\Result describeGatewayDNS(array $arguments = [])
 * @method \Http\Promise\Promise describeGatewayDNSAsync($arguments = [])
 * @method \Dew\Acs\Result setGatewayADInfo(array $arguments = [])
 * @method \Http\Promise\Promise setGatewayADInfoAsync($arguments = [])
 * @method \Dew\Acs\Result describeGatewayADInfo(array $arguments = [])
 * @method \Http\Promise\Promise describeGatewayADInfoAsync($arguments = [])
 * @method \Dew\Acs\Result createGatewayCacheDisk(array $arguments = [])
 * @method \Http\Promise\Promise createGatewayCacheDiskAsync($arguments = [])
 * @method \Dew\Acs\Result describeGatewayCaches(array $arguments = [])
 * @method \Http\Promise\Promise describeGatewayCachesAsync($arguments = [])
 * @method \Dew\Acs\Result expandCacheDisk(array $arguments = [])
 * @method \Http\Promise\Promise expandCacheDiskAsync($arguments = [])
 * @method \Dew\Acs\Result deleteGatewayCacheDisk(array $arguments = [])
 * @method \Http\Promise\Promise deleteGatewayCacheDiskAsync($arguments = [])
 * @method \Dew\Acs\Result tagResources(array $arguments = [])
 * @method \Http\Promise\Promise tagResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result listTagResources(array $arguments = [])
 * @method \Http\Promise\Promise listTagResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result untagResources(array $arguments = [])
 * @method \Http\Promise\Promise untagResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result createGatewayLogging(array $arguments = [])
 * @method \Http\Promise\Promise createGatewayLoggingAsync($arguments = [])
 * @method \Dew\Acs\Result describeGatewayLogging(array $arguments = [])
 * @method \Http\Promise\Promise describeGatewayLoggingAsync($arguments = [])
 * @method \Dew\Acs\Result enableGatewayLogging(array $arguments = [])
 * @method \Http\Promise\Promise enableGatewayLoggingAsync($arguments = [])
 * @method \Dew\Acs\Result disableGatewayLogging(array $arguments = [])
 * @method \Http\Promise\Promise disableGatewayLoggingAsync($arguments = [])
 * @method \Dew\Acs\Result deleteGatewayLogging(array $arguments = [])
 * @method \Http\Promise\Promise deleteGatewayLoggingAsync($arguments = [])
 * @method \Dew\Acs\Result createExpressSync(array $arguments = [])
 * @method \Http\Promise\Promise createExpressSyncAsync($arguments = [])
 * @method \Dew\Acs\Result addSharesToExpressSync(array $arguments = [])
 * @method \Http\Promise\Promise addSharesToExpressSyncAsync($arguments = [])
 * @method \Dew\Acs\Result describeExpressSyncs(array $arguments = [])
 * @method \Http\Promise\Promise describeExpressSyncsAsync($arguments = [])
 * @method \Dew\Acs\Result describeExpressSyncShares(array $arguments = [])
 * @method \Http\Promise\Promise describeExpressSyncSharesAsync($arguments = [])
 * @method \Dew\Acs\Result deleteExpressSync(array $arguments = [])
 * @method \Http\Promise\Promise deleteExpressSyncAsync($arguments = [])
 * @method \Dew\Acs\Result removeSharesFromExpressSync(array $arguments = [])
 * @method \Http\Promise\Promise removeSharesFromExpressSyncAsync($arguments = [])
 */
final class SgwClient extends AcsClient
{
    //
}
