<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto

namespace Dew\Acs\Sls\Metadata;

class Log
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ê
	log.protoacs.sls"1
LogGroupList!
groups (2.acs.sls.LogGroup"z
LogGroup
logs (2.acs.sls.Log
topic (	
source (	
machine_uuid (	
tags (2.acs.sls.LogTag"K
Log
time (%
contents (2.acs.sls.LogContent
time_ns ("(

LogContent
key (	
value ("$
LogTag
key (	
value (	B. Dew\\Acs\\Sls\\Messages‚Dew\\Acs\\Sls\\Metadata'
        , true);

        static::$is_initialized = true;
    }
}

