<?php

declare(strict_types=1);

namespace Dew\Acs\Cddc;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result createMyBase(array $arguments = [])
 * @method \Http\Promise\Promise createMyBaseAsync($arguments = [])
 * @method \Dew\Acs\Result describeRegions(array $arguments = [])
 * @method \Http\Promise\Promise describeRegionsAsync($arguments = [])
 * @method \Dew\Acs\Result createDedicatedHostGroup(array $arguments = [])
 * @method \Http\Promise\Promise createDedicatedHostGroupAsync($arguments = [])
 * @method \Dew\Acs\Result deleteDedicatedHostGroup(array $arguments = [])
 * @method \Http\Promise\Promise deleteDedicatedHostGroupAsync($arguments = [])
 * @method \Dew\Acs\Result modifyDedicatedHostGroupAttribute(array $arguments = [])
 * @method \Http\Promise\Promise modifyDedicatedHostGroupAttributeAsync($arguments = [])
 * @method \Dew\Acs\Result describeDedicatedHostGroups(array $arguments = [])
 * @method \Http\Promise\Promise describeDedicatedHostGroupsAsync($arguments = [])
 * @method \Dew\Acs\Result createDedicatedHost(array $arguments = [])
 * @method \Http\Promise\Promise createDedicatedHostAsync($arguments = [])
 * @method \Dew\Acs\Result describeDedicatedHosts(array $arguments = [])
 * @method \Http\Promise\Promise describeDedicatedHostsAsync($arguments = [])
 * @method \Dew\Acs\Result describeDedicatedHostAttribute(array $arguments = [])
 * @method \Http\Promise\Promise describeDedicatedHostAttributeAsync($arguments = [])
 * @method \Dew\Acs\Result describeHostEcsLevelInfo(array $arguments = [])
 * @method \Http\Promise\Promise describeHostEcsLevelInfoAsync($arguments = [])
 * @method \Dew\Acs\Result describeDedicatedHostDisks(array $arguments = [])
 * @method \Http\Promise\Promise describeDedicatedHostDisksAsync($arguments = [])
 * @method \Dew\Acs\Result modifyDedicatedHostAttribute(array $arguments = [])
 * @method \Http\Promise\Promise modifyDedicatedHostAttributeAsync($arguments = [])
 * @method \Dew\Acs\Result replaceDedicatedHost(array $arguments = [])
 * @method \Http\Promise\Promise replaceDedicatedHostAsync($arguments = [])
 * @method \Dew\Acs\Result restartDedicatedHost(array $arguments = [])
 * @method \Http\Promise\Promise restartDedicatedHostAsync($arguments = [])
 * @method \Dew\Acs\Result describeHostWebShell(array $arguments = [])
 * @method \Http\Promise\Promise describeHostWebShellAsync($arguments = [])
 * @method \Dew\Acs\Result modifyDedicatedHostClass(array $arguments = [])
 * @method \Http\Promise\Promise modifyDedicatedHostClassAsync($arguments = [])
 * @method \Dew\Acs\Result tagResources(array $arguments = [])
 * @method \Http\Promise\Promise tagResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result listTagResources(array $arguments = [])
 * @method \Http\Promise\Promise listTagResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result untagResources(array $arguments = [])
 * @method \Http\Promise\Promise untagResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result createDedicatedHostAccount(array $arguments = [])
 * @method \Http\Promise\Promise createDedicatedHostAccountAsync($arguments = [])
 * @method \Dew\Acs\Result deleteDedicatedHostAccount(array $arguments = [])
 * @method \Http\Promise\Promise deleteDedicatedHostAccountAsync($arguments = [])
 * @method \Dew\Acs\Result modifyDedicatedHostPassword(array $arguments = [])
 * @method \Http\Promise\Promise modifyDedicatedHostPasswordAsync($arguments = [])
 * @method \Dew\Acs\Result modifyDedicatedHostAccount(array $arguments = [])
 * @method \Http\Promise\Promise modifyDedicatedHostAccountAsync($arguments = [])
 * @method \Dew\Acs\Result queryHostInstanceConsoleInfo(array $arguments = [])
 * @method \Http\Promise\Promise queryHostInstanceConsoleInfoAsync($arguments = [])
 * @method \Dew\Acs\Result queryHostBaseInfoByInstance(array $arguments = [])
 * @method \Http\Promise\Promise queryHostBaseInfoByInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result addPrinsInstance(array $arguments = [])
 * @method \Http\Promise\Promise addPrinsInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result createPrinsBackupPlan(array $arguments = [])
 * @method \Http\Promise\Promise createPrinsBackupPlanAsync($arguments = [])
 * @method \Dew\Acs\Result describePrinsInstance(array $arguments = [])
 * @method \Http\Promise\Promise describePrinsInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result describePrinsBackupPlan(array $arguments = [])
 * @method \Http\Promise\Promise describePrinsBackupPlanAsync($arguments = [])
 * @method \Dew\Acs\Result describePrinsEcsInstances(array $arguments = [])
 * @method \Http\Promise\Promise describePrinsEcsInstancesAsync($arguments = [])
 * @method \Dew\Acs\Result getPrinsEventList(array $arguments = [])
 * @method \Http\Promise\Promise getPrinsEventListAsync($arguments = [])
 * @method \Dew\Acs\Result getPrinsMetricsList(array $arguments = [])
 * @method \Http\Promise\Promise getPrinsMetricsListAsync($arguments = [])
 * @method \Dew\Acs\Result listPrinsSQLErrorLog(array $arguments = [])
 * @method \Http\Promise\Promise listPrinsSQLErrorLogAsync($arguments = [])
 * @method \Dew\Acs\Result listPrinsParams(array $arguments = [])
 * @method \Http\Promise\Promise listPrinsParamsAsync($arguments = [])
 * @method \Dew\Acs\Result listPrinsInstances(array $arguments = [])
 * @method \Http\Promise\Promise listPrinsInstancesAsync($arguments = [])
 */
final class CddcClient extends AcsClient
{
    //
}
