<?php

declare(strict_types=1);

namespace Dew\Acs\Dyplsapi;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result bindAxb(array $arguments = [])
 * @method \Http\Promise\Promise bindAxbAsync($arguments = [])
 * @method \Dew\Acs\Result bindAxn(array $arguments = [])
 * @method \Http\Promise\Promise bindAxnAsync($arguments = [])
 * @method \Dew\Acs\Result bindAxnExtension(array $arguments = [])
 * @method \Http\Promise\Promise bindAxnExtensionAsync($arguments = [])
 * @method \Dew\Acs\Result bindAxg(array $arguments = [])
 * @method \Http\Promise\Promise bindAxgAsync($arguments = [])
 * @method \Dew\Acs\Result bindBatchAxg(array $arguments = [])
 * @method \Http\Promise\Promise bindBatchAxgAsync($arguments = [])
 * @method \Dew\Acs\Result updateSubscription(array $arguments = [])
 * @method \Http\Promise\Promise updateSubscriptionAsync($arguments = [])
 * @method \Dew\Acs\Result unbindSubscription(array $arguments = [])
 * @method \Http\Promise\Promise unbindSubscriptionAsync($arguments = [])
 * @method \Dew\Acs\Result querySubscriptionDetail(array $arguments = [])
 * @method \Http\Promise\Promise querySubscriptionDetailAsync($arguments = [])
 * @method \Dew\Acs\Result querySubsId(array $arguments = [])
 * @method \Http\Promise\Promise querySubsIdAsync($arguments = [])
 * @method \Dew\Acs\Result querySecretNoDetail(array $arguments = [])
 * @method \Http\Promise\Promise querySecretNoDetailAsync($arguments = [])
 * @method \Dew\Acs\Result createAxgGroup(array $arguments = [])
 * @method \Http\Promise\Promise createAxgGroupAsync($arguments = [])
 * @method \Dew\Acs\Result operateAxgGroup(array $arguments = [])
 * @method \Http\Promise\Promise operateAxgGroupAsync($arguments = [])
 * @method \Dew\Acs\Result deleteAxgGroup(array $arguments = [])
 * @method \Http\Promise\Promise deleteAxgGroupAsync($arguments = [])
 * @method \Dew\Acs\Result queryRecordFileDownloadUrl(array $arguments = [])
 * @method \Http\Promise\Promise queryRecordFileDownloadUrlAsync($arguments = [])
 * @method \Dew\Acs\Result getTotalPublicUrl(array $arguments = [])
 * @method \Http\Promise\Promise getTotalPublicUrlAsync($arguments = [])
 * @method \Dew\Acs\Result getSecretAsrDetail(array $arguments = [])
 * @method \Http\Promise\Promise getSecretAsrDetailAsync($arguments = [])
 * @method \Dew\Acs\Result addSecretBlacklist(array $arguments = [])
 * @method \Http\Promise\Promise addSecretBlacklistAsync($arguments = [])
 * @method \Dew\Acs\Result deleteSecretBlacklist(array $arguments = [])
 * @method \Http\Promise\Promise deleteSecretBlacklistAsync($arguments = [])
 * @method \Dew\Acs\Result operateBlackNo(array $arguments = [])
 * @method \Http\Promise\Promise operateBlackNoAsync($arguments = [])
 * @method \Dew\Acs\Result querySecretNoRemain(array $arguments = [])
 * @method \Http\Promise\Promise querySecretNoRemainAsync($arguments = [])
 * @method \Dew\Acs\Result buySecretNo(array $arguments = [])
 * @method \Http\Promise\Promise buySecretNoAsync($arguments = [])
 * @method \Dew\Acs\Result releaseSecretNo(array $arguments = [])
 * @method \Http\Promise\Promise releaseSecretNoAsync($arguments = [])
 * @method \Dew\Acs\Result lockSecretNo(array $arguments = [])
 * @method \Http\Promise\Promise lockSecretNoAsync($arguments = [])
 * @method \Dew\Acs\Result unlockSecretNo(array $arguments = [])
 * @method \Http\Promise\Promise unlockSecretNoAsync($arguments = [])
 * @method \Dew\Acs\Result createPickUpWaybillPreQuery(array $arguments = [])
 * @method \Http\Promise\Promise createPickUpWaybillPreQueryAsync($arguments = [])
 * @method \Dew\Acs\Result createPickUpWaybill(array $arguments = [])
 * @method \Http\Promise\Promise createPickUpWaybillAsync($arguments = [])
 * @method \Dew\Acs\Result cancelPickUpWaybill(array $arguments = [])
 * @method \Http\Promise\Promise cancelPickUpWaybillAsync($arguments = [])
 * @method \Dew\Acs\Result addAxnTrackNo(array $arguments = [])
 * @method \Http\Promise\Promise addAxnTrackNoAsync($arguments = [])
 * @method \Dew\Acs\Result queryPhoneNoAByTrackNo(array $arguments = [])
 * @method \Http\Promise\Promise queryPhoneNoAByTrackNoAsync($arguments = [])
 * @method \Dew\Acs\Result unBindAXB(array $arguments = [])
 * @method \Http\Promise\Promise unBindAXBAsync($arguments = [])
 * @method \Dew\Acs\Result bindXB(array $arguments = [])
 * @method \Http\Promise\Promise bindXBAsync($arguments = [])
 * @method \Dew\Acs\Result bindAXBCall(array $arguments = [])
 * @method \Http\Promise\Promise bindAXBCallAsync($arguments = [])
 * @method \Dew\Acs\Result unBindXB(array $arguments = [])
 * @method \Http\Promise\Promise unBindXBAsync($arguments = [])
 * @method \Dew\Acs\Result querySoundRecord(array $arguments = [])
 * @method \Http\Promise\Promise querySoundRecordAsync($arguments = [])
 * @method \Dew\Acs\Result createSmsSign(array $arguments = [])
 * @method \Http\Promise\Promise createSmsSignAsync($arguments = [])
 * @method \Dew\Acs\Result listXTelephones(array $arguments = [])
 * @method \Http\Promise\Promise listXTelephonesAsync($arguments = [])
 * @method \Dew\Acs\Result getXConfig(array $arguments = [])
 * @method \Http\Promise\Promise getXConfigAsync($arguments = [])
 * @method \Dew\Acs\Result configX(array $arguments = [])
 * @method \Http\Promise\Promise configXAsync($arguments = [])
 * @method \Dew\Acs\Result getXDefaultConfig(array $arguments = [])
 * @method \Http\Promise\Promise getXDefaultConfigAsync($arguments = [])
 */
final class DyplsapiClient extends AcsClient
{
    //
}
