<?php

declare(strict_types=1);

namespace Dew\Acs\Actiontrail;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result createAdvancedQueryHistory(array $arguments = [])
 * @method \Http\Promise\Promise createAdvancedQueryHistoryAsync($arguments = [])
 * @method \Dew\Acs\Result createAdvancedQueryTemplate(array $arguments = [])
 * @method \Http\Promise\Promise createAdvancedQueryTemplateAsync($arguments = [])
 * @method \Dew\Acs\Result createDeliveryHistoryJob(array $arguments = [])
 * @method \Http\Promise\Promise createDeliveryHistoryJobAsync($arguments = [])
 * @method \Dew\Acs\Result createTrail(array $arguments = [])
 * @method \Http\Promise\Promise createTrailAsync($arguments = [])
 * @method \Dew\Acs\Result deleteAdvancedQueryHistory(array $arguments = [])
 * @method \Http\Promise\Promise deleteAdvancedQueryHistoryAsync($arguments = [])
 * @method \Dew\Acs\Result deleteAdvancedQueryTemplate(array $arguments = [])
 * @method \Http\Promise\Promise deleteAdvancedQueryTemplateAsync($arguments = [])
 * @method \Dew\Acs\Result deleteDataEventSelector(array $arguments = [])
 * @method \Http\Promise\Promise deleteDataEventSelectorAsync($arguments = [])
 * @method \Dew\Acs\Result deleteDeliveryHistoryJob(array $arguments = [])
 * @method \Http\Promise\Promise deleteDeliveryHistoryJobAsync($arguments = [])
 * @method \Dew\Acs\Result deleteTrail(array $arguments = [])
 * @method \Http\Promise\Promise deleteTrailAsync($arguments = [])
 * @method \Dew\Acs\Result describeAdvancedQueryHistory(array $arguments = [])
 * @method \Http\Promise\Promise describeAdvancedQueryHistoryAsync($arguments = [])
 * @method \Dew\Acs\Result describeAdvancedQueryTemplate(array $arguments = [])
 * @method \Http\Promise\Promise describeAdvancedQueryTemplateAsync($arguments = [])
 * @method \Dew\Acs\Result describeRegions(array $arguments = [])
 * @method \Http\Promise\Promise describeRegionsAsync($arguments = [])
 * @method \Dew\Acs\Result describeResourceLifeCycleEvents(array $arguments = [])
 * @method \Http\Promise\Promise describeResourceLifeCycleEventsAsync($arguments = [])
 * @method \Dew\Acs\Result describeScenes(array $arguments = [])
 * @method \Http\Promise\Promise describeScenesAsync($arguments = [])
 * @method \Dew\Acs\Result describeSearchTemplates(array $arguments = [])
 * @method \Http\Promise\Promise describeSearchTemplatesAsync($arguments = [])
 * @method \Dew\Acs\Result describeTrails(array $arguments = [])
 * @method \Http\Promise\Promise describeTrailsAsync($arguments = [])
 * @method \Dew\Acs\Result describeUserAlertCount(array $arguments = [])
 * @method \Http\Promise\Promise describeUserAlertCountAsync($arguments = [])
 * @method \Dew\Acs\Result describeUserLogCount(array $arguments = [])
 * @method \Http\Promise\Promise describeUserLogCountAsync($arguments = [])
 * @method \Dew\Acs\Result enableInsight(array $arguments = [])
 * @method \Http\Promise\Promise enableInsightAsync($arguments = [])
 * @method \Dew\Acs\Result getAccessKeyLastUsedEvents(array $arguments = [])
 * @method \Http\Promise\Promise getAccessKeyLastUsedEventsAsync($arguments = [])
 * @method \Dew\Acs\Result getAccessKeyLastUsedInfo(array $arguments = [])
 * @method \Http\Promise\Promise getAccessKeyLastUsedInfoAsync($arguments = [])
 * @method \Dew\Acs\Result getAccessKeyLastUsedIps(array $arguments = [])
 * @method \Http\Promise\Promise getAccessKeyLastUsedIpsAsync($arguments = [])
 * @method \Dew\Acs\Result getAccessKeyLastUsedProducts(array $arguments = [])
 * @method \Http\Promise\Promise getAccessKeyLastUsedProductsAsync($arguments = [])
 * @method \Dew\Acs\Result getAccessKeyLastUsedResources(array $arguments = [])
 * @method \Http\Promise\Promise getAccessKeyLastUsedResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result getAdvancedQueryTemplate(array $arguments = [])
 * @method \Http\Promise\Promise getAdvancedQueryTemplateAsync($arguments = [])
 * @method \Dew\Acs\Result getDataEventSelector(array $arguments = [])
 * @method \Http\Promise\Promise getDataEventSelectorAsync($arguments = [])
 * @method \Dew\Acs\Result getDeliveryHistoryJob(array $arguments = [])
 * @method \Http\Promise\Promise getDeliveryHistoryJobAsync($arguments = [])
 * @method \Dew\Acs\Result getGlobalEventsStorageRegion(array $arguments = [])
 * @method \Http\Promise\Promise getGlobalEventsStorageRegionAsync($arguments = [])
 * @method \Dew\Acs\Result getGovernanceMetrics(array $arguments = [])
 * @method \Http\Promise\Promise getGovernanceMetricsAsync($arguments = [])
 * @method \Dew\Acs\Result getTrailStatus(array $arguments = [])
 * @method \Http\Promise\Promise getTrailStatusAsync($arguments = [])
 * @method \Dew\Acs\Result listDataEventSelectors(array $arguments = [])
 * @method \Http\Promise\Promise listDataEventSelectorsAsync($arguments = [])
 * @method \Dew\Acs\Result listDataEventServices(array $arguments = [])
 * @method \Http\Promise\Promise listDataEventServicesAsync($arguments = [])
 * @method \Dew\Acs\Result listDeliveryHistoryJobs(array $arguments = [])
 * @method \Http\Promise\Promise listDeliveryHistoryJobsAsync($arguments = [])
 * @method \Dew\Acs\Result lookupEvents(array $arguments = [])
 * @method \Http\Promise\Promise lookupEventsAsync($arguments = [])
 * @method \Dew\Acs\Result putDataEventSelector(array $arguments = [])
 * @method \Http\Promise\Promise putDataEventSelectorAsync($arguments = [])
 * @method \Dew\Acs\Result startLogging(array $arguments = [])
 * @method \Http\Promise\Promise startLoggingAsync($arguments = [])
 * @method \Dew\Acs\Result stopLogging(array $arguments = [])
 * @method \Http\Promise\Promise stopLoggingAsync($arguments = [])
 * @method \Dew\Acs\Result updateAdvancedQueryTemplate(array $arguments = [])
 * @method \Http\Promise\Promise updateAdvancedQueryTemplateAsync($arguments = [])
 * @method \Dew\Acs\Result updateGlobalEventsStorageRegion(array $arguments = [])
 * @method \Http\Promise\Promise updateGlobalEventsStorageRegionAsync($arguments = [])
 * @method \Dew\Acs\Result updateTrail(array $arguments = [])
 * @method \Http\Promise\Promise updateTrailAsync($arguments = [])
 */
final class ActiontrailClient extends AcsClient
{
    //
}
