<?php

declare(strict_types=1);

namespace Dew\Acs\Bailian;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result listFile(array $arguments = [])
 * @method \Http\Promise\Promise listFileAsync($arguments = [])
 * @method \Dew\Acs\Result deleteCategory(array $arguments = [])
 * @method \Http\Promise\Promise deleteCategoryAsync($arguments = [])
 * @method \Dew\Acs\Result listCategory(array $arguments = [])
 * @method \Http\Promise\Promise listCategoryAsync($arguments = [])
 * @method \Dew\Acs\Result addCategory(array $arguments = [])
 * @method \Http\Promise\Promise addCategoryAsync($arguments = [])
 * @method \Dew\Acs\Result addFile(array $arguments = [])
 * @method \Http\Promise\Promise addFileAsync($arguments = [])
 * @method \Dew\Acs\Result applyFileUploadLease(array $arguments = [])
 * @method \Http\Promise\Promise applyFileUploadLeaseAsync($arguments = [])
 * @method \Dew\Acs\Result deleteFile(array $arguments = [])
 * @method \Http\Promise\Promise deleteFileAsync($arguments = [])
 * @method \Dew\Acs\Result describeFile(array $arguments = [])
 * @method \Http\Promise\Promise describeFileAsync($arguments = [])
 * @method \Dew\Acs\Result createIndex(array $arguments = [])
 * @method \Http\Promise\Promise createIndexAsync($arguments = [])
 * @method \Dew\Acs\Result getIndexJobStatus(array $arguments = [])
 * @method \Http\Promise\Promise getIndexJobStatusAsync($arguments = [])
 * @method \Dew\Acs\Result submitIndexJob(array $arguments = [])
 * @method \Http\Promise\Promise submitIndexJobAsync($arguments = [])
 * @method \Dew\Acs\Result submitIndexAddDocumentsJob(array $arguments = [])
 * @method \Http\Promise\Promise submitIndexAddDocumentsJobAsync($arguments = [])
 * @method \Dew\Acs\Result retrieve(array $arguments = [])
 * @method \Http\Promise\Promise retrieveAsync($arguments = [])
 * @method \Dew\Acs\Result listIndexDocuments(array $arguments = [])
 * @method \Http\Promise\Promise listIndexDocumentsAsync($arguments = [])
 * @method \Dew\Acs\Result listChunks(array $arguments = [])
 * @method \Http\Promise\Promise listChunksAsync($arguments = [])
 * @method \Dew\Acs\Result listIndices(array $arguments = [])
 * @method \Http\Promise\Promise listIndicesAsync($arguments = [])
 * @method \Dew\Acs\Result deleteIndex(array $arguments = [])
 * @method \Http\Promise\Promise deleteIndexAsync($arguments = [])
 * @method \Dew\Acs\Result deleteIndexDocument(array $arguments = [])
 * @method \Http\Promise\Promise deleteIndexDocumentAsync($arguments = [])
 * @method \Dew\Acs\Result createPromptTemplate(array $arguments = [])
 * @method \Http\Promise\Promise createPromptTemplateAsync($arguments = [])
 * @method \Dew\Acs\Result getPromptTemplate(array $arguments = [])
 * @method \Http\Promise\Promise getPromptTemplateAsync($arguments = [])
 * @method \Dew\Acs\Result updatePromptTemplate(array $arguments = [])
 * @method \Http\Promise\Promise updatePromptTemplateAsync($arguments = [])
 * @method \Dew\Acs\Result deletePromptTemplate(array $arguments = [])
 * @method \Http\Promise\Promise deletePromptTemplateAsync($arguments = [])
 * @method \Dew\Acs\Result listPromptTemplates(array $arguments = [])
 * @method \Http\Promise\Promise listPromptTemplatesAsync($arguments = [])
 * @method \Dew\Acs\Result createMemory(array $arguments = [])
 * @method \Http\Promise\Promise createMemoryAsync($arguments = [])
 * @method \Dew\Acs\Result getMemory(array $arguments = [])
 * @method \Http\Promise\Promise getMemoryAsync($arguments = [])
 * @method \Dew\Acs\Result updateMemory(array $arguments = [])
 * @method \Http\Promise\Promise updateMemoryAsync($arguments = [])
 * @method \Dew\Acs\Result deleteMemory(array $arguments = [])
 * @method \Http\Promise\Promise deleteMemoryAsync($arguments = [])
 * @method \Dew\Acs\Result listMemories(array $arguments = [])
 * @method \Http\Promise\Promise listMemoriesAsync($arguments = [])
 * @method \Dew\Acs\Result createMemoryNode(array $arguments = [])
 * @method \Http\Promise\Promise createMemoryNodeAsync($arguments = [])
 * @method \Dew\Acs\Result getMemoryNode(array $arguments = [])
 * @method \Http\Promise\Promise getMemoryNodeAsync($arguments = [])
 * @method \Dew\Acs\Result updateMemoryNode(array $arguments = [])
 * @method \Http\Promise\Promise updateMemoryNodeAsync($arguments = [])
 * @method \Dew\Acs\Result deleteMemoryNode(array $arguments = [])
 * @method \Http\Promise\Promise deleteMemoryNodeAsync($arguments = [])
 * @method \Dew\Acs\Result listMemoryNodes(array $arguments = [])
 * @method \Http\Promise\Promise listMemoryNodesAsync($arguments = [])
 */
final class BailianClient extends AcsClient
{
    //
}
