<?php

declare(strict_types=1);

namespace Dew\Acs\Cloudphone;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result runInstances(array $arguments = [])
 * @method \Http\Promise\Promise runInstancesAsync($arguments = [])
 * @method \Dew\Acs\Result deleteInstances(array $arguments = [])
 * @method \Http\Promise\Promise deleteInstancesAsync($arguments = [])
 * @method \Dew\Acs\Result startInstances(array $arguments = [])
 * @method \Http\Promise\Promise startInstancesAsync($arguments = [])
 * @method \Dew\Acs\Result stopInstances(array $arguments = [])
 * @method \Http\Promise\Promise stopInstancesAsync($arguments = [])
 * @method \Dew\Acs\Result renewInstances(array $arguments = [])
 * @method \Http\Promise\Promise renewInstancesAsync($arguments = [])
 * @method \Dew\Acs\Result resetInstances(array $arguments = [])
 * @method \Http\Promise\Promise resetInstancesAsync($arguments = [])
 * @method \Dew\Acs\Result rebootInstances(array $arguments = [])
 * @method \Http\Promise\Promise rebootInstancesAsync($arguments = [])
 * @method \Dew\Acs\Result updateInstanceAttribute(array $arguments = [])
 * @method \Http\Promise\Promise updateInstanceAttributeAsync($arguments = [])
 * @method \Dew\Acs\Result listInstances(array $arguments = [])
 * @method \Http\Promise\Promise listInstancesAsync($arguments = [])
 * @method \Dew\Acs\Result listInstanceTypes(array $arguments = [])
 * @method \Http\Promise\Promise listInstanceTypesAsync($arguments = [])
 * @method \Dew\Acs\Result listInstanceVncUrl(array $arguments = [])
 * @method \Http\Promise\Promise listInstanceVncUrlAsync($arguments = [])
 * @method \Dew\Acs\Result listRegions(array $arguments = [])
 * @method \Http\Promise\Promise listRegionsAsync($arguments = [])
 * @method \Dew\Acs\Result listZones(array $arguments = [])
 * @method \Http\Promise\Promise listZonesAsync($arguments = [])
 * @method \Dew\Acs\Result createImage(array $arguments = [])
 * @method \Http\Promise\Promise createImageAsync($arguments = [])
 * @method \Dew\Acs\Result importImage(array $arguments = [])
 * @method \Http\Promise\Promise importImageAsync($arguments = [])
 * @method \Dew\Acs\Result copyImage(array $arguments = [])
 * @method \Http\Promise\Promise copyImageAsync($arguments = [])
 * @method \Dew\Acs\Result deleteImages(array $arguments = [])
 * @method \Http\Promise\Promise deleteImagesAsync($arguments = [])
 * @method \Dew\Acs\Result updateImageAttribute(array $arguments = [])
 * @method \Http\Promise\Promise updateImageAttributeAsync($arguments = [])
 * @method \Dew\Acs\Result listImages(array $arguments = [])
 * @method \Http\Promise\Promise listImagesAsync($arguments = [])
 * @method \Dew\Acs\Result listImageSharePermission(array $arguments = [])
 * @method \Http\Promise\Promise listImageSharePermissionAsync($arguments = [])
 * @method \Dew\Acs\Result importKeyPair(array $arguments = [])
 * @method \Http\Promise\Promise importKeyPairAsync($arguments = [])
 * @method \Dew\Acs\Result deleteKeyPairs(array $arguments = [])
 * @method \Http\Promise\Promise deleteKeyPairsAsync($arguments = [])
 * @method \Dew\Acs\Result listKeyPairs(array $arguments = [])
 * @method \Http\Promise\Promise listKeyPairsAsync($arguments = [])
 * @method \Dew\Acs\Result cancelTask(array $arguments = [])
 * @method \Http\Promise\Promise cancelTaskAsync($arguments = [])
 * @method \Dew\Acs\Result listTasks(array $arguments = [])
 * @method \Http\Promise\Promise listTasksAsync($arguments = [])
 * @method \Dew\Acs\Result runCommand(array $arguments = [])
 * @method \Http\Promise\Promise runCommandAsync($arguments = [])
 * @method \Dew\Acs\Result sendFile(array $arguments = [])
 * @method \Http\Promise\Promise sendFileAsync($arguments = [])
 * @method \Dew\Acs\Result installApplication(array $arguments = [])
 * @method \Http\Promise\Promise installApplicationAsync($arguments = [])
 * @method \Dew\Acs\Result uninstallApplication(array $arguments = [])
 * @method \Http\Promise\Promise uninstallApplicationAsync($arguments = [])
 * @method \Dew\Acs\Result fetchFile(array $arguments = [])
 * @method \Http\Promise\Promise fetchFileAsync($arguments = [])
 * @method \Dew\Acs\Result tagResources(array $arguments = [])
 * @method \Http\Promise\Promise tagResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result listTagResources(array $arguments = [])
 * @method \Http\Promise\Promise listTagResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result untagResources(array $arguments = [])
 * @method \Http\Promise\Promise untagResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result listTagKeys(array $arguments = [])
 * @method \Http\Promise\Promise listTagKeysAsync($arguments = [])
 * @method \Dew\Acs\Result listTagValues(array $arguments = [])
 * @method \Http\Promise\Promise listTagValuesAsync($arguments = [])
 */
final class CloudphoneClient extends AcsClient
{
    //
}
