<?php

declare(strict_types=1);

namespace Dew\Acs\RdsAi;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result chatMessages(array $arguments = [])
 * @method \Http\Promise\Promise chatMessagesAsync($arguments = [])
 * @method \Dew\Acs\Result modifyMessagesFeedbacks(array $arguments = [])
 * @method \Http\Promise\Promise modifyMessagesFeedbacksAsync($arguments = [])
 * @method \Dew\Acs\Result chatMessagesTaskStop(array $arguments = [])
 * @method \Http\Promise\Promise chatMessagesTaskStopAsync($arguments = [])
 * @method \Dew\Acs\Result getConversations(array $arguments = [])
 * @method \Http\Promise\Promise getConversationsAsync($arguments = [])
 * @method \Dew\Acs\Result getMessages(array $arguments = [])
 * @method \Http\Promise\Promise getMessagesAsync($arguments = [])
 * @method \Dew\Acs\Result describeEventsList(array $arguments = [])
 * @method \Http\Promise\Promise describeEventsListAsync($arguments = [])
 * @method \Dew\Acs\Result listCustomAgentTools(array $arguments = [])
 * @method \Http\Promise\Promise listCustomAgentToolsAsync($arguments = [])
 * @method \Dew\Acs\Result updateCustomAgent(array $arguments = [])
 * @method \Http\Promise\Promise updateCustomAgentAsync($arguments = [])
 * @method \Dew\Acs\Result getCustomAgent(array $arguments = [])
 * @method \Http\Promise\Promise getCustomAgentAsync($arguments = [])
 * @method \Dew\Acs\Result listCustomAgent(array $arguments = [])
 * @method \Http\Promise\Promise listCustomAgentAsync($arguments = [])
 * @method \Dew\Acs\Result deleteCustomAgent(array $arguments = [])
 * @method \Http\Promise\Promise deleteCustomAgentAsync($arguments = [])
 * @method \Dew\Acs\Result createCustomAgent(array $arguments = [])
 * @method \Http\Promise\Promise createCustomAgentAsync($arguments = [])
 * @method \Dew\Acs\Result createAppInstance(array $arguments = [])
 * @method \Http\Promise\Promise createAppInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result deleteAppInstance(array $arguments = [])
 * @method \Http\Promise\Promise deleteAppInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result restartInstance(array $arguments = [])
 * @method \Http\Promise\Promise restartInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result stopInstance(array $arguments = [])
 * @method \Http\Promise\Promise stopInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result startInstance(array $arguments = [])
 * @method \Http\Promise\Promise startInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result resetInstancePassword(array $arguments = [])
 * @method \Http\Promise\Promise resetInstancePasswordAsync($arguments = [])
 * @method \Dew\Acs\Result describeAppInstanceAttribute(array $arguments = [])
 * @method \Http\Promise\Promise describeAppInstanceAttributeAsync($arguments = [])
 * @method \Dew\Acs\Result describeAppInstances(array $arguments = [])
 * @method \Http\Promise\Promise describeAppInstancesAsync($arguments = [])
 * @method \Dew\Acs\Result describeInstanceEndpoints(array $arguments = [])
 * @method \Http\Promise\Promise describeInstanceEndpointsAsync($arguments = [])
 * @method \Dew\Acs\Result describeInstanceAuthInfo(array $arguments = [])
 * @method \Http\Promise\Promise describeInstanceAuthInfoAsync($arguments = [])
 * @method \Dew\Acs\Result modifyInstanceAuthConfig(array $arguments = [])
 * @method \Http\Promise\Promise modifyInstanceAuthConfigAsync($arguments = [])
 * @method \Dew\Acs\Result describeInstanceStorageConfig(array $arguments = [])
 * @method \Http\Promise\Promise describeInstanceStorageConfigAsync($arguments = [])
 * @method \Dew\Acs\Result modifyInstanceStorageConfig(array $arguments = [])
 * @method \Http\Promise\Promise modifyInstanceStorageConfigAsync($arguments = [])
 * @method \Dew\Acs\Result modifyInstanceConfig(array $arguments = [])
 * @method \Http\Promise\Promise modifyInstanceConfigAsync($arguments = [])
 * @method \Dew\Acs\Result modifyInstanceRAGConfig(array $arguments = [])
 * @method \Http\Promise\Promise modifyInstanceRAGConfigAsync($arguments = [])
 * @method \Dew\Acs\Result describeInstanceRAGConfig(array $arguments = [])
 * @method \Http\Promise\Promise describeInstanceRAGConfigAsync($arguments = [])
 * @method \Dew\Acs\Result modifyInstanceIpWhitelist(array $arguments = [])
 * @method \Http\Promise\Promise modifyInstanceIpWhitelistAsync($arguments = [])
 * @method \Dew\Acs\Result describeInstanceIpWhitelist(array $arguments = [])
 * @method \Http\Promise\Promise describeInstanceIpWhitelistAsync($arguments = [])
 * @method \Dew\Acs\Result modifyInstanceSSL(array $arguments = [])
 * @method \Http\Promise\Promise modifyInstanceSSLAsync($arguments = [])
 * @method \Dew\Acs\Result describeInstanceSSL(array $arguments = [])
 * @method \Http\Promise\Promise describeInstanceSSLAsync($arguments = [])
 */
final class RdsAiClient extends AcsClient
{
    //
}
