<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: general.proto

namespace Dew\Acs\Tablestore\Metadata;

class General
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
²
general.protoacs.tablestore"&
Error
code (	
message (	"+
CapacityUnit
read (
write (B<ÊDew\\Acs\\Tablestore\\MessagesâDew\\Acs\\Tablestore\\Metadata'
        , true);

        static::$is_initialized = true;
    }
}

