<?php

declare(strict_types=1);

namespace Dew\Acs\VoiceNavigator;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result modifyGreetingConfig(array $arguments = [])
 * @method \Http\Promise\Promise modifyGreetingConfigAsync($arguments = [])
 * @method \Dew\Acs\Result modifySilenceTimeoutConfig(array $arguments = [])
 * @method \Http\Promise\Promise modifySilenceTimeoutConfigAsync($arguments = [])
 * @method \Dew\Acs\Result modifyTTSConfig(array $arguments = [])
 * @method \Http\Promise\Promise modifyTTSConfigAsync($arguments = [])
 * @method \Dew\Acs\Result modifyUnrecognizingConfig(array $arguments = [])
 * @method \Http\Promise\Promise modifyUnrecognizingConfigAsync($arguments = [])
 * @method \Dew\Acs\Result describeTTSConfig(array $arguments = [])
 * @method \Http\Promise\Promise describeTTSConfigAsync($arguments = [])
 * @method \Dew\Acs\Result describeExportProgress(array $arguments = [])
 * @method \Http\Promise\Promise describeExportProgressAsync($arguments = [])
 * @method \Dew\Acs\Result associateChatbotInstance(array $arguments = [])
 * @method \Http\Promise\Promise associateChatbotInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result auditTTSVoice(array $arguments = [])
 * @method \Http\Promise\Promise auditTTSVoiceAsync($arguments = [])
 * @method \Dew\Acs\Result collectedNumber(array $arguments = [])
 * @method \Http\Promise\Promise collectedNumberAsync($arguments = [])
 * @method \Dew\Acs\Result exportStatisticalData(array $arguments = [])
 * @method \Http\Promise\Promise exportStatisticalDataAsync($arguments = [])
 * @method \Dew\Acs\Result silenceTimeout(array $arguments = [])
 * @method \Http\Promise\Promise silenceTimeoutAsync($arguments = [])
 * @method \Dew\Acs\Result describeConversation(array $arguments = [])
 * @method \Http\Promise\Promise describeConversationAsync($arguments = [])
 * @method \Dew\Acs\Result describeConversationContext(array $arguments = [])
 * @method \Http\Promise\Promise describeConversationContextAsync($arguments = [])
 * @method \Dew\Acs\Result listConversationDetails(array $arguments = [])
 * @method \Http\Promise\Promise listConversationDetailsAsync($arguments = [])
 * @method \Dew\Acs\Result queryConversations(array $arguments = [])
 * @method \Http\Promise\Promise queryConversationsAsync($arguments = [])
 * @method \Dew\Acs\Result describeRecording(array $arguments = [])
 * @method \Http\Promise\Promise describeRecordingAsync($arguments = [])
 * @method \Dew\Acs\Result dialogue(array $arguments = [])
 * @method \Http\Promise\Promise dialogueAsync($arguments = [])
 * @method \Dew\Acs\Result endDialogue(array $arguments = [])
 * @method \Http\Promise\Promise endDialogueAsync($arguments = [])
 * @method \Dew\Acs\Result saveRecording(array $arguments = [])
 * @method \Http\Promise\Promise saveRecordingAsync($arguments = [])
 * @method \Dew\Acs\Result listConversations(array $arguments = [])
 * @method \Http\Promise\Promise listConversationsAsync($arguments = [])
 * @method \Dew\Acs\Result beginDialogue(array $arguments = [])
 * @method \Http\Promise\Promise beginDialogueAsync($arguments = [])
 * @method \Dew\Acs\Result exportConversationDetails(array $arguments = [])
 * @method \Http\Promise\Promise exportConversationDetailsAsync($arguments = [])
 * @method \Dew\Acs\Result debugBeginDialogue(array $arguments = [])
 * @method \Http\Promise\Promise debugBeginDialogueAsync($arguments = [])
 * @method \Dew\Acs\Result debugCollectedNumber(array $arguments = [])
 * @method \Http\Promise\Promise debugCollectedNumberAsync($arguments = [])
 * @method \Dew\Acs\Result debugDialogue(array $arguments = [])
 * @method \Http\Promise\Promise debugDialogueAsync($arguments = [])
 * @method \Dew\Acs\Result createInstance(array $arguments = [])
 * @method \Http\Promise\Promise createInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result deleteInstance(array $arguments = [])
 * @method \Http\Promise\Promise deleteInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result disableInstance(array $arguments = [])
 * @method \Http\Promise\Promise disableInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result enableInstance(array $arguments = [])
 * @method \Http\Promise\Promise enableInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result modifyInstance(array $arguments = [])
 * @method \Http\Promise\Promise modifyInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result describeNavigationConfig(array $arguments = [])
 * @method \Http\Promise\Promise describeNavigationConfigAsync($arguments = [])
 * @method \Dew\Acs\Result describeInstance(array $arguments = [])
 * @method \Http\Promise\Promise describeInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result describeStatisticalData(array $arguments = [])
 * @method \Http\Promise\Promise describeStatisticalDataAsync($arguments = [])
 * @method \Dew\Acs\Result listInstances(array $arguments = [])
 * @method \Http\Promise\Promise listInstancesAsync($arguments = [])
 * @method \Dew\Acs\Result listChatbotInstances(array $arguments = [])
 * @method \Http\Promise\Promise listChatbotInstancesAsync($arguments = [])
 * @method \Dew\Acs\Result createDownloadUrl(array $arguments = [])
 * @method \Http\Promise\Promise createDownloadUrlAsync($arguments = [])
 * @method \Dew\Acs\Result listDownloadTasks(array $arguments = [])
 * @method \Http\Promise\Promise listDownloadTasksAsync($arguments = [])
 * @method \Dew\Acs\Result modifyAsrConfig(array $arguments = [])
 * @method \Http\Promise\Promise modifyAsrConfigAsync($arguments = [])
 * @method \Dew\Acs\Result getAsrConfig(array $arguments = [])
 * @method \Http\Promise\Promise getAsrConfigAsync($arguments = [])
 * @method \Dew\Acs\Result getRealTimeConcurrency(array $arguments = [])
 * @method \Http\Promise\Promise getRealTimeConcurrencyAsync($arguments = [])
 */
final class VoiceNavigatorClient extends AcsClient
{
    //
}
