<?php

declare(strict_types=1);

namespace Dew\Acs\Qualitycheck;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result uploadAudioData(array $arguments = [])
 * @method \Http\Promise\Promise uploadAudioDataAsync($arguments = [])
 * @method \Dew\Acs\Result uploadDataV4(array $arguments = [])
 * @method \Http\Promise\Promise uploadDataV4Async($arguments = [])
 * @method \Dew\Acs\Result uploadData(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise uploadDataAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result updateQualityCheckData(array $arguments = [])
 * @method \Http\Promise\Promise updateQualityCheckDataAsync($arguments = [])
 * @method \Dew\Acs\Result addRuleV4(array $arguments = [])
 * @method \Http\Promise\Promise addRuleV4Async($arguments = [])
 * @method \Dew\Acs\Result updateRuleV4(array $arguments = [])
 * @method \Http\Promise\Promise updateRuleV4Async($arguments = [])
 * @method \Dew\Acs\Result listRulesV4(array $arguments = [])
 * @method \Http\Promise\Promise listRulesV4Async($arguments = [])
 * @method \Dew\Acs\Result getRuleV4(array $arguments = [])
 * @method \Http\Promise\Promise getRuleV4Async($arguments = [])
 * @method \Dew\Acs\Result deleteRuleV4(array $arguments = [])
 * @method \Http\Promise\Promise deleteRuleV4Async($arguments = [])
 * @method \Dew\Acs\Result testRuleV4(array $arguments = [])
 * @method \Http\Promise\Promise testRuleV4Async($arguments = [])
 * @method \Dew\Acs\Result deleteCheckTypeToScheme(array $arguments = [])
 * @method \Http\Promise\Promise deleteCheckTypeToSchemeAsync($arguments = [])
 * @method \Dew\Acs\Result createQualityCheckScheme(array $arguments = [])
 * @method \Http\Promise\Promise createQualityCheckSchemeAsync($arguments = [])
 * @method \Dew\Acs\Result updateQualityCheckScheme(array $arguments = [])
 * @method \Http\Promise\Promise updateQualityCheckSchemeAsync($arguments = [])
 * @method \Dew\Acs\Result getQualityCheckScheme(array $arguments = [])
 * @method \Http\Promise\Promise getQualityCheckSchemeAsync($arguments = [])
 * @method \Dew\Acs\Result listQualityCheckScheme(array $arguments = [])
 * @method \Http\Promise\Promise listQualityCheckSchemeAsync($arguments = [])
 * @method \Dew\Acs\Result deleteQualityCheckScheme(array $arguments = [])
 * @method \Http\Promise\Promise deleteQualityCheckSchemeAsync($arguments = [])
 * @method \Dew\Acs\Result updateRuleToScheme(array $arguments = [])
 * @method \Http\Promise\Promise updateRuleToSchemeAsync($arguments = [])
 * @method \Dew\Acs\Result createCheckTypeToScheme(array $arguments = [])
 * @method \Http\Promise\Promise createCheckTypeToSchemeAsync($arguments = [])
 * @method \Dew\Acs\Result updateCheckTypeToScheme(array $arguments = [])
 * @method \Http\Promise\Promise updateCheckTypeToSchemeAsync($arguments = [])
 * @method \Dew\Acs\Result addRuleCategory(array $arguments = [])
 * @method \Http\Promise\Promise addRuleCategoryAsync($arguments = [])
 * @method \Dew\Acs\Result getRuleCategory(array $arguments = [])
 * @method \Http\Promise\Promise getRuleCategoryAsync($arguments = [])
 * @method \Dew\Acs\Result delRuleCategory(array $arguments = [])
 * @method \Http\Promise\Promise delRuleCategoryAsync($arguments = [])
 * @method \Dew\Acs\Result addBusinessCategory(array $arguments = [])
 * @method \Http\Promise\Promise addBusinessCategoryAsync($arguments = [])
 * @method \Dew\Acs\Result deleteBusinessCategory(array $arguments = [])
 * @method \Http\Promise\Promise deleteBusinessCategoryAsync($arguments = [])
 * @method \Dew\Acs\Result getBusinessCategoryList(array $arguments = [])
 * @method \Http\Promise\Promise getBusinessCategoryListAsync($arguments = [])
 * @method \Dew\Acs\Result getSchemeTaskConfig(array $arguments = [])
 * @method \Http\Promise\Promise getSchemeTaskConfigAsync($arguments = [])
 * @method \Dew\Acs\Result createSchemeTaskConfig(array $arguments = [])
 * @method \Http\Promise\Promise createSchemeTaskConfigAsync($arguments = [])
 * @method \Dew\Acs\Result updateSchemeTaskConfig(array $arguments = [])
 * @method \Http\Promise\Promise updateSchemeTaskConfigAsync($arguments = [])
 * @method \Dew\Acs\Result listSchemeTaskConfig(array $arguments = [])
 * @method \Http\Promise\Promise listSchemeTaskConfigAsync($arguments = [])
 * @method \Dew\Acs\Result submitQualityCheckTask(array $arguments = [])
 * @method \Http\Promise\Promise submitQualityCheckTaskAsync($arguments = [])
 * @method \Dew\Acs\Result saveConfigDataSet(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise saveConfigDataSetAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result listDataSet(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise listDataSetAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result deleteDataSet(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise deleteDataSetAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result getResult(array $arguments = [])
 * @method \Http\Promise\Promise getResultAsync($arguments = [])
 * @method \Dew\Acs\Result getResultToReview(array $arguments = [])
 * @method \Http\Promise\Promise getResultToReviewAsync($arguments = [])
 * @method \Dew\Acs\Result listSessionGroup(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise listSessionGroupAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result assignReviewerBySessionGroup(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise assignReviewerBySessionGroupAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result revertAssignedSessionGroup(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise revertAssignedSessionGroupAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result assignReviewer(array $arguments = [])
 * @method \Http\Promise\Promise assignReviewerAsync($arguments = [])
 * @method \Dew\Acs\Result submitReviewInfo(array $arguments = [])
 * @method \Http\Promise\Promise submitReviewInfoAsync($arguments = [])
 * @method \Dew\Acs\Result batchSubmitReviewInfo(array $arguments = [])
 * @method \Http\Promise\Promise batchSubmitReviewInfoAsync($arguments = [])
 * @method \Dew\Acs\Result submitComplaint(array $arguments = [])
 * @method \Http\Promise\Promise submitComplaintAsync($arguments = [])
 * @method \Dew\Acs\Result handleComplaint(array $arguments = [])
 * @method \Http\Promise\Promise handleComplaintAsync($arguments = [])
 * @method \Dew\Acs\Result revertAssignedSession(array $arguments = [])
 * @method \Http\Promise\Promise revertAssignedSessionAsync($arguments = [])
 * @method \Dew\Acs\Result createAsrVocab(array $arguments = [])
 * @method \Http\Promise\Promise createAsrVocabAsync($arguments = [])
 * @method \Dew\Acs\Result updateAsrVocab(array $arguments = [])
 * @method \Http\Promise\Promise updateAsrVocabAsync($arguments = [])
 * @method \Dew\Acs\Result getAsrVocab(array $arguments = [])
 * @method \Http\Promise\Promise getAsrVocabAsync($arguments = [])
 * @method \Dew\Acs\Result listAsrVocab(array $arguments = [])
 * @method \Http\Promise\Promise listAsrVocabAsync($arguments = [])
 * @method \Dew\Acs\Result deleteAsrVocab(array $arguments = [])
 * @method \Http\Promise\Promise deleteAsrVocabAsync($arguments = [])
 * @method \Dew\Acs\Result getCustomizationConfigList(array $arguments = [])
 * @method \Http\Promise\Promise getCustomizationConfigListAsync($arguments = [])
 * @method \Dew\Acs\Result deleteCustomizationConfig(array $arguments = [])
 * @method \Http\Promise\Promise deleteCustomizationConfigAsync($arguments = [])
 * @method \Dew\Acs\Result submitPrecisionTask(array $arguments = [])
 * @method \Http\Promise\Promise submitPrecisionTaskAsync($arguments = [])
 * @method \Dew\Acs\Result getPrecisionTask(array $arguments = [])
 * @method \Http\Promise\Promise getPrecisionTaskAsync($arguments = [])
 * @method \Dew\Acs\Result listPrecisionTask(array $arguments = [])
 * @method \Http\Promise\Promise listPrecisionTaskAsync($arguments = [])
 * @method \Dew\Acs\Result deletePrecisionTask(array $arguments = [])
 * @method \Http\Promise\Promise deletePrecisionTaskAsync($arguments = [])
 * @method \Dew\Acs\Result getNextResultToVerify(array $arguments = [])
 * @method \Http\Promise\Promise getNextResultToVerifyAsync($arguments = [])
 * @method \Dew\Acs\Result verifyFile(array $arguments = [])
 * @method \Http\Promise\Promise verifyFileAsync($arguments = [])
 * @method \Dew\Acs\Result verifySentence(array $arguments = [])
 * @method \Http\Promise\Promise verifySentenceAsync($arguments = [])
 * @method \Dew\Acs\Result createTaskAssignRule(array $arguments = [])
 * @method \Http\Promise\Promise createTaskAssignRuleAsync($arguments = [])
 * @method \Dew\Acs\Result updateTaskAssignRule(array $arguments = [])
 * @method \Http\Promise\Promise updateTaskAssignRuleAsync($arguments = [])
 * @method \Dew\Acs\Result listTaskAssignRules(array $arguments = [])
 * @method \Http\Promise\Promise listTaskAssignRulesAsync($arguments = [])
 * @method \Dew\Acs\Result deleteTaskAssignRule(array $arguments = [])
 * @method \Http\Promise\Promise deleteTaskAssignRuleAsync($arguments = [])
 * @method \Dew\Acs\Result createWarningConfig(array $arguments = [])
 * @method \Http\Promise\Promise createWarningConfigAsync($arguments = [])
 * @method \Dew\Acs\Result updateWarningConfig(array $arguments = [])
 * @method \Http\Promise\Promise updateWarningConfigAsync($arguments = [])
 * @method \Dew\Acs\Result listWarningConfig(array $arguments = [])
 * @method \Http\Promise\Promise listWarningConfigAsync($arguments = [])
 * @method \Dew\Acs\Result deleteWarningConfig(array $arguments = [])
 * @method \Http\Promise\Promise deleteWarningConfigAsync($arguments = [])
 * @method \Dew\Acs\Result createSkillGroupConfig(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise createSkillGroupConfigAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result updateSkillGroupConfig(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise updateSkillGroupConfigAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result getSkillGroupConfig(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise getSkillGroupConfigAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result listSkillGroupConfig(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise listSkillGroupConfigAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result deleteSkillGroupConfig(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise deleteSkillGroupConfigAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result applyWsToken(array $arguments = [])
 * @method \Http\Promise\Promise applyWsTokenAsync($arguments = [])
 * @method \Dew\Acs\Result getSyncResult(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise getSyncResultAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result syncQualityCheck(array $arguments = [])
 * @method \Http\Promise\Promise syncQualityCheckAsync($arguments = [])
 * @method \Dew\Acs\Result updateSyncQualityCheckData(array $arguments = [])
 * @method \Http\Promise\Promise updateSyncQualityCheckDataAsync($arguments = [])
 * @method \Dew\Acs\Result deleteSchemeTaskConfig(array $arguments = [])
 * @method \Http\Promise\Promise deleteSchemeTaskConfigAsync($arguments = [])
 * @method \Dew\Acs\Result deleteRule(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise deleteRuleAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result getRuleById(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise getRuleByIdAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result getRulesCountList(array $arguments = [])
 * @method \Http\Promise\Promise getRulesCountListAsync($arguments = [])
 * @method \Dew\Acs\Result updateRuleById(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise updateRuleByIdAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result updateRule(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise updateRuleAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result uploadRule(array $arguments = [])
 * @method \Http\Promise\Promise uploadRuleAsync($arguments = [])
 * @method \Dew\Acs\Result getRuleDetail(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise getRuleDetailAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result getRule(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise getRuleAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result listRules(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise listRulesAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result invalidRule(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise invalidRuleAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result getScoreInfo(array $arguments = []) {@deprecated 2019-01-15}
 * @method \Http\Promise\Promise getScoreInfoAsync($arguments = []) {@deprecated 2019-01-15}
 * @method \Dew\Acs\Result uploadDataSync(array $arguments = [])
 * @method \Http\Promise\Promise uploadDataSyncAsync($arguments = [])
 * @method \Dew\Acs\Result listUsers(array $arguments = [])
 * @method \Http\Promise\Promise listUsersAsync($arguments = [])
 * @method \Dew\Acs\Result updateUser(array $arguments = [])
 * @method \Http\Promise\Promise updateUserAsync($arguments = [])
 * @method \Dew\Acs\Result createMiningTask(array $arguments = [])
 * @method \Http\Promise\Promise createMiningTaskAsync($arguments = [])
 * @method \Dew\Acs\Result getMiningTaskResult(array $arguments = [])
 * @method \Http\Promise\Promise getMiningTaskResultAsync($arguments = [])
 */
final class QualitycheckClient extends AcsClient
{
    //
}
