<?php

declare(strict_types=1);

namespace Dew\Acs\Config;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result getDiscoveredResourceCounts(array $arguments = [])
 * @method \Http\Promise\Promise getDiscoveredResourceCountsAsync($arguments = [])
 * @method \Dew\Acs\Result listDiscoveredResources(array $arguments = [])
 * @method \Http\Promise\Promise listDiscoveredResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result describeDiscoveredResource(array $arguments = [])
 * @method \Http\Promise\Promise describeDiscoveredResourceAsync($arguments = [])
 * @method \Dew\Acs\Result getResourceComplianceTimeline(array $arguments = [])
 * @method \Http\Promise\Promise getResourceComplianceTimelineAsync($arguments = [])
 * @method \Dew\Acs\Result getResourceConfigurationTimeline(array $arguments = [])
 * @method \Http\Promise\Promise getResourceConfigurationTimelineAsync($arguments = [])
 * @method \Dew\Acs\Result getDiscoveredResourceSummary(array $arguments = [])
 * @method \Http\Promise\Promise getDiscoveredResourceSummaryAsync($arguments = [])
 * @method \Dew\Acs\Result getSupportedResourceTypes(array $arguments = [])
 * @method \Http\Promise\Promise getSupportedResourceTypesAsync($arguments = [])
 * @method \Dew\Acs\Result deleteConfigRules(array $arguments = [])
 * @method \Http\Promise\Promise deleteConfigRulesAsync($arguments = [])
 * @method \Dew\Acs\Result startConfigRuleEvaluation(array $arguments = [])
 * @method \Http\Promise\Promise startConfigRuleEvaluationAsync($arguments = [])
 * @method \Dew\Acs\Result stopConfigRules(array $arguments = [])
 * @method \Http\Promise\Promise stopConfigRulesAsync($arguments = [])
 * @method \Dew\Acs\Result listConfigRules(array $arguments = [])
 * @method \Http\Promise\Promise listConfigRulesAsync($arguments = [])
 * @method \Dew\Acs\Result describeEvaluationResults(array $arguments = [])
 * @method \Http\Promise\Promise describeEvaluationResultsAsync($arguments = [])
 * @method \Dew\Acs\Result describeCompliance(array $arguments = [])
 * @method \Http\Promise\Promise describeComplianceAsync($arguments = [])
 * @method \Dew\Acs\Result describeComplianceSummary(array $arguments = [])
 * @method \Http\Promise\Promise describeComplianceSummaryAsync($arguments = [])
 * @method \Dew\Acs\Result describeConfigRule(array $arguments = [])
 * @method \Http\Promise\Promise describeConfigRuleAsync($arguments = [])
 * @method \Dew\Acs\Result putConfigRule(array $arguments = []) {@deprecated 2019-01-08}
 * @method \Http\Promise\Promise putConfigRuleAsync($arguments = []) {@deprecated 2019-01-08}
 * @method \Dew\Acs\Result putEvaluations(array $arguments = []) {@deprecated 2019-01-08}
 * @method \Http\Promise\Promise putEvaluationsAsync($arguments = []) {@deprecated 2019-01-08}
 * @method \Dew\Acs\Result activeConfigRules(array $arguments = []) {@deprecated 2019-01-08}
 * @method \Http\Promise\Promise activeConfigRulesAsync($arguments = []) {@deprecated 2019-01-08}
 * @method \Dew\Acs\Result startConfigurationRecorder(array $arguments = [])
 * @method \Http\Promise\Promise startConfigurationRecorderAsync($arguments = [])
 * @method \Dew\Acs\Result describeConfigurationRecorder(array $arguments = [])
 * @method \Http\Promise\Promise describeConfigurationRecorderAsync($arguments = [])
 * @method \Dew\Acs\Result putConfigurationRecorder(array $arguments = []) {@deprecated 2019-01-08}
 * @method \Http\Promise\Promise putConfigurationRecorderAsync($arguments = []) {@deprecated 2019-01-08}
 * @method \Dew\Acs\Result describeDeliveryChannels(array $arguments = []) {@deprecated 2019-01-08}
 * @method \Http\Promise\Promise describeDeliveryChannelsAsync($arguments = []) {@deprecated 2019-01-08}
 * @method \Dew\Acs\Result putDeliveryChannel(array $arguments = []) {@deprecated 2019-01-08}
 * @method \Http\Promise\Promise putDeliveryChannelAsync($arguments = []) {@deprecated 2019-01-08}
 * @method \Dew\Acs\Result getAggregateDiscoveredResource(array $arguments = []) {@deprecated 2019-01-08}
 * @method \Http\Promise\Promise getAggregateDiscoveredResourceAsync($arguments = []) {@deprecated 2019-01-08}
 * @method \Dew\Acs\Result listAggregateDiscoveredResources(array $arguments = []) {@deprecated 2019-01-08}
 * @method \Http\Promise\Promise listAggregateDiscoveredResourcesAsync($arguments = []) {@deprecated 2019-01-08}
 * @method \Dew\Acs\Result listRemediationTemplates(array $arguments = []) {@deprecated 2019-01-08}
 * @method \Http\Promise\Promise listRemediationTemplatesAsync($arguments = []) {@deprecated 2019-01-08}
 * @method \Dew\Acs\Result createAggregator(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise createAggregatorAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result updateAggregator(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise updateAggregatorAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result deleteAggregators(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise deleteAggregatorsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listAggregators(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listAggregatorsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregator(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregatorAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getDiscoveredResource(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getDiscoveredResourceAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listResourceRelations(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listResourceRelationsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listResourcesByAdvancedSearch(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listResourcesByAdvancedSearchAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result createAdvancedSearchFile(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise createAdvancedSearchFileAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAdvancedSearchFile(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAdvancedSearchFileAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result generateResourceInventory(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise generateResourceInventoryAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getResourceInventory(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getResourceInventoryAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getDiscoveredResourceCountsGroupByRegion(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getDiscoveredResourceCountsGroupByRegionAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getDiscoveredResourceCountsGroupByResourceType(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getDiscoveredResourceCountsGroupByResourceTypeAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getResourceComplianceGroupByResourceType(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getResourceComplianceGroupByResourceTypeAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getResourceComplianceGroupByRegion(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getResourceComplianceGroupByRegionAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listAggregateResourceRelations(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listAggregateResourceRelationsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateResourceConfigurationTimeline(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateResourceConfigurationTimelineAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateResourceComplianceTimeline(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateResourceComplianceTimelineAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listAggregateResourcesByAdvancedSearch(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listAggregateResourcesByAdvancedSearchAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result createAggregateAdvancedSearchFile(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise createAggregateAdvancedSearchFileAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateAdvancedSearchFile(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateAdvancedSearchFileAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result generateAggregateResourceInventory(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise generateAggregateResourceInventoryAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateResourceInventory(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateResourceInventoryAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateResourceCountsGroupByRegion(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateResourceCountsGroupByRegionAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateResourceCountsGroupByResourceType(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateResourceCountsGroupByResourceTypeAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateResourceComplianceGroupByRegion(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateResourceComplianceGroupByRegionAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateResourceComplianceGroupByResourceType(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateResourceComplianceGroupByResourceTypeAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getSupportedResourceRelationConfig(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getSupportedResourceRelationConfigAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listSupportedProducts(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listSupportedProductsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result createConfigRule(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise createConfigRuleAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result updateConfigRule(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise updateConfigRuleAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getConfigRule(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getConfigRuleAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listConfigRuleEvaluationResults(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listConfigRuleEvaluationResultsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listResourceEvaluationResults(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listResourceEvaluationResultsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result deactiveConfigRules(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise deactiveConfigRulesAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result ignoreEvaluationResults(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise ignoreEvaluationResultsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result revertEvaluationResults(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise revertEvaluationResultsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result generateConfigRulesReport(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise generateConfigRulesReportAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getConfigRulesReport(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getConfigRulesReportAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getConfigRuleSummaryByRiskLevel(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getConfigRuleSummaryByRiskLevelAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getResourceComplianceByConfigRule(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getResourceComplianceByConfigRuleAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getComplianceSummary(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getComplianceSummaryAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listConfigRuleEvaluationStatistics(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listConfigRuleEvaluationStatisticsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result createAggregateConfigRule(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise createAggregateConfigRuleAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result updateAggregateConfigRule(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise updateAggregateConfigRuleAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listAggregateConfigRules(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listAggregateConfigRulesAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateConfigRule(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateConfigRuleAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listAggregateConfigRuleEvaluationResults(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listAggregateConfigRuleEvaluationResultsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listAggregateResourceEvaluationResults(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listAggregateResourceEvaluationResultsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result deleteAggregateConfigRules(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise deleteAggregateConfigRulesAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result deactiveAggregateConfigRules(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise deactiveAggregateConfigRulesAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result activeAggregateConfigRules(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise activeAggregateConfigRulesAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result startAggregateConfigRuleEvaluation(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise startAggregateConfigRuleEvaluationAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result ignoreAggregateEvaluationResults(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise ignoreAggregateEvaluationResultsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result revertAggregateEvaluationResults(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise revertAggregateEvaluationResultsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result generateAggregateConfigRulesReport(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise generateAggregateConfigRulesReportAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateConfigRulesReport(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateConfigRulesReportAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateConfigRuleSummaryByRiskLevel(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateConfigRuleSummaryByRiskLevelAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateResourceComplianceByConfigRule(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateResourceComplianceByConfigRuleAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateComplianceSummary(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateComplianceSummaryAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listAggregateConfigRuleEvaluationStatistics(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listAggregateConfigRuleEvaluationStatisticsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result copyConfigRules(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise copyConfigRulesAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listManagedRules(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listManagedRulesAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getManagedRule(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getManagedRuleAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listPreManagedRules(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listPreManagedRulesAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result evaluatePreConfigRules(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise evaluatePreConfigRulesAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result createCompliancePack(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise createCompliancePackAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result updateCompliancePack(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise updateCompliancePackAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listCompliancePacks(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listCompliancePacksAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getCompliancePack(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getCompliancePackAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result deleteCompliancePacks(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise deleteCompliancePacksAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result generateCompliancePackReport(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise generateCompliancePackReportAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getCompliancePackReport(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getCompliancePackReportAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getConfigRuleComplianceByPack(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getConfigRuleComplianceByPackAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getResourceComplianceByPack(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getResourceComplianceByPackAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result attachConfigRuleToCompliancePack(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise attachConfigRuleToCompliancePackAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result detachConfigRuleToCompliancePack(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise detachConfigRuleToCompliancePackAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result createAggregateCompliancePack(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise createAggregateCompliancePackAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result updateAggregateCompliancePack(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise updateAggregateCompliancePackAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listAggregateCompliancePacks(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listAggregateCompliancePacksAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateCompliancePack(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateCompliancePackAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result deleteAggregateCompliancePacks(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise deleteAggregateCompliancePacksAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result generateAggregateCompliancePackReport(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise generateAggregateCompliancePackReportAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateCompliancePackReport(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateCompliancePackReportAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateResourceComplianceByPack(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateResourceComplianceByPackAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateConfigRuleComplianceByPack(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateConfigRuleComplianceByPackAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateAccountComplianceByPack(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateAccountComplianceByPackAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result attachAggregateConfigRuleToCompliancePack(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise attachAggregateConfigRuleToCompliancePackAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result detachAggregateConfigRuleToCompliancePack(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise detachAggregateConfigRuleToCompliancePackAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result copyCompliancePacks(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise copyCompliancePacksAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listCompliancePackTemplates(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listCompliancePackTemplatesAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result createRemediation(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise createRemediationAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result updateRemediation(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise updateRemediationAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listRemediations(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listRemediationsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result deleteRemediations(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise deleteRemediationsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result startRemediation(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise startRemediationAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listRemediationExecutions(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listRemediationExecutionsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result describeRemediation(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise describeRemediationAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result createAggregateRemediation(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise createAggregateRemediationAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result updateAggregateRemediation(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise updateAggregateRemediationAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listAggregateRemediations(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listAggregateRemediationsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result deleteAggregateRemediations(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise deleteAggregateRemediationsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result startAggregateRemediation(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise startAggregateRemediationAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listAggregateRemediationExecutions(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listAggregateRemediationExecutionsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getRemediationTemplate(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getRemediationTemplateAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result createConfigDeliveryChannel(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise createConfigDeliveryChannelAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result updateConfigDeliveryChannel(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise updateConfigDeliveryChannelAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result deleteConfigDeliveryChannel(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise deleteConfigDeliveryChannelAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listConfigDeliveryChannels(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listConfigDeliveryChannelsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getConfigDeliveryChannel(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getConfigDeliveryChannelAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result createDeliveryChannel(array $arguments = []) {@deprecated 2020-09-07} {@since 2020-09-07}
 * @method \Http\Promise\Promise createDeliveryChannelAsync($arguments = []) {@deprecated 2020-09-07} {@since 2020-09-07}
 * @method \Dew\Acs\Result updateDeliveryChannel(array $arguments = []) {@deprecated 2020-09-07} {@since 2020-09-07}
 * @method \Http\Promise\Promise updateDeliveryChannelAsync($arguments = []) {@deprecated 2020-09-07} {@since 2020-09-07}
 * @method \Dew\Acs\Result createAggregateConfigDeliveryChannel(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise createAggregateConfigDeliveryChannelAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result updateAggregateConfigDeliveryChannel(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise updateAggregateConfigDeliveryChannelAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result deleteAggregateConfigDeliveryChannel(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise deleteAggregateConfigDeliveryChannelAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listAggregateConfigDeliveryChannels(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listAggregateConfigDeliveryChannelsAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getAggregateConfigDeliveryChannel(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getAggregateConfigDeliveryChannelAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listTagResources(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listTagResourcesAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result tagResources(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise tagResourcesAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result untagResources(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise untagResourcesAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getIntegratedServiceStatus(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getIntegratedServiceStatusAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result updateIntegratedServiceStatus(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise updateIntegratedServiceStatusAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result listIntegratedService(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise listIntegratedServiceAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result getConfigurationRecorder(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise getConfigurationRecorderAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result updateConfigurationRecorder(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise updateConfigurationRecorderAsync($arguments = []) {@since 2020-09-07}
 * @method \Dew\Acs\Result stopConfigurationRecorder(array $arguments = []) {@since 2020-09-07}
 * @method \Http\Promise\Promise stopConfigurationRecorderAsync($arguments = []) {@since 2020-09-07}
 */
final class ConfigClient extends AcsClient
{
    //
}
