<?php

declare(strict_types=1);

namespace Dew\Acs\QuanMiaoLightApp;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result runMarketingInformationWriting(array $arguments = [])
 * @method \Http\Promise\Promise runMarketingInformationWritingAsync($arguments = [])
 * @method \Dew\Acs\Result runMarketingInformationExtract(array $arguments = [])
 * @method \Http\Promise\Promise runMarketingInformationExtractAsync($arguments = [])
 * @method \Dew\Acs\Result runStyleWriting(array $arguments = [])
 * @method \Http\Promise\Promise runStyleWritingAsync($arguments = [])
 * @method \Dew\Acs\Result runScriptRefine(array $arguments = [])
 * @method \Http\Promise\Promise runScriptRefineAsync($arguments = [])
 * @method \Dew\Acs\Result runScriptChat(array $arguments = [])
 * @method \Http\Promise\Promise runScriptChatAsync($arguments = [])
 * @method \Dew\Acs\Result runScriptPlanning(array $arguments = [])
 * @method \Http\Promise\Promise runScriptPlanningAsync($arguments = [])
 * @method \Dew\Acs\Result runScriptContinue(array $arguments = [])
 * @method \Http\Promise\Promise runScriptContinueAsync($arguments = [])
 * @method \Dew\Acs\Result submitVideoAnalysisTask(array $arguments = [])
 * @method \Http\Promise\Promise submitVideoAnalysisTaskAsync($arguments = [])
 * @method \Dew\Acs\Result getVideoAnalysisTask(array $arguments = [])
 * @method \Http\Promise\Promise getVideoAnalysisTaskAsync($arguments = [])
 * @method \Dew\Acs\Result updateVideoAnalysisTask(array $arguments = [])
 * @method \Http\Promise\Promise updateVideoAnalysisTaskAsync($arguments = [])
 * @method \Dew\Acs\Result updateVideoAnalysisConfig(array $arguments = [])
 * @method \Http\Promise\Promise updateVideoAnalysisConfigAsync($arguments = [])
 * @method \Dew\Acs\Result getVideoAnalysisConfig(array $arguments = [])
 * @method \Http\Promise\Promise getVideoAnalysisConfigAsync($arguments = [])
 * @method \Dew\Acs\Result runVideoAnalysis(array $arguments = [])
 * @method \Http\Promise\Promise runVideoAnalysisAsync($arguments = [])
 * @method \Dew\Acs\Result runHotTopicChat(array $arguments = [])
 * @method \Http\Promise\Promise runHotTopicChatAsync($arguments = [])
 * @method \Dew\Acs\Result runHotTopicSummary(array $arguments = [])
 * @method \Http\Promise\Promise runHotTopicSummaryAsync($arguments = [])
 * @method \Dew\Acs\Result runEnterpriseVocAnalysis(array $arguments = [])
 * @method \Http\Promise\Promise runEnterpriseVocAnalysisAsync($arguments = [])
 * @method \Dew\Acs\Result submitEnterpriseVocAnalysisTask(array $arguments = [])
 * @method \Http\Promise\Promise submitEnterpriseVocAnalysisTaskAsync($arguments = [])
 * @method \Dew\Acs\Result getEnterpriseVocAnalysisTask(array $arguments = [])
 * @method \Http\Promise\Promise getEnterpriseVocAnalysisTaskAsync($arguments = [])
 * @method \Dew\Acs\Result exportAnalysisTagDetailByTaskId(array $arguments = [])
 * @method \Http\Promise\Promise exportAnalysisTagDetailByTaskIdAsync($arguments = [])
 * @method \Dew\Acs\Result listAnalysisTagDetailByTaskId(array $arguments = [])
 * @method \Http\Promise\Promise listAnalysisTagDetailByTaskIdAsync($arguments = [])
 * @method \Dew\Acs\Result generateOutputFormat(array $arguments = [])
 * @method \Http\Promise\Promise generateOutputFormatAsync($arguments = [])
 * @method \Dew\Acs\Result runTagMiningAnalysis(array $arguments = [])
 * @method \Http\Promise\Promise runTagMiningAnalysisAsync($arguments = [])
 * @method \Dew\Acs\Result runNetworkContentAudit(array $arguments = [])
 * @method \Http\Promise\Promise runNetworkContentAuditAsync($arguments = [])
 * @method \Dew\Acs\Result runEssayCorrection(array $arguments = [])
 * @method \Http\Promise\Promise runEssayCorrectionAsync($arguments = [])
 * @method \Dew\Acs\Result runOcrParse(array $arguments = [])
 * @method \Http\Promise\Promise runOcrParseAsync($arguments = [])
 * @method \Dew\Acs\Result submitEssayCorrectionTask(array $arguments = [])
 * @method \Http\Promise\Promise submitEssayCorrectionTaskAsync($arguments = [])
 * @method \Dew\Acs\Result getEssayCorrectionTask(array $arguments = [])
 * @method \Http\Promise\Promise getEssayCorrectionTaskAsync($arguments = [])
 * @method \Dew\Acs\Result generateBroadcastNews(array $arguments = [])
 * @method \Http\Promise\Promise generateBroadcastNewsAsync($arguments = [])
 * @method \Dew\Acs\Result submitTagMiningAnalysisTask(array $arguments = [])
 * @method \Http\Promise\Promise submitTagMiningAnalysisTaskAsync($arguments = [])
 * @method \Dew\Acs\Result listHotTopicSummaries(array $arguments = [])
 * @method \Http\Promise\Promise listHotTopicSummariesAsync($arguments = [])
 * @method \Dew\Acs\Result getTagMiningAnalysisTask(array $arguments = [])
 * @method \Http\Promise\Promise getTagMiningAnalysisTaskAsync($arguments = [])
 * @method \Dew\Acs\Result cancelAsyncTask(array $arguments = [])
 * @method \Http\Promise\Promise cancelAsyncTaskAsync($arguments = [])
 * @method \Dew\Acs\Result hotNewsRecommend(array $arguments = [])
 * @method \Http\Promise\Promise hotNewsRecommendAsync($arguments = [])
 * @method \Dew\Acs\Result getFileContent(array $arguments = [])
 * @method \Http\Promise\Promise getFileContentAsync($arguments = [])
 * @method \Dew\Acs\Result updateVideoAnalysisTasks(array $arguments = [])
 * @method \Http\Promise\Promise updateVideoAnalysisTasksAsync($arguments = [])
 */
final class QuanMiaoLightAppClient extends AcsClient
{
    //
}
