<?php

declare(strict_types=1);

namespace Dew\Acs\AiMiaoBi;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result createToken(array $arguments = [])
 * @method \Http\Promise\Promise createTokenAsync($arguments = [])
 * @method \Dew\Acs\Result listDialogues(array $arguments = [])
 * @method \Http\Promise\Promise listDialoguesAsync($arguments = [])
 * @method \Dew\Acs\Result listVersions(array $arguments = [])
 * @method \Http\Promise\Promise listVersionsAsync($arguments = [])
 * @method \Dew\Acs\Result getProperties(array $arguments = [])
 * @method \Http\Promise\Promise getPropertiesAsync($arguments = [])
 * @method \Dew\Acs\Result generateFileUrlByKey(array $arguments = [])
 * @method \Http\Promise\Promise generateFileUrlByKeyAsync($arguments = [])
 * @method \Dew\Acs\Result generateUploadConfig(array $arguments = [])
 * @method \Http\Promise\Promise generateUploadConfigAsync($arguments = [])
 * @method \Dew\Acs\Result submitAsyncTask(array $arguments = [])
 * @method \Http\Promise\Promise submitAsyncTaskAsync($arguments = [])
 * @method \Dew\Acs\Result cancelAsyncTask(array $arguments = [])
 * @method \Http\Promise\Promise cancelAsyncTaskAsync($arguments = [])
 * @method \Dew\Acs\Result queryAsyncTask(array $arguments = [])
 * @method \Http\Promise\Promise queryAsyncTaskAsync($arguments = [])
 * @method \Dew\Acs\Result listAsyncTasks(array $arguments = [])
 * @method \Http\Promise\Promise listAsyncTasksAsync($arguments = [])
 * @method \Dew\Acs\Result searchNews(array $arguments = [])
 * @method \Http\Promise\Promise searchNewsAsync($arguments = [])
 * @method \Dew\Acs\Result listBuildConfigs(array $arguments = [])
 * @method \Http\Promise\Promise listBuildConfigsAsync($arguments = [])
 * @method \Dew\Acs\Result generateImageTask(array $arguments = [])
 * @method \Http\Promise\Promise generateImageTaskAsync($arguments = [])
 * @method \Dew\Acs\Result fetchImageTask(array $arguments = [])
 * @method \Http\Promise\Promise fetchImageTaskAsync($arguments = [])
 * @method \Dew\Acs\Result feedbackDialogue(array $arguments = [])
 * @method \Http\Promise\Promise feedbackDialogueAsync($arguments = [])
 * @method \Dew\Acs\Result getCustomText(array $arguments = [])
 * @method \Http\Promise\Promise getCustomTextAsync($arguments = [])
 * @method \Dew\Acs\Result updateCustomText(array $arguments = [])
 * @method \Http\Promise\Promise updateCustomTextAsync($arguments = [])
 * @method \Dew\Acs\Result listCustomText(array $arguments = [])
 * @method \Http\Promise\Promise listCustomTextAsync($arguments = [])
 * @method \Dew\Acs\Result saveCustomText(array $arguments = [])
 * @method \Http\Promise\Promise saveCustomTextAsync($arguments = [])
 * @method \Dew\Acs\Result deleteCustomText(array $arguments = [])
 * @method \Http\Promise\Promise deleteCustomTextAsync($arguments = [])
 * @method \Dew\Acs\Result documentExtraction(array $arguments = [])
 * @method \Http\Promise\Promise documentExtractionAsync($arguments = [])
 * @method \Dew\Acs\Result createGeneratedContent(array $arguments = [])
 * @method \Http\Promise\Promise createGeneratedContentAsync($arguments = [])
 * @method \Dew\Acs\Result deleteGeneratedContent(array $arguments = [])
 * @method \Http\Promise\Promise deleteGeneratedContentAsync($arguments = [])
 * @method \Dew\Acs\Result updateGeneratedContent(array $arguments = [])
 * @method \Http\Promise\Promise updateGeneratedContentAsync($arguments = [])
 * @method \Dew\Acs\Result getGeneratedContent(array $arguments = [])
 * @method \Http\Promise\Promise getGeneratedContentAsync($arguments = [])
 * @method \Dew\Acs\Result listGeneratedContents(array $arguments = [])
 * @method \Http\Promise\Promise listGeneratedContentsAsync($arguments = [])
 * @method \Dew\Acs\Result exportGeneratedContent(array $arguments = [])
 * @method \Http\Promise\Promise exportGeneratedContentAsync($arguments = [])
 * @method \Dew\Acs\Result saveMaterialDocument(array $arguments = [])
 * @method \Http\Promise\Promise saveMaterialDocumentAsync($arguments = [])
 * @method \Dew\Acs\Result deleteMaterialById(array $arguments = [])
 * @method \Http\Promise\Promise deleteMaterialByIdAsync($arguments = [])
 * @method \Dew\Acs\Result updateMaterialDocument(array $arguments = [])
 * @method \Http\Promise\Promise updateMaterialDocumentAsync($arguments = [])
 * @method \Dew\Acs\Result getMaterialById(array $arguments = [])
 * @method \Http\Promise\Promise getMaterialByIdAsync($arguments = [])
 * @method \Dew\Acs\Result listMaterialDocuments(array $arguments = [])
 * @method \Http\Promise\Promise listMaterialDocumentsAsync($arguments = [])
 * @method \Dew\Acs\Result listInterveneCnt(array $arguments = [])
 * @method \Http\Promise\Promise listInterveneCntAsync($arguments = [])
 * @method \Dew\Acs\Result listIntervenes(array $arguments = [])
 * @method \Http\Promise\Promise listIntervenesAsync($arguments = [])
 * @method \Dew\Acs\Result importInterveneFile(array $arguments = [])
 * @method \Http\Promise\Promise importInterveneFileAsync($arguments = [])
 * @method \Dew\Acs\Result insertInterveneGlobalReply(array $arguments = [])
 * @method \Http\Promise\Promise insertInterveneGlobalReplyAsync($arguments = [])
 * @method \Dew\Acs\Result importInterveneFileAsync(array $arguments = [])
 * @method \Http\Promise\Promise importInterveneFileAsyncAsync($arguments = [])
 * @method \Dew\Acs\Result getInterveneTemplateFileUrl(array $arguments = [])
 * @method \Http\Promise\Promise getInterveneTemplateFileUrlAsync($arguments = [])
 * @method \Dew\Acs\Result clearIntervenes(array $arguments = [])
 * @method \Http\Promise\Promise clearIntervenesAsync($arguments = [])
 * @method \Dew\Acs\Result getInterveneGlobalReply(array $arguments = [])
 * @method \Http\Promise\Promise getInterveneGlobalReplyAsync($arguments = [])
 * @method \Dew\Acs\Result listInterveneRules(array $arguments = [])
 * @method \Http\Promise\Promise listInterveneRulesAsync($arguments = [])
 * @method \Dew\Acs\Result listInterveneImportTasks(array $arguments = [])
 * @method \Http\Promise\Promise listInterveneImportTasksAsync($arguments = [])
 * @method \Dew\Acs\Result insertInterveneRule(array $arguments = [])
 * @method \Http\Promise\Promise insertInterveneRuleAsync($arguments = [])
 * @method \Dew\Acs\Result getInterveneRuleDetail(array $arguments = [])
 * @method \Http\Promise\Promise getInterveneRuleDetailAsync($arguments = [])
 * @method \Dew\Acs\Result deleteInterveneRule(array $arguments = [])
 * @method \Http\Promise\Promise deleteInterveneRuleAsync($arguments = [])
 * @method \Dew\Acs\Result exportIntervenes(array $arguments = [])
 * @method \Http\Promise\Promise exportIntervenesAsync($arguments = [])
 * @method \Dew\Acs\Result getInterveneImportTaskInfo(array $arguments = [])
 * @method \Http\Promise\Promise getInterveneImportTaskInfoAsync($arguments = [])
 * @method \Dew\Acs\Result saveDataSourceOrderConfig(array $arguments = [])
 * @method \Http\Promise\Promise saveDataSourceOrderConfigAsync($arguments = [])
 * @method \Dew\Acs\Result getDataSourceOrderConfig(array $arguments = [])
 * @method \Http\Promise\Promise getDataSourceOrderConfigAsync($arguments = [])
 * @method \Dew\Acs\Result listHotNewsWithType(array $arguments = [])
 * @method \Http\Promise\Promise listHotNewsWithTypeAsync($arguments = [])
 * @method \Dew\Acs\Result generateViewPoint(array $arguments = [])
 * @method \Http\Promise\Promise generateViewPointAsync($arguments = [])
 */
final class AiMiaoBiClient extends AcsClient
{
    //
}
