<?php

declare(strict_types=1);

namespace Dew\Acs\Nlb;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result describeHdMonitorRegionConfig(array $arguments = [])
 * @method \Http\Promise\Promise describeHdMonitorRegionConfigAsync($arguments = [])
 * @method \Dew\Acs\Result setHdMonitorRegionConfig(array $arguments = [])
 * @method \Http\Promise\Promise setHdMonitorRegionConfigAsync($arguments = [])
 * @method \Dew\Acs\Result describeRegions(array $arguments = [])
 * @method \Http\Promise\Promise describeRegionsAsync($arguments = [])
 * @method \Dew\Acs\Result describeZones(array $arguments = [])
 * @method \Http\Promise\Promise describeZonesAsync($arguments = [])
 * @method \Dew\Acs\Result createLoadBalancer(array $arguments = [])
 * @method \Http\Promise\Promise createLoadBalancerAsync($arguments = [])
 * @method \Dew\Acs\Result deleteLoadBalancer(array $arguments = [])
 * @method \Http\Promise\Promise deleteLoadBalancerAsync($arguments = [])
 * @method \Dew\Acs\Result updateLoadBalancerAddressTypeConfig(array $arguments = [])
 * @method \Http\Promise\Promise updateLoadBalancerAddressTypeConfigAsync($arguments = [])
 * @method \Dew\Acs\Result updateLoadBalancerAttribute(array $arguments = [])
 * @method \Http\Promise\Promise updateLoadBalancerAttributeAsync($arguments = [])
 * @method \Dew\Acs\Result updateLoadBalancerZones(array $arguments = [])
 * @method \Http\Promise\Promise updateLoadBalancerZonesAsync($arguments = [])
 * @method \Dew\Acs\Result enableLoadBalancerIpv6Internet(array $arguments = [])
 * @method \Http\Promise\Promise enableLoadBalancerIpv6InternetAsync($arguments = [])
 * @method \Dew\Acs\Result disableLoadBalancerIpv6Internet(array $arguments = [])
 * @method \Http\Promise\Promise disableLoadBalancerIpv6InternetAsync($arguments = [])
 * @method \Dew\Acs\Result loadBalancerLeaveSecurityGroup(array $arguments = [])
 * @method \Http\Promise\Promise loadBalancerLeaveSecurityGroupAsync($arguments = [])
 * @method \Dew\Acs\Result loadBalancerJoinSecurityGroup(array $arguments = [])
 * @method \Http\Promise\Promise loadBalancerJoinSecurityGroupAsync($arguments = [])
 * @method \Dew\Acs\Result updateLoadBalancerProtection(array $arguments = [])
 * @method \Http\Promise\Promise updateLoadBalancerProtectionAsync($arguments = [])
 * @method \Dew\Acs\Result listLoadBalancers(array $arguments = [])
 * @method \Http\Promise\Promise listLoadBalancersAsync($arguments = [])
 * @method \Dew\Acs\Result getLoadBalancerAttribute(array $arguments = [])
 * @method \Http\Promise\Promise getLoadBalancerAttributeAsync($arguments = [])
 * @method \Dew\Acs\Result startShiftLoadBalancerZones(array $arguments = [])
 * @method \Http\Promise\Promise startShiftLoadBalancerZonesAsync($arguments = [])
 * @method \Dew\Acs\Result cancelShiftLoadBalancerZones(array $arguments = [])
 * @method \Http\Promise\Promise cancelShiftLoadBalancerZonesAsync($arguments = [])
 * @method \Dew\Acs\Result createListener(array $arguments = [])
 * @method \Http\Promise\Promise createListenerAsync($arguments = [])
 * @method \Dew\Acs\Result deleteListener(array $arguments = [])
 * @method \Http\Promise\Promise deleteListenerAsync($arguments = [])
 * @method \Dew\Acs\Result startListener(array $arguments = [])
 * @method \Http\Promise\Promise startListenerAsync($arguments = [])
 * @method \Dew\Acs\Result stopListener(array $arguments = [])
 * @method \Http\Promise\Promise stopListenerAsync($arguments = [])
 * @method \Dew\Acs\Result updateListenerAttribute(array $arguments = [])
 * @method \Http\Promise\Promise updateListenerAttributeAsync($arguments = [])
 * @method \Dew\Acs\Result listListeners(array $arguments = [])
 * @method \Http\Promise\Promise listListenersAsync($arguments = [])
 * @method \Dew\Acs\Result getListenerAttribute(array $arguments = [])
 * @method \Http\Promise\Promise getListenerAttributeAsync($arguments = [])
 * @method \Dew\Acs\Result getListenerHealthStatus(array $arguments = [])
 * @method \Http\Promise\Promise getListenerHealthStatusAsync($arguments = [])
 * @method \Dew\Acs\Result listListenerCertificates(array $arguments = [])
 * @method \Http\Promise\Promise listListenerCertificatesAsync($arguments = [])
 * @method \Dew\Acs\Result associateAdditionalCertificatesWithListener(array $arguments = [])
 * @method \Http\Promise\Promise associateAdditionalCertificatesWithListenerAsync($arguments = [])
 * @method \Dew\Acs\Result disassociateAdditionalCertificatesWithListener(array $arguments = [])
 * @method \Http\Promise\Promise disassociateAdditionalCertificatesWithListenerAsync($arguments = [])
 * @method \Dew\Acs\Result createServerGroup(array $arguments = [])
 * @method \Http\Promise\Promise createServerGroupAsync($arguments = [])
 * @method \Dew\Acs\Result addServersToServerGroup(array $arguments = [])
 * @method \Http\Promise\Promise addServersToServerGroupAsync($arguments = [])
 * @method \Dew\Acs\Result deleteServerGroup(array $arguments = [])
 * @method \Http\Promise\Promise deleteServerGroupAsync($arguments = [])
 * @method \Dew\Acs\Result removeServersFromServerGroup(array $arguments = [])
 * @method \Http\Promise\Promise removeServersFromServerGroupAsync($arguments = [])
 * @method \Dew\Acs\Result updateServerGroupAttribute(array $arguments = [])
 * @method \Http\Promise\Promise updateServerGroupAttributeAsync($arguments = [])
 * @method \Dew\Acs\Result updateServerGroupServersAttribute(array $arguments = [])
 * @method \Http\Promise\Promise updateServerGroupServersAttributeAsync($arguments = [])
 * @method \Dew\Acs\Result listServerGroups(array $arguments = [])
 * @method \Http\Promise\Promise listServerGroupsAsync($arguments = [])
 * @method \Dew\Acs\Result listServerGroupServers(array $arguments = [])
 * @method \Http\Promise\Promise listServerGroupServersAsync($arguments = [])
 * @method \Dew\Acs\Result detachCommonBandwidthPackageFromLoadBalancer(array $arguments = [])
 * @method \Http\Promise\Promise detachCommonBandwidthPackageFromLoadBalancerAsync($arguments = [])
 * @method \Dew\Acs\Result attachCommonBandwidthPackageToLoadBalancer(array $arguments = [])
 * @method \Http\Promise\Promise attachCommonBandwidthPackageToLoadBalancerAsync($arguments = [])
 * @method \Dew\Acs\Result createSecurityPolicy(array $arguments = [])
 * @method \Http\Promise\Promise createSecurityPolicyAsync($arguments = [])
 * @method \Dew\Acs\Result deleteSecurityPolicy(array $arguments = [])
 * @method \Http\Promise\Promise deleteSecurityPolicyAsync($arguments = [])
 * @method \Dew\Acs\Result updateSecurityPolicyAttribute(array $arguments = [])
 * @method \Http\Promise\Promise updateSecurityPolicyAttributeAsync($arguments = [])
 * @method \Dew\Acs\Result listSecurityPolicy(array $arguments = [])
 * @method \Http\Promise\Promise listSecurityPolicyAsync($arguments = [])
 * @method \Dew\Acs\Result listSystemSecurityPolicy(array $arguments = [])
 * @method \Http\Promise\Promise listSystemSecurityPolicyAsync($arguments = [])
 * @method \Dew\Acs\Result moveResourceGroup(array $arguments = [])
 * @method \Http\Promise\Promise moveResourceGroupAsync($arguments = [])
 * @method \Dew\Acs\Result listAsynJobs(array $arguments = [])
 * @method \Http\Promise\Promise listAsynJobsAsync($arguments = [])
 * @method \Dew\Acs\Result getJobStatus(array $arguments = [])
 * @method \Http\Promise\Promise getJobStatusAsync($arguments = [])
 * @method \Dew\Acs\Result tagResources(array $arguments = [])
 * @method \Http\Promise\Promise tagResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result untagResources(array $arguments = [])
 * @method \Http\Promise\Promise untagResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result listTagResources(array $arguments = [])
 * @method \Http\Promise\Promise listTagResourcesAsync($arguments = [])
 */
final class NlbClient extends AcsClient
{
    //
}
