<?php

declare(strict_types=1);

namespace Dew\Acs\PaiStudio;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result createExperiment(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise createExperimentAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result copyExperiment(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise copyExperimentAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result updateExperimentMeta(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise updateExperimentMetaAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result updateExperimentContent(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise updateExperimentContentAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result publishExperiment(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise publishExperimentAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result getExperiment(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise getExperimentAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result getExperimentMeta(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise getExperimentMetaAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result getExperimentStatus(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise getExperimentStatusAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result deleteExperiment(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise deleteExperimentAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result listExperiments(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise listExperimentsAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result createJob(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise createJobAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result getJob(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise getJobAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result listJobs(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise listJobsAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result stopJob(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise stopJobAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result stopExperiment(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise stopExperimentAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result createExperimentFolder(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise createExperimentFolderAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result updateExperimentFolder(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise updateExperimentFolderAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result getExperimentFolderChildren(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise getExperimentFolderChildrenAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result deleteExperimentFolder(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise deleteExperimentFolderAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result getAlgorithmTree(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise getAlgorithmTreeAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result getAlgorithmDef(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise getAlgorithmDefAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result listRecentExperiments(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise listRecentExperimentsAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result listTemplates(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise listTemplatesAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result getTemplate(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise getTemplateAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result getExperimentsStatistics(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise getExperimentsStatisticsAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result getExperimentsUsersStatistics(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise getExperimentsUsersStatisticsAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result previewMCTable(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise previewMCTableAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result getMCTableSchema(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise getMCTableSchemaAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result searchMCTables(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise searchMCTablesAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result getNodeInputSchema(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise getNodeInputSchemaAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result getExperimentVisualizationMeta(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise getExperimentVisualizationMetaAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result queryExperimentVisualizationData(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise queryExperimentVisualizationDataAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result getAlgoTree(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise getAlgoTreeAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result listNodeOutputs(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise listNodeOutputsAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result getNodeOutput(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise getNodeOutputAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result listAuthRoles(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise listAuthRolesAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result listImages(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise listImagesAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result listImageLabels(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise listImageLabelsAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result migrateExperiments(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise migrateExperimentsAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result createExperimentMigrateValidation(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise createExperimentMigrateValidationAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result migrateExperimentFolders(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise migrateExperimentFoldersAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result getAlgorithmDefs(array $arguments = []) {@since 2021-02-02}
 * @method \Http\Promise\Promise getAlgorithmDefsAsync($arguments = []) {@since 2021-02-02}
 * @method \Dew\Acs\Result updateResourceGroup(array $arguments = [])
 * @method \Http\Promise\Promise updateResourceGroupAsync($arguments = [])
 * @method \Dew\Acs\Result getResourceGroupTotal(array $arguments = [])
 * @method \Http\Promise\Promise getResourceGroupTotalAsync($arguments = [])
 * @method \Dew\Acs\Result listResourceGroups(array $arguments = [])
 * @method \Http\Promise\Promise listResourceGroupsAsync($arguments = [])
 * @method \Dew\Acs\Result getResourceGroupRequest(array $arguments = []) {@deprecated 2022-01-12}
 * @method \Http\Promise\Promise getResourceGroupRequestAsync($arguments = []) {@deprecated 2022-01-12}
 * @method \Dew\Acs\Result deleteResourceGroupMachineGroup(array $arguments = []) {@deprecated 2022-01-12}
 * @method \Http\Promise\Promise deleteResourceGroupMachineGroupAsync($arguments = []) {@deprecated 2022-01-12}
 * @method \Dew\Acs\Result getNodeMetrics(array $arguments = []) {@deprecated 2022-01-12}
 * @method \Http\Promise\Promise getNodeMetricsAsync($arguments = []) {@deprecated 2022-01-12}
 * @method \Dew\Acs\Result listResourceGroupMachineGroups(array $arguments = [])
 * @method \Http\Promise\Promise listResourceGroupMachineGroupsAsync($arguments = [])
 * @method \Dew\Acs\Result getUserViewMetrics(array $arguments = []) {@deprecated 2022-01-12}
 * @method \Http\Promise\Promise getUserViewMetricsAsync($arguments = []) {@deprecated 2022-01-12}
 * @method \Dew\Acs\Result getResourceGroupMachineGroup(array $arguments = [])
 * @method \Http\Promise\Promise getResourceGroupMachineGroupAsync($arguments = [])
 * @method \Dew\Acs\Result getResourceGroup(array $arguments = [])
 * @method \Http\Promise\Promise getResourceGroupAsync($arguments = [])
 * @method \Dew\Acs\Result deleteMachineGroup(array $arguments = []) {@deprecated 2022-01-12}
 * @method \Http\Promise\Promise deleteMachineGroupAsync($arguments = []) {@deprecated 2022-01-12}
 * @method \Dew\Acs\Result createResourceGroup(array $arguments = [])
 * @method \Http\Promise\Promise createResourceGroupAsync($arguments = [])
 * @method \Dew\Acs\Result deleteResourceGroup(array $arguments = [])
 * @method \Http\Promise\Promise deleteResourceGroupAsync($arguments = [])
 * @method \Dew\Acs\Result getMachineGroup(array $arguments = []) {@deprecated 2022-01-12}
 * @method \Http\Promise\Promise getMachineGroupAsync($arguments = []) {@deprecated 2022-01-12}
 * @method \Dew\Acs\Result createAlgorithm(array $arguments = [])
 * @method \Http\Promise\Promise createAlgorithmAsync($arguments = [])
 * @method \Dew\Acs\Result createAlgorithmVersion(array $arguments = [])
 * @method \Http\Promise\Promise createAlgorithmVersionAsync($arguments = [])
 * @method \Dew\Acs\Result deleteAlgorithm(array $arguments = [])
 * @method \Http\Promise\Promise deleteAlgorithmAsync($arguments = [])
 * @method \Dew\Acs\Result deleteAlgorithmVersion(array $arguments = [])
 * @method \Http\Promise\Promise deleteAlgorithmVersionAsync($arguments = [])
 * @method \Dew\Acs\Result getAlgorithm(array $arguments = [])
 * @method \Http\Promise\Promise getAlgorithmAsync($arguments = [])
 * @method \Dew\Acs\Result getAlgorithmVersion(array $arguments = [])
 * @method \Http\Promise\Promise getAlgorithmVersionAsync($arguments = [])
 * @method \Dew\Acs\Result listAlgorithms(array $arguments = [])
 * @method \Http\Promise\Promise listAlgorithmsAsync($arguments = [])
 * @method \Dew\Acs\Result listAlgorithmVersions(array $arguments = [])
 * @method \Http\Promise\Promise listAlgorithmVersionsAsync($arguments = [])
 * @method \Dew\Acs\Result updateAlgorithm(array $arguments = [])
 * @method \Http\Promise\Promise updateAlgorithmAsync($arguments = [])
 * @method \Dew\Acs\Result updateAlgorithmVersion(array $arguments = [])
 * @method \Http\Promise\Promise updateAlgorithmVersionAsync($arguments = [])
 * @method \Dew\Acs\Result createTrainingJob(array $arguments = [])
 * @method \Http\Promise\Promise createTrainingJobAsync($arguments = [])
 * @method \Dew\Acs\Result createInstanceWebTerminal(array $arguments = [])
 * @method \Http\Promise\Promise createInstanceWebTerminalAsync($arguments = [])
 * @method \Dew\Acs\Result checkInstanceWebTerminal(array $arguments = [])
 * @method \Http\Promise\Promise checkInstanceWebTerminalAsync($arguments = [])
 * @method \Dew\Acs\Result deleteTrainingJob(array $arguments = [])
 * @method \Http\Promise\Promise deleteTrainingJobAsync($arguments = [])
 * @method \Dew\Acs\Result deleteTrainingJobLabels(array $arguments = [])
 * @method \Http\Promise\Promise deleteTrainingJobLabelsAsync($arguments = [])
 * @method \Dew\Acs\Result getToken(array $arguments = [])
 * @method \Http\Promise\Promise getTokenAsync($arguments = [])
 * @method \Dew\Acs\Result getTrainingJob(array $arguments = [])
 * @method \Http\Promise\Promise getTrainingJobAsync($arguments = [])
 * @method \Dew\Acs\Result getTrainingJobErrorInfo(array $arguments = [])
 * @method \Http\Promise\Promise getTrainingJobErrorInfoAsync($arguments = [])
 * @method \Dew\Acs\Result getTrainingJobLatestMetrics(array $arguments = [])
 * @method \Http\Promise\Promise getTrainingJobLatestMetricsAsync($arguments = [])
 * @method \Dew\Acs\Result listTrainingJobs(array $arguments = [])
 * @method \Http\Promise\Promise listTrainingJobsAsync($arguments = [])
 * @method \Dew\Acs\Result listTrainingJobEvents(array $arguments = [])
 * @method \Http\Promise\Promise listTrainingJobEventsAsync($arguments = [])
 * @method \Dew\Acs\Result listTrainingJobInstanceEvents(array $arguments = [])
 * @method \Http\Promise\Promise listTrainingJobInstanceEventsAsync($arguments = [])
 * @method \Dew\Acs\Result listTrainingJobInstanceMetrics(array $arguments = [])
 * @method \Http\Promise\Promise listTrainingJobInstanceMetricsAsync($arguments = [])
 * @method \Dew\Acs\Result listTrainingJobLogs(array $arguments = [])
 * @method \Http\Promise\Promise listTrainingJobLogsAsync($arguments = [])
 * @method \Dew\Acs\Result listTrainingJobMetrics(array $arguments = [])
 * @method \Http\Promise\Promise listTrainingJobMetricsAsync($arguments = [])
 * @method \Dew\Acs\Result listTrainingJobOutputModels(array $arguments = [])
 * @method \Http\Promise\Promise listTrainingJobOutputModelsAsync($arguments = [])
 * @method \Dew\Acs\Result stopTrainingJob(array $arguments = [])
 * @method \Http\Promise\Promise stopTrainingJobAsync($arguments = [])
 * @method \Dew\Acs\Result updateTrainingJobLabels(array $arguments = [])
 * @method \Http\Promise\Promise updateTrainingJobLabelsAsync($arguments = [])
 * @method \Dew\Acs\Result createQuota(array $arguments = [])
 * @method \Http\Promise\Promise createQuotaAsync($arguments = [])
 * @method \Dew\Acs\Result listQuotas(array $arguments = [])
 * @method \Http\Promise\Promise listQuotasAsync($arguments = [])
 * @method \Dew\Acs\Result getQuota(array $arguments = [])
 * @method \Http\Promise\Promise getQuotaAsync($arguments = [])
 * @method \Dew\Acs\Result updateQuota(array $arguments = [])
 * @method \Http\Promise\Promise updateQuotaAsync($arguments = [])
 * @method \Dew\Acs\Result scaleQuota(array $arguments = [])
 * @method \Http\Promise\Promise scaleQuotaAsync($arguments = [])
 * @method \Dew\Acs\Result deleteQuota(array $arguments = [])
 * @method \Http\Promise\Promise deleteQuotaAsync($arguments = [])
 * @method \Dew\Acs\Result listQuotaWorkloads(array $arguments = [])
 * @method \Http\Promise\Promise listQuotaWorkloadsAsync($arguments = [])
 * @method \Dew\Acs\Result listNodes(array $arguments = [])
 * @method \Http\Promise\Promise listNodesAsync($arguments = [])
 * @method \Dew\Acs\Result getSpotPriceHistory(array $arguments = [])
 * @method \Http\Promise\Promise getSpotPriceHistoryAsync($arguments = [])
 */
final class PaiStudioClient extends AcsClient
{
    //
}
