<?php

declare(strict_types=1);

namespace Dew\Acs\Ons;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result openOnsService(array $arguments = [])
 * @method \Http\Promise\Promise openOnsServiceAsync($arguments = [])
 * @method \Dew\Acs\Result onsMessageTrace(array $arguments = [])
 * @method \Http\Promise\Promise onsMessageTraceAsync($arguments = [])
 * @method \Dew\Acs\Result onsMessageGetByMsgId(array $arguments = [])
 * @method \Http\Promise\Promise onsMessageGetByMsgIdAsync($arguments = [])
 * @method \Dew\Acs\Result onsMessageGetByKey(array $arguments = [])
 * @method \Http\Promise\Promise onsMessageGetByKeyAsync($arguments = [])
 * @method \Dew\Acs\Result onsMessagePageQueryByTopic(array $arguments = [])
 * @method \Http\Promise\Promise onsMessagePageQueryByTopicAsync($arguments = [])
 * @method \Dew\Acs\Result onsMessageDetail(array $arguments = [])
 * @method \Http\Promise\Promise onsMessageDetailAsync($arguments = [])
 * @method \Dew\Acs\Result onsRegionList(array $arguments = [])
 * @method \Http\Promise\Promise onsRegionListAsync($arguments = [])
 * @method \Dew\Acs\Result onsInstanceCreate(array $arguments = [])
 * @method \Http\Promise\Promise onsInstanceCreateAsync($arguments = [])
 * @method \Dew\Acs\Result onsInstanceBaseInfo(array $arguments = [])
 * @method \Http\Promise\Promise onsInstanceBaseInfoAsync($arguments = [])
 * @method \Dew\Acs\Result onsInstanceUpdate(array $arguments = [])
 * @method \Http\Promise\Promise onsInstanceUpdateAsync($arguments = [])
 * @method \Dew\Acs\Result onsInstanceInServiceList(array $arguments = [])
 * @method \Http\Promise\Promise onsInstanceInServiceListAsync($arguments = [])
 * @method \Dew\Acs\Result onsInstanceDelete(array $arguments = [])
 * @method \Http\Promise\Promise onsInstanceDeleteAsync($arguments = [])
 * @method \Dew\Acs\Result onsTopicCreate(array $arguments = [])
 * @method \Http\Promise\Promise onsTopicCreateAsync($arguments = [])
 * @method \Dew\Acs\Result onsTopicStatus(array $arguments = [])
 * @method \Http\Promise\Promise onsTopicStatusAsync($arguments = [])
 * @method \Dew\Acs\Result onsTopicList(array $arguments = [])
 * @method \Http\Promise\Promise onsTopicListAsync($arguments = [])
 * @method \Dew\Acs\Result onsTopicSubDetail(array $arguments = [])
 * @method \Http\Promise\Promise onsTopicSubDetailAsync($arguments = [])
 * @method \Dew\Acs\Result onsTopicDelete(array $arguments = [])
 * @method \Http\Promise\Promise onsTopicDeleteAsync($arguments = [])
 * @method \Dew\Acs\Result onsGroupCreate(array $arguments = [])
 * @method \Http\Promise\Promise onsGroupCreateAsync($arguments = [])
 * @method \Dew\Acs\Result onsGroupConsumerUpdate(array $arguments = [])
 * @method \Http\Promise\Promise onsGroupConsumerUpdateAsync($arguments = [])
 * @method \Dew\Acs\Result onsGroupList(array $arguments = [])
 * @method \Http\Promise\Promise onsGroupListAsync($arguments = [])
 * @method \Dew\Acs\Result onsGroupSubDetail(array $arguments = [])
 * @method \Http\Promise\Promise onsGroupSubDetailAsync($arguments = [])
 * @method \Dew\Acs\Result onsGroupDelete(array $arguments = [])
 * @method \Http\Promise\Promise onsGroupDeleteAsync($arguments = [])
 * @method \Dew\Acs\Result listTagResources(array $arguments = [])
 * @method \Http\Promise\Promise listTagResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result tagResources(array $arguments = [])
 * @method \Http\Promise\Promise tagResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result untagResources(array $arguments = [])
 * @method \Http\Promise\Promise untagResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result onsConsumerStatus(array $arguments = [])
 * @method \Http\Promise\Promise onsConsumerStatusAsync($arguments = [])
 * @method \Dew\Acs\Result onsConsumerAccumulate(array $arguments = [])
 * @method \Http\Promise\Promise onsConsumerAccumulateAsync($arguments = [])
 * @method \Dew\Acs\Result onsConsumerGetConnection(array $arguments = [])
 * @method \Http\Promise\Promise onsConsumerGetConnectionAsync($arguments = [])
 * @method \Dew\Acs\Result onsConsumerResetOffset(array $arguments = [])
 * @method \Http\Promise\Promise onsConsumerResetOffsetAsync($arguments = [])
 * @method \Dew\Acs\Result onsConsumerTimeSpan(array $arguments = [])
 * @method \Http\Promise\Promise onsConsumerTimeSpanAsync($arguments = [])
 * @method \Dew\Acs\Result onsMessagePush(array $arguments = [])
 * @method \Http\Promise\Promise onsMessagePushAsync($arguments = [])
 * @method \Dew\Acs\Result onsTrendTopicInputTps(array $arguments = [])
 * @method \Http\Promise\Promise onsTrendTopicInputTpsAsync($arguments = [])
 * @method \Dew\Acs\Result onsTrendGroupOutputTps(array $arguments = [])
 * @method \Http\Promise\Promise onsTrendGroupOutputTpsAsync($arguments = [])
 * @method \Dew\Acs\Result onsTraceQueryByMsgId(array $arguments = [])
 * @method \Http\Promise\Promise onsTraceQueryByMsgIdAsync($arguments = [])
 * @method \Dew\Acs\Result onsTraceQueryByMsgKey(array $arguments = [])
 * @method \Http\Promise\Promise onsTraceQueryByMsgKeyAsync($arguments = [])
 * @method \Dew\Acs\Result onsTraceGetResult(array $arguments = [])
 * @method \Http\Promise\Promise onsTraceGetResultAsync($arguments = [])
 * @method \Dew\Acs\Result onsDLQMessagePageQueryByGroupId(array $arguments = [])
 * @method \Http\Promise\Promise onsDLQMessagePageQueryByGroupIdAsync($arguments = [])
 * @method \Dew\Acs\Result onsDLQMessageGetById(array $arguments = [])
 * @method \Http\Promise\Promise onsDLQMessageGetByIdAsync($arguments = [])
 * @method \Dew\Acs\Result onsDLQMessageResendById(array $arguments = [])
 * @method \Http\Promise\Promise onsDLQMessageResendByIdAsync($arguments = [])
 * @method \Dew\Acs\Result onsTopicUpdate(array $arguments = []) {@deprecated 2019-02-14}
 * @method \Http\Promise\Promise onsTopicUpdateAsync($arguments = []) {@deprecated 2019-02-14}
 */
final class OnsClient extends AcsClient
{
    //
}
