<?php

declare(strict_types=1);

namespace Dew\Acs\Hologram;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result revokeTablePermission(array $arguments = [])
 * @method \Http\Promise\Promise revokeTablePermissionAsync($arguments = [])
 * @method \Dew\Acs\Result revokeSchemaPermission(array $arguments = [])
 * @method \Http\Promise\Promise revokeSchemaPermissionAsync($arguments = [])
 * @method \Dew\Acs\Result revokeDatabasePermission(array $arguments = [])
 * @method \Http\Promise\Promise revokeDatabasePermissionAsync($arguments = [])
 * @method \Dew\Acs\Result listDatabases(array $arguments = [])
 * @method \Http\Promise\Promise listDatabasesAsync($arguments = [])
 * @method \Dew\Acs\Result grantTablePermission(array $arguments = [])
 * @method \Http\Promise\Promise grantTablePermissionAsync($arguments = [])
 * @method \Dew\Acs\Result grantSchemaPermission(array $arguments = [])
 * @method \Http\Promise\Promise grantSchemaPermissionAsync($arguments = [])
 * @method \Dew\Acs\Result grantDatabasePermission(array $arguments = [])
 * @method \Http\Promise\Promise grantDatabasePermissionAsync($arguments = [])
 * @method \Dew\Acs\Result createInstance(array $arguments = [])
 * @method \Http\Promise\Promise createInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result deleteInstance(array $arguments = [])
 * @method \Http\Promise\Promise deleteInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result renewInstance(array $arguments = [])
 * @method \Http\Promise\Promise renewInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result restartInstance(array $arguments = [])
 * @method \Http\Promise\Promise restartInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result resumeInstance(array $arguments = [])
 * @method \Http\Promise\Promise resumeInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result updateInstanceName(array $arguments = [])
 * @method \Http\Promise\Promise updateInstanceNameAsync($arguments = [])
 * @method \Dew\Acs\Result updateInstanceNetworkType(array $arguments = [])
 * @method \Http\Promise\Promise updateInstanceNetworkTypeAsync($arguments = [])
 * @method \Dew\Acs\Result disableHiveAccess(array $arguments = [])
 * @method \Http\Promise\Promise disableHiveAccessAsync($arguments = [])
 * @method \Dew\Acs\Result enableHiveAccess(array $arguments = [])
 * @method \Http\Promise\Promise enableHiveAccessAsync($arguments = [])
 * @method \Dew\Acs\Result stopInstance(array $arguments = [])
 * @method \Http\Promise\Promise stopInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result scaleInstance(array $arguments = [])
 * @method \Http\Promise\Promise scaleInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result changeResourceGroup(array $arguments = [])
 * @method \Http\Promise\Promise changeResourceGroupAsync($arguments = [])
 * @method \Dew\Acs\Result listInstances(array $arguments = [])
 * @method \Http\Promise\Promise listInstancesAsync($arguments = [])
 * @method \Dew\Acs\Result getInstance(array $arguments = [])
 * @method \Http\Promise\Promise getInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result createHoloWarehouse(array $arguments = [])
 * @method \Http\Promise\Promise createHoloWarehouseAsync($arguments = [])
 * @method \Dew\Acs\Result deleteHoloWarehouse(array $arguments = [])
 * @method \Http\Promise\Promise deleteHoloWarehouseAsync($arguments = [])
 * @method \Dew\Acs\Result rebalanceHoloWarehouse(array $arguments = [])
 * @method \Http\Promise\Promise rebalanceHoloWarehouseAsync($arguments = [])
 * @method \Dew\Acs\Result resumeHoloWarehouse(array $arguments = [])
 * @method \Http\Promise\Promise resumeHoloWarehouseAsync($arguments = [])
 * @method \Dew\Acs\Result suspendHoloWarehouse(array $arguments = [])
 * @method \Http\Promise\Promise suspendHoloWarehouseAsync($arguments = [])
 * @method \Dew\Acs\Result renameHoloWarehouse(array $arguments = [])
 * @method \Http\Promise\Promise renameHoloWarehouseAsync($arguments = [])
 * @method \Dew\Acs\Result scaleHoloWarehouse(array $arguments = [])
 * @method \Http\Promise\Promise scaleHoloWarehouseAsync($arguments = [])
 * @method \Dew\Acs\Result restartHoloWarehouse(array $arguments = [])
 * @method \Http\Promise\Promise restartHoloWarehouseAsync($arguments = [])
 * @method \Dew\Acs\Result getWarehouseDetail(array $arguments = [])
 * @method \Http\Promise\Promise getWarehouseDetailAsync($arguments = [])
 * @method \Dew\Acs\Result listWarehouses(array $arguments = [])
 * @method \Http\Promise\Promise listWarehousesAsync($arguments = [])
 * @method \Dew\Acs\Result listBackupData(array $arguments = [])
 * @method \Http\Promise\Promise listBackupDataAsync($arguments = [])
 * @method \Dew\Acs\Result enableSSL(array $arguments = [])
 * @method \Http\Promise\Promise enableSSLAsync($arguments = [])
 * @method \Dew\Acs\Result disableSSL(array $arguments = [])
 * @method \Http\Promise\Promise disableSSLAsync($arguments = [])
 * @method \Dew\Acs\Result getCertificateAttribute(array $arguments = [])
 * @method \Http\Promise\Promise getCertificateAttributeAsync($arguments = [])
 * @method \Dew\Acs\Result getRootCertificate(array $arguments = [])
 * @method \Http\Promise\Promise getRootCertificateAsync($arguments = [])
 * @method \Dew\Acs\Result renewSSLCertificate(array $arguments = [])
 * @method \Http\Promise\Promise renewSSLCertificateAsync($arguments = [])
 */
final class HologramClient extends AcsClient
{
    //
}
