<?php

declare(strict_types=1);

namespace Dew\Acs\EasyGene;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result createWorkspace(array $arguments = [])
 * @method \Http\Promise\Promise createWorkspaceAsync($arguments = [])
 * @method \Dew\Acs\Result deleteWorkspace(array $arguments = [])
 * @method \Http\Promise\Promise deleteWorkspaceAsync($arguments = [])
 * @method \Dew\Acs\Result updateWorkspace(array $arguments = [])
 * @method \Http\Promise\Promise updateWorkspaceAsync($arguments = [])
 * @method \Dew\Acs\Result listWorkspaces(array $arguments = [])
 * @method \Http\Promise\Promise listWorkspacesAsync($arguments = [])
 * @method \Dew\Acs\Result getWorkspace(array $arguments = [])
 * @method \Http\Promise\Promise getWorkspaceAsync($arguments = [])
 * @method \Dew\Acs\Result createApp(array $arguments = [])
 * @method \Http\Promise\Promise createAppAsync($arguments = [])
 * @method \Dew\Acs\Result tagApp(array $arguments = [])
 * @method \Http\Promise\Promise tagAppAsync($arguments = [])
 * @method \Dew\Acs\Result importApp(array $arguments = [])
 * @method \Http\Promise\Promise importAppAsync($arguments = [])
 * @method \Dew\Acs\Result deleteApp(array $arguments = [])
 * @method \Http\Promise\Promise deleteAppAsync($arguments = [])
 * @method \Dew\Acs\Result getApp(array $arguments = [])
 * @method \Http\Promise\Promise getAppAsync($arguments = [])
 * @method \Dew\Acs\Result listApps(array $arguments = [])
 * @method \Http\Promise\Promise listAppsAsync($arguments = [])
 * @method \Dew\Acs\Result createRun(array $arguments = [])
 * @method \Http\Promise\Promise createRunAsync($arguments = [])
 * @method \Dew\Acs\Result getRun(array $arguments = [])
 * @method \Http\Promise\Promise getRunAsync($arguments = [])
 * @method \Dew\Acs\Result deleteRun(array $arguments = [])
 * @method \Http\Promise\Promise deleteRunAsync($arguments = [])
 * @method \Dew\Acs\Result listRuns(array $arguments = [])
 * @method \Http\Promise\Promise listRunsAsync($arguments = [])
 * @method \Dew\Acs\Result listUserActiveRuns(array $arguments = [])
 * @method \Http\Promise\Promise listUserActiveRunsAsync($arguments = [])
 * @method \Dew\Acs\Result abortRun(array $arguments = [])
 * @method \Http\Promise\Promise abortRunAsync($arguments = [])
 * @method \Dew\Acs\Result createEntity(array $arguments = [])
 * @method \Http\Promise\Promise createEntityAsync($arguments = [])
 * @method \Dew\Acs\Result getEntity(array $arguments = [])
 * @method \Http\Promise\Promise getEntityAsync($arguments = [])
 * @method \Dew\Acs\Result deleteEntity(array $arguments = [])
 * @method \Http\Promise\Promise deleteEntityAsync($arguments = [])
 * @method \Dew\Acs\Result deleteEntityItems(array $arguments = [])
 * @method \Http\Promise\Promise deleteEntityItemsAsync($arguments = [])
 * @method \Dew\Acs\Result updateEntity(array $arguments = []) {@deprecated 2021-03-15}
 * @method \Http\Promise\Promise updateEntityAsync($arguments = []) {@deprecated 2021-03-15}
 * @method \Dew\Acs\Result updateEntityItems(array $arguments = [])
 * @method \Http\Promise\Promise updateEntityItemsAsync($arguments = [])
 * @method \Dew\Acs\Result listEntities(array $arguments = [])
 * @method \Http\Promise\Promise listEntitiesAsync($arguments = [])
 * @method \Dew\Acs\Result listEntityItems(array $arguments = [])
 * @method \Http\Promise\Promise listEntityItemsAsync($arguments = [])
 * @method \Dew\Acs\Result copyPublicEntity(array $arguments = [])
 * @method \Http\Promise\Promise copyPublicEntityAsync($arguments = [])
 * @method \Dew\Acs\Result downloadEntity(array $arguments = [])
 * @method \Http\Promise\Promise downloadEntityAsync($arguments = [])
 * @method \Dew\Acs\Result uploadEntity(array $arguments = [])
 * @method \Http\Promise\Promise uploadEntityAsync($arguments = [])
 * @method \Dew\Acs\Result createTemplate(array $arguments = [])
 * @method \Http\Promise\Promise createTemplateAsync($arguments = [])
 * @method \Dew\Acs\Result getTemplate(array $arguments = [])
 * @method \Http\Promise\Promise getTemplateAsync($arguments = [])
 * @method \Dew\Acs\Result deleteTemplate(array $arguments = [])
 * @method \Http\Promise\Promise deleteTemplateAsync($arguments = [])
 * @method \Dew\Acs\Result updateTemplate(array $arguments = [])
 * @method \Http\Promise\Promise updateTemplateAsync($arguments = [])
 * @method \Dew\Acs\Result listTemplates(array $arguments = [])
 * @method \Http\Promise\Promise listTemplatesAsync($arguments = [])
 * @method \Dew\Acs\Result createSubmission(array $arguments = [])
 * @method \Http\Promise\Promise createSubmissionAsync($arguments = [])
 * @method \Dew\Acs\Result getSubmission(array $arguments = [])
 * @method \Http\Promise\Promise getSubmissionAsync($arguments = [])
 * @method \Dew\Acs\Result deleteSubmission(array $arguments = [])
 * @method \Http\Promise\Promise deleteSubmissionAsync($arguments = [])
 * @method \Dew\Acs\Result listSubmissions(array $arguments = [])
 * @method \Http\Promise\Promise listSubmissionsAsync($arguments = [])
 * @method \Dew\Acs\Result abortSubmission(array $arguments = [])
 * @method \Http\Promise\Promise abortSubmissionAsync($arguments = [])
 * @method \Dew\Acs\Result resumeSubmission(array $arguments = [])
 * @method \Http\Promise\Promise resumeSubmissionAsync($arguments = [])
 * @method \Dew\Acs\Result listGlobalApps(array $arguments = [])
 * @method \Http\Promise\Promise listGlobalAppsAsync($arguments = [])
 * @method \Dew\Acs\Result getGlobalApp(array $arguments = [])
 * @method \Http\Promise\Promise getGlobalAppAsync($arguments = [])
 * @method \Dew\Acs\Result listContainerImages(array $arguments = [])
 * @method \Http\Promise\Promise listContainerImagesAsync($arguments = [])
 * @method \Dew\Acs\Result listAuthorizedSoftware(array $arguments = [])
 * @method \Http\Promise\Promise listAuthorizedSoftwareAsync($arguments = [])
 * @method \Dew\Acs\Result listPublicDataset(array $arguments = [])
 * @method \Http\Promise\Promise listPublicDatasetAsync($arguments = [])
 * @method \Dew\Acs\Result getPublicDataset(array $arguments = [])
 * @method \Http\Promise\Promise getPublicDatasetAsync($arguments = [])
 * @method \Dew\Acs\Result listPublicDatasetEntities(array $arguments = [])
 * @method \Http\Promise\Promise listPublicDatasetEntitiesAsync($arguments = [])
 * @method \Dew\Acs\Result getPublicDatasetEntity(array $arguments = [])
 * @method \Http\Promise\Promise getPublicDatasetEntityAsync($arguments = [])
 * @method \Dew\Acs\Result listPublicDatasetEntityItems(array $arguments = [])
 * @method \Http\Promise\Promise listPublicDatasetEntityItemsAsync($arguments = [])
 * @method \Dew\Acs\Result listPublicDatasetTags(array $arguments = [])
 * @method \Http\Promise\Promise listPublicDatasetTagsAsync($arguments = [])
 * @method \Dew\Acs\Result listRegions(array $arguments = [])
 * @method \Http\Promise\Promise listRegionsAsync($arguments = [])
 * @method \Dew\Acs\Result installGlobalApp(array $arguments = [])
 * @method \Http\Promise\Promise installGlobalAppAsync($arguments = [])
 */
final class EasyGeneClient extends AcsClient
{
    //
}
