<?php

declare(strict_types=1);

namespace Dew\Acs\EnergyExpertExternal;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result getDataItemList(array $arguments = [])
 * @method \Http\Promise\Promise getDataItemListAsync($arguments = [])
 * @method \Dew\Acs\Result pushItemData(array $arguments = [])
 * @method \Http\Promise\Promise pushItemDataAsync($arguments = [])
 * @method \Dew\Acs\Result recalculateCarbonEmission(array $arguments = [])
 * @method \Http\Promise\Promise recalculateCarbonEmissionAsync($arguments = [])
 * @method \Dew\Acs\Result getFootprintList(array $arguments = [])
 * @method \Http\Promise\Promise getFootprintListAsync($arguments = [])
 * @method \Dew\Acs\Result generateResult(array $arguments = [])
 * @method \Http\Promise\Promise generateResultAsync($arguments = [])
 * @method \Dew\Acs\Result isCompleted(array $arguments = [])
 * @method \Http\Promise\Promise isCompletedAsync($arguments = [])
 * @method \Dew\Acs\Result getPcrInfo(array $arguments = [])
 * @method \Http\Promise\Promise getPcrInfoAsync($arguments = [])
 * @method \Dew\Acs\Result getGwpInventorySummary(array $arguments = [])
 * @method \Http\Promise\Promise getGwpInventorySummaryAsync($arguments = [])
 * @method \Dew\Acs\Result getGwpBenchmarkSummary(array $arguments = [])
 * @method \Http\Promise\Promise getGwpBenchmarkSummaryAsync($arguments = [])
 * @method \Dew\Acs\Result getEpdSummary(array $arguments = [])
 * @method \Http\Promise\Promise getEpdSummaryAsync($arguments = [])
 * @method \Dew\Acs\Result getInventoryList(array $arguments = [])
 * @method \Http\Promise\Promise getInventoryListAsync($arguments = [])
 * @method \Dew\Acs\Result getGwpBenchmarkList(array $arguments = [])
 * @method \Http\Promise\Promise getGwpBenchmarkListAsync($arguments = [])
 * @method \Dew\Acs\Result getGwpInventoryConstitute(array $arguments = [])
 * @method \Http\Promise\Promise getGwpInventoryConstituteAsync($arguments = [])
 * @method \Dew\Acs\Result getEpdInventoryConstitute(array $arguments = [])
 * @method \Http\Promise\Promise getEpdInventoryConstituteAsync($arguments = [])
 * @method \Dew\Acs\Result getReductionProposal(array $arguments = [])
 * @method \Http\Promise\Promise getReductionProposalAsync($arguments = [])
 * @method \Dew\Acs\Result getDataQualityAnalysis(array $arguments = [])
 * @method \Http\Promise\Promise getDataQualityAnalysisAsync($arguments = [])
 * @method \Dew\Acs\Result getEmissionSummary(array $arguments = [])
 * @method \Http\Promise\Promise getEmissionSummaryAsync($arguments = [])
 * @method \Dew\Acs\Result getEmissionSourceConstitute(array $arguments = [])
 * @method \Http\Promise\Promise getEmissionSourceConstituteAsync($arguments = [])
 * @method \Dew\Acs\Result getCarbonEmissionTrend(array $arguments = [])
 * @method \Http\Promise\Promise getCarbonEmissionTrendAsync($arguments = [])
 * @method \Dew\Acs\Result getElecConstitute(array $arguments = [])
 * @method \Http\Promise\Promise getElecConstituteAsync($arguments = [])
 * @method \Dew\Acs\Result getElecTrend(array $arguments = [])
 * @method \Http\Promise\Promise getElecTrendAsync($arguments = [])
 * @method \Dew\Acs\Result getAreaElecConstitute(array $arguments = [])
 * @method \Http\Promise\Promise getAreaElecConstituteAsync($arguments = [])
 * @method \Dew\Acs\Result getGasConstitute(array $arguments = [])
 * @method \Http\Promise\Promise getGasConstituteAsync($arguments = [])
 * @method \Dew\Acs\Result getOrgConstitute(array $arguments = [])
 * @method \Http\Promise\Promise getOrgConstituteAsync($arguments = [])
 * @method \Dew\Acs\Result batchSaveInstructionStatus(array $arguments = [])
 * @method \Http\Promise\Promise batchSaveInstructionStatusAsync($arguments = [])
 * @method \Dew\Acs\Result setRunningPlan(array $arguments = [])
 * @method \Http\Promise\Promise setRunningPlanAsync($arguments = [])
 * @method \Dew\Acs\Result editUnfavorableAreaDevices(array $arguments = [])
 * @method \Http\Promise\Promise editUnfavorableAreaDevicesAsync($arguments = [])
 * @method \Dew\Acs\Result editProhibitedDevices(array $arguments = [])
 * @method \Http\Promise\Promise editProhibitedDevicesAsync($arguments = [])
 * @method \Dew\Acs\Result batchUpdateSystemRunningPlan(array $arguments = [])
 * @method \Http\Promise\Promise batchUpdateSystemRunningPlanAsync($arguments = [])
 * @method \Dew\Acs\Result pushDeviceData(array $arguments = [])
 * @method \Http\Promise\Promise pushDeviceDataAsync($arguments = [])
 * @method \Dew\Acs\Result getOrgAndFactory(array $arguments = [])
 * @method \Http\Promise\Promise getOrgAndFactoryAsync($arguments = [])
 * @method \Dew\Acs\Result getDeviceList(array $arguments = [])
 * @method \Http\Promise\Promise getDeviceListAsync($arguments = [])
 * @method \Dew\Acs\Result getDeviceInfo(array $arguments = [])
 * @method \Http\Promise\Promise getDeviceInfoAsync($arguments = [])
 * @method \Dew\Acs\Result submitDocParsingTask(array $arguments = [])
 * @method \Http\Promise\Promise submitDocParsingTaskAsync($arguments = [])
 * @method \Dew\Acs\Result getDocParsingResult(array $arguments = [])
 * @method \Http\Promise\Promise getDocParsingResultAsync($arguments = [])
 * @method \Dew\Acs\Result submitDocExtractionTask(array $arguments = [])
 * @method \Http\Promise\Promise submitDocExtractionTaskAsync($arguments = [])
 * @method \Dew\Acs\Result getDocExtractionResult(array $arguments = [])
 * @method \Http\Promise\Promise getDocExtractionResultAsync($arguments = [])
 * @method \Dew\Acs\Result submitVLExtractionTask(array $arguments = [])
 * @method \Http\Promise\Promise submitVLExtractionTaskAsync($arguments = [])
 * @method \Dew\Acs\Result getVLExtractionResult(array $arguments = [])
 * @method \Http\Promise\Promise getVLExtractionResultAsync($arguments = [])
 * @method \Dew\Acs\Result analyzeVlRealtime(array $arguments = [])
 * @method \Http\Promise\Promise analyzeVlRealtimeAsync($arguments = [])
 * @method \Dew\Acs\Result getChatFolderList(array $arguments = [])
 * @method \Http\Promise\Promise getChatFolderListAsync($arguments = [])
 * @method \Dew\Acs\Result createChatSession(array $arguments = [])
 * @method \Http\Promise\Promise createChatSessionAsync($arguments = [])
 * @method \Dew\Acs\Result getChatSessionList(array $arguments = [])
 * @method \Http\Promise\Promise getChatSessionListAsync($arguments = [])
 * @method \Dew\Acs\Result getChatList(array $arguments = [])
 * @method \Http\Promise\Promise getChatListAsync($arguments = [])
 * @method \Dew\Acs\Result chat(array $arguments = [])
 * @method \Http\Promise\Promise chatAsync($arguments = [])
 * @method \Dew\Acs\Result chatStream(array $arguments = [])
 * @method \Http\Promise\Promise chatStreamAsync($arguments = [])
 * @method \Dew\Acs\Result getDocumentAnalyzeResult(array $arguments = [])
 * @method \Http\Promise\Promise getDocumentAnalyzeResultAsync($arguments = [])
 * @method \Dew\Acs\Result submitDocumentAnalyzeJob(array $arguments = [])
 * @method \Http\Promise\Promise submitDocumentAnalyzeJobAsync($arguments = [])
 * @method \Dew\Acs\Result sendDocumentAskQuestion(array $arguments = [])
 * @method \Http\Promise\Promise sendDocumentAskQuestionAsync($arguments = [])
 */
final class EnergyExpertExternalClient extends AcsClient
{
    //
}
