<?php

declare(strict_types=1);

namespace Dew\Acs\Apig;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result createHttpApi(array $arguments = [])
 * @method \Http\Promise\Promise createHttpApiAsync($arguments = [])
 * @method \Dew\Acs\Result updateHttpApi(array $arguments = [])
 * @method \Http\Promise\Promise updateHttpApiAsync($arguments = [])
 * @method \Dew\Acs\Result getHttpApi(array $arguments = [])
 * @method \Http\Promise\Promise getHttpApiAsync($arguments = [])
 * @method \Dew\Acs\Result listHttpApis(array $arguments = [])
 * @method \Http\Promise\Promise listHttpApisAsync($arguments = [])
 * @method \Dew\Acs\Result deleteHttpApi(array $arguments = [])
 * @method \Http\Promise\Promise deleteHttpApiAsync($arguments = [])
 * @method \Dew\Acs\Result createHttpApiOperation(array $arguments = [])
 * @method \Http\Promise\Promise createHttpApiOperationAsync($arguments = [])
 * @method \Dew\Acs\Result updateHttpApiOperation(array $arguments = [])
 * @method \Http\Promise\Promise updateHttpApiOperationAsync($arguments = [])
 * @method \Dew\Acs\Result getHttpApiOperation(array $arguments = [])
 * @method \Http\Promise\Promise getHttpApiOperationAsync($arguments = [])
 * @method \Dew\Acs\Result listHttpApiOperations(array $arguments = [])
 * @method \Http\Promise\Promise listHttpApiOperationsAsync($arguments = [])
 * @method \Dew\Acs\Result deleteHttpApiOperation(array $arguments = [])
 * @method \Http\Promise\Promise deleteHttpApiOperationAsync($arguments = [])
 * @method \Dew\Acs\Result offlineHttpApi(array $arguments = [])
 * @method \Http\Promise\Promise offlineHttpApiAsync($arguments = [])
 * @method \Dew\Acs\Result publishHttpApi(array $arguments = [])
 * @method \Http\Promise\Promise publishHttpApiAsync($arguments = [])
 * @method \Dew\Acs\Result getGateway(array $arguments = [])
 * @method \Http\Promise\Promise getGatewayAsync($arguments = [])
 * @method \Dew\Acs\Result listGateways(array $arguments = [])
 * @method \Http\Promise\Promise listGatewaysAsync($arguments = [])
 * @method \Dew\Acs\Result addGatewaySecurityGroupRule(array $arguments = [])
 * @method \Http\Promise\Promise addGatewaySecurityGroupRuleAsync($arguments = [])
 * @method \Dew\Acs\Result deleteGateway(array $arguments = [])
 * @method \Http\Promise\Promise deleteGatewayAsync($arguments = [])
 * @method \Dew\Acs\Result createGatewayRoute(array $arguments = [])
 * @method \Http\Promise\Promise createGatewayRouteAsync($arguments = [])
 * @method \Dew\Acs\Result getGatewayRoute(array $arguments = [])
 * @method \Http\Promise\Promise getGatewayRouteAsync($arguments = [])
 * @method \Dew\Acs\Result listGatewayRoutes(array $arguments = [])
 * @method \Http\Promise\Promise listGatewayRoutesAsync($arguments = [])
 * @method \Dew\Acs\Result updateGatewayRoute(array $arguments = [])
 * @method \Http\Promise\Promise updateGatewayRouteAsync($arguments = [])
 * @method \Dew\Acs\Result deleteGatewayRoute(array $arguments = [])
 * @method \Http\Promise\Promise deleteGatewayRouteAsync($arguments = [])
 * @method \Dew\Acs\Result publishGatewayRoute(array $arguments = [])
 * @method \Http\Promise\Promise publishGatewayRouteAsync($arguments = [])
 * @method \Dew\Acs\Result offlineGatewayRoute(array $arguments = [])
 * @method \Http\Promise\Promise offlineGatewayRouteAsync($arguments = [])
 * @method \Dew\Acs\Result createServiceSource(array $arguments = [])
 * @method \Http\Promise\Promise createServiceSourceAsync($arguments = [])
 * @method \Dew\Acs\Result getGatewayService(array $arguments = [])
 * @method \Http\Promise\Promise getGatewayServiceAsync($arguments = [])
 * @method \Dew\Acs\Result updateServiceSource(array $arguments = [])
 * @method \Http\Promise\Promise updateServiceSourceAsync($arguments = [])
 * @method \Dew\Acs\Result listGatewayServices(array $arguments = [])
 * @method \Http\Promise\Promise listGatewayServicesAsync($arguments = [])
 * @method \Dew\Acs\Result deleteServiceSource(array $arguments = [])
 * @method \Http\Promise\Promise deleteServiceSourceAsync($arguments = [])
 * @method \Dew\Acs\Result createGatewayService(array $arguments = [])
 * @method \Http\Promise\Promise createGatewayServiceAsync($arguments = [])
 * @method \Dew\Acs\Result updateGatewayService(array $arguments = [])
 * @method \Http\Promise\Promise updateGatewayServiceAsync($arguments = [])
 * @method \Dew\Acs\Result createGatewayServiceVersion(array $arguments = [])
 * @method \Http\Promise\Promise createGatewayServiceVersionAsync($arguments = [])
 * @method \Dew\Acs\Result updateGatewayServiceVersion(array $arguments = [])
 * @method \Http\Promise\Promise updateGatewayServiceVersionAsync($arguments = [])
 * @method \Dew\Acs\Result deleteGatewayServiceVersion(array $arguments = [])
 * @method \Http\Promise\Promise deleteGatewayServiceVersionAsync($arguments = [])
 * @method \Dew\Acs\Result deleteGatewayService(array $arguments = [])
 * @method \Http\Promise\Promise deleteGatewayServiceAsync($arguments = [])
 * @method \Dew\Acs\Result listEnvironments(array $arguments = [])
 * @method \Http\Promise\Promise listEnvironmentsAsync($arguments = [])
 * @method \Dew\Acs\Result updateEnvironment(array $arguments = [])
 * @method \Http\Promise\Promise updateEnvironmentAsync($arguments = [])
 * @method \Dew\Acs\Result getEnvironment(array $arguments = [])
 * @method \Http\Promise\Promise getEnvironmentAsync($arguments = [])
 * @method \Dew\Acs\Result createEnvironment(array $arguments = [])
 * @method \Http\Promise\Promise createEnvironmentAsync($arguments = [])
 * @method \Dew\Acs\Result updateDomain(array $arguments = [])
 * @method \Http\Promise\Promise updateDomainAsync($arguments = [])
 * @method \Dew\Acs\Result listDomains(array $arguments = [])
 * @method \Http\Promise\Promise listDomainsAsync($arguments = [])
 * @method \Dew\Acs\Result getDomain(array $arguments = [])
 * @method \Http\Promise\Promise getDomainAsync($arguments = [])
 * @method \Dew\Acs\Result createDomain(array $arguments = [])
 * @method \Http\Promise\Promise createDomainAsync($arguments = [])
 * @method \Dew\Acs\Result deleteEnvironment(array $arguments = [])
 * @method \Http\Promise\Promise deleteEnvironmentAsync($arguments = [])
 * @method \Dew\Acs\Result deleteDomain(array $arguments = [])
 * @method \Http\Promise\Promise deleteDomainAsync($arguments = [])
 */
final class ApigClient extends AcsClient
{
    //
}
