<?php

declare(strict_types=1);

namespace Dew\Acs\EmrServerlessSpark;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result addMembers(array $arguments = [])
 * @method \Http\Promise\Promise addMembersAsync($arguments = [])
 * @method \Dew\Acs\Result listMembers(array $arguments = [])
 * @method \Http\Promise\Promise listMembersAsync($arguments = [])
 * @method \Dew\Acs\Result grantRoleToUsers(array $arguments = [])
 * @method \Http\Promise\Promise grantRoleToUsersAsync($arguments = [])
 * @method \Dew\Acs\Result listKyuubiSparkApplications(array $arguments = [])
 * @method \Http\Promise\Promise listKyuubiSparkApplicationsAsync($arguments = [])
 * @method \Dew\Acs\Result getSessionCluster(array $arguments = [])
 * @method \Http\Promise\Promise getSessionClusterAsync($arguments = [])
 * @method \Dew\Acs\Result createSessionCluster(array $arguments = [])
 * @method \Http\Promise\Promise createSessionClusterAsync($arguments = [])
 * @method \Dew\Acs\Result stopSessionCluster(array $arguments = [])
 * @method \Http\Promise\Promise stopSessionClusterAsync($arguments = [])
 * @method \Dew\Acs\Result startSessionCluster(array $arguments = [])
 * @method \Http\Promise\Promise startSessionClusterAsync($arguments = [])
 * @method \Dew\Acs\Result listSessionClusters(array $arguments = [])
 * @method \Http\Promise\Promise listSessionClustersAsync($arguments = [])
 * @method \Dew\Acs\Result getTemplate(array $arguments = [])
 * @method \Http\Promise\Promise getTemplateAsync($arguments = [])
 * @method \Dew\Acs\Result terminateSqlStatement(array $arguments = [])
 * @method \Http\Promise\Promise terminateSqlStatementAsync($arguments = [])
 * @method \Dew\Acs\Result createSqlStatement(array $arguments = [])
 * @method \Http\Promise\Promise createSqlStatementAsync($arguments = [])
 * @method \Dew\Acs\Result getSqlStatement(array $arguments = [])
 * @method \Http\Promise\Promise getSqlStatementAsync($arguments = [])
 * @method \Dew\Acs\Result listSqlStatementContents(array $arguments = [])
 * @method \Http\Promise\Promise listSqlStatementContentsAsync($arguments = [])
 * @method \Dew\Acs\Result createWorkspace(array $arguments = [])
 * @method \Http\Promise\Promise createWorkspaceAsync($arguments = [])
 * @method \Dew\Acs\Result listWorkspaces(array $arguments = [])
 * @method \Http\Promise\Promise listWorkspacesAsync($arguments = [])
 * @method \Dew\Acs\Result listWorkspaceQueues(array $arguments = [])
 * @method \Http\Promise\Promise listWorkspaceQueuesAsync($arguments = [])
 * @method \Dew\Acs\Result editWorkspaceQueue(array $arguments = [])
 * @method \Http\Promise\Promise editWorkspaceQueueAsync($arguments = [])
 * @method \Dew\Acs\Result listReleaseVersions(array $arguments = [])
 * @method \Http\Promise\Promise listReleaseVersionsAsync($arguments = [])
 * @method \Dew\Acs\Result listLogContents(array $arguments = [])
 * @method \Http\Promise\Promise listLogContentsAsync($arguments = [])
 * @method \Dew\Acs\Result getCuHours(array $arguments = [])
 * @method \Http\Promise\Promise getCuHoursAsync($arguments = [])
 * @method \Dew\Acs\Result getDoctorApplication(array $arguments = [])
 * @method \Http\Promise\Promise getDoctorApplicationAsync($arguments = [])
 * @method \Dew\Acs\Result cancelJobRun(array $arguments = [])
 * @method \Http\Promise\Promise cancelJobRunAsync($arguments = [])
 * @method \Dew\Acs\Result listJobRuns(array $arguments = [])
 * @method \Http\Promise\Promise listJobRunsAsync($arguments = [])
 * @method \Dew\Acs\Result getJobRun(array $arguments = [])
 * @method \Http\Promise\Promise getJobRunAsync($arguments = [])
 * @method \Dew\Acs\Result startJobRun(array $arguments = [])
 * @method \Http\Promise\Promise startJobRunAsync($arguments = [])
 * @method \Dew\Acs\Result startProcessInstance(array $arguments = [])
 * @method \Http\Promise\Promise startProcessInstanceAsync($arguments = [])
 * @method \Dew\Acs\Result updateProcessDefinitionWithSchedule(array $arguments = [])
 * @method \Http\Promise\Promise updateProcessDefinitionWithScheduleAsync($arguments = [])
 * @method \Dew\Acs\Result createProcessDefinitionWithSchedule(array $arguments = [])
 * @method \Http\Promise\Promise createProcessDefinitionWithScheduleAsync($arguments = [])
 * @method \Dew\Acs\Result listKyuubiToken(array $arguments = [])
 * @method \Http\Promise\Promise listKyuubiTokenAsync($arguments = [])
 * @method \Dew\Acs\Result listKyuubiServices(array $arguments = [])
 * @method \Http\Promise\Promise listKyuubiServicesAsync($arguments = [])
 * @method \Dew\Acs\Result getLivyCompute(array $arguments = [])
 * @method \Http\Promise\Promise getLivyComputeAsync($arguments = [])
 * @method \Dew\Acs\Result listLivyComputeToken(array $arguments = [])
 * @method \Http\Promise\Promise listLivyComputeTokenAsync($arguments = [])
 * @method \Dew\Acs\Result stopLivyCompute(array $arguments = [])
 * @method \Http\Promise\Promise stopLivyComputeAsync($arguments = [])
 * @method \Dew\Acs\Result deleteLivyComputeToken(array $arguments = [])
 * @method \Http\Promise\Promise deleteLivyComputeTokenAsync($arguments = [])
 * @method \Dew\Acs\Result createLivyComputeToken(array $arguments = [])
 * @method \Http\Promise\Promise createLivyComputeTokenAsync($arguments = [])
 * @method \Dew\Acs\Result getLivyComputeToken(array $arguments = [])
 * @method \Http\Promise\Promise getLivyComputeTokenAsync($arguments = [])
 * @method \Dew\Acs\Result refreshLivyComputeToken(array $arguments = [])
 * @method \Http\Promise\Promise refreshLivyComputeTokenAsync($arguments = [])
 * @method \Dew\Acs\Result startLivyCompute(array $arguments = [])
 * @method \Http\Promise\Promise startLivyComputeAsync($arguments = [])
 * @method \Dew\Acs\Result listLivyCompute(array $arguments = [])
 * @method \Http\Promise\Promise listLivyComputeAsync($arguments = [])
 * @method \Dew\Acs\Result updateLivyCompute(array $arguments = [])
 * @method \Http\Promise\Promise updateLivyComputeAsync($arguments = [])
 * @method \Dew\Acs\Result createLivyCompute(array $arguments = [])
 * @method \Http\Promise\Promise createLivyComputeAsync($arguments = [])
 * @method \Dew\Acs\Result deleteLivyCompute(array $arguments = [])
 * @method \Http\Promise\Promise deleteLivyComputeAsync($arguments = [])
 */
final class EmrServerlessSparkClient extends AcsClient
{
    //
}
