<?php

declare(strict_types=1);

namespace Dew\Acs\Aiccs;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result importOneTaskPhoneNumber(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise importOneTaskPhoneNumberAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result queryAiVoiceAgentDetail(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise queryAiVoiceAgentDetailAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result pageQueryAgentList(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise pageQueryAgentListAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result queryConversationDetailInfo(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise queryConversationDetailInfoAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result queryAiCallDetailPage(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise queryAiCallDetailPageAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result stopAiCallTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise stopAiCallTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result cancelAiCallDetails(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise cancelAiCallDetailsAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result startAiCallTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise startAiCallTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result updateAiCallTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise updateAiCallTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result queryAiCallTaskPage(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise queryAiCallTaskPageAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result queryAiCallTaskDetail(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise queryAiCallTaskDetailAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result importTaskNumberDatas(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise importTaskNumberDatasAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result createAiCallTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise createAiCallTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result llmSmartCall(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise llmSmartCallAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result llmSmartCallEncrypt(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise llmSmartCallEncryptAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result hangupOperate(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise hangupOperateAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result listAvailableTts(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise listAvailableTtsAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getHotlineServiceStatistics(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getHotlineServiceStatisticsAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getSkillGroupAndAgentStatusSummary(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getSkillGroupAndAgentStatusSummaryAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getDepartmentalLatitudeAgentStatus(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getDepartmentalLatitudeAgentStatusAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getSkillGroupLatitudeState(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getSkillGroupLatitudeStateAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getAgentBasisStatus(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getAgentBasisStatusAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getAgentStatistics(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getAgentStatisticsAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getOnlineServiceVolume(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getOnlineServiceVolumeAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getSeatInformation(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getSeatInformationAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getSkillGroupServiceCapability(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getSkillGroupServiceCapabilityAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getSkillGroupAgentStatusDetails(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getSkillGroupAgentStatusDetailsAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getOnlineSeatInformation(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getOnlineSeatInformationAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getQueueInformation(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getQueueInformationAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getSkillGroupStatusTotal(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getSkillGroupStatusTotalAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getAgentDetailReport(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getAgentDetailReportAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getSkillGroupServiceStatus(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getSkillGroupServiceStatusAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getAgentServiceStatus(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getAgentServiceStatusAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result createAgent(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise createAgentAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result deleteAgent(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise deleteAgentAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result updateAgent(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise updateAgentAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getAgent(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getAgentAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result listAgentBySkillGroupId(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise listAgentBySkillGroupIdAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getHotlineAgentStatus(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getHotlineAgentStatusAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result removeAgentFromSkillGroup(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise removeAgentFromSkillGroupAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getHotlineAgentDetail(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getHotlineAgentDetailAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result createSkillGroup(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise createSkillGroupAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result updateSkillGroup(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise updateSkillGroupAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result removeSkillGroup(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise removeSkillGroupAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result querySkillGroups(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise querySkillGroupsAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result listSkillGroup(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise listSkillGroupAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getDepGroupTreeData(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getDepGroupTreeDataAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result createDepartment(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise createDepartmentAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getAllDepartment(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getAllDepartmentAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result deleteDepartment(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise deleteDepartmentAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result updateDepartment(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise updateDepartmentAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result generateWebSocketSign(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise generateWebSocketSignAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result hotlineSessionQuery(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise hotlineSessionQueryAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getRecordData(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getRecordDataAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getRecordUrl(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getRecordUrlAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result describeRecordData(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise describeRecordDataAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getIndexCurrentValue(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getIndexCurrentValueAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getAgentIndexRealTime(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getAgentIndexRealTimeAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getHotlineAgentDetailReport(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getHotlineAgentDetailReportAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getHotlineGroupDetailReport(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getHotlineGroupDetailReportAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result queryTouchList(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise queryTouchListAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getCustomerInfo(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getCustomerInfoAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getHotlineMessageLog(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getHotlineMessageLogAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getHotlineCallAction(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getHotlineCallActionAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result robotCall(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise robotCallAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result listRobotCallDialog(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise listRobotCallDialogAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result listAiccsRobot(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise listAiccsRobotAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result listRobotParams(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise listRobotParamsAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getCallSoundRecord(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getCallSoundRecordAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result listRobotNode(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise listRobotNodeAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result createTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise createTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result attachTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise attachTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result startTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise startTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result stopTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise stopTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result cancelTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise cancelTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result listTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise listTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result listTaskDetail(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise listTaskDetailAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result listDialog(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise listDialogAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result sendCcoSmartCall(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise sendCcoSmartCallAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result sendCcoSmartCallOperate(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise sendCcoSmartCallOperateAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result createAiOutboundTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise createAiOutboundTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result createAiOutboundTaskBatch(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise createAiOutboundTaskBatchAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result deleteAiOutboundTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise deleteAiOutboundTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getAiOutboundTaskBizData(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getAiOutboundTaskBizDataAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getAiOutboundTaskExecDetail(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getAiOutboundTaskExecDetailAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getAiOutboundTaskDetail(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getAiOutboundTaskDetailAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result updateAiOutboundTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise updateAiOutboundTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result insertAiOutboundPhoneNums(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise insertAiOutboundPhoneNumsAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getAiOutboundTaskProgress(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getAiOutboundTaskProgressAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result stopAiOutboundTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise stopAiOutboundTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result terminateAiOutboundTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise terminateAiOutboundTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getAiOutboundTaskList(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getAiOutboundTaskListAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result startAiOutboundTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise startAiOutboundTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result addHotlineNumber(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise addHotlineNumberAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result deleteHotlineNumber(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise deleteHotlineNumberAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result resetHotlineNumber(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise resetHotlineNumberAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result queryHotlineNumber(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise queryHotlineNumberAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getConfigNumList(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getConfigNumListAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result answerCall(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise answerCallAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result finishHotlineService(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise finishHotlineServiceAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getNumLocation(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getNumLocationAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getRtcToken(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getRtcTokenAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result hangupCall(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise hangupCallAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result listHotlineRecord(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise listHotlineRecordAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result listOutboundPhoneNumber(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise listOutboundPhoneNumberAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result makeDoubleCall(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise makeDoubleCallAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result sendHotlineHeartBeat(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise sendHotlineHeartBeatAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result startCall(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise startCallAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result startHotlineService(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise startHotlineServiceAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result suspendHotlineService(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise suspendHotlineServiceAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result addOuterAccount(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise addOuterAccountAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result aiccsSmartCall(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise aiccsSmartCallAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result aiccsSmartCallOperate(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise aiccsSmartCallOperateAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result batchCreateQualityProjects(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise batchCreateQualityProjectsAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result changeChatAgentStatus(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise changeChatAgentStatusAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result changeQualityProjectStatus(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise changeQualityProjectStatusAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result createOutboundTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise createOutboundTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result createQualityProject(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise createQualityProjectAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result createQualityRule(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise createQualityRuleAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result createThirdSsoAgent(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise createThirdSsoAgentAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result deleteOutboundTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise deleteOutboundTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result deleteOuterAccount(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise deleteOuterAccountAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result deleteQualityProject(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise deleteQualityProjectAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result deleteQualityRule(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise deleteQualityRuleAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result editQualityProject(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise editQualityProjectAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result editQualityRule(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise editQualityRuleAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result editQualityRuleTag(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise editQualityRuleTagAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result encryptPhoneNum(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise encryptPhoneNumAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result fetchCall(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise fetchCallAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getAgentById(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getAgentByIdAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getHotlineRuntimeInfo(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getHotlineRuntimeInfoAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getHotlineWaitingNumber(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getHotlineWaitingNumberAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getInstanceList(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getInstanceListAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getMcuLvsIp(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getMcuLvsIpAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getOutbounNumList(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getOutbounNumListAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getQualityProjectDetail(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getQualityProjectDetailAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getQualityProjectList(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getQualityProjectListAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getQualityProjectLog(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getQualityProjectLogAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getQualityResult(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getQualityResultAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getQualityRuleDetail(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getQualityRuleDetailAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getQualityRuleList(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getQualityRuleListAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result getQualityRuleTagList(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise getQualityRuleTagListAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result hangUpDoubleCall(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise hangUpDoubleCallAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result hangupThirdCall(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise hangupThirdCallAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result holdCall(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise holdCallAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result insertTaskDetail(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise insertTaskDetailAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result joinThirdCall(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise joinThirdCallAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result listChatRecordDetail(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise listChatRecordDetailAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result listHotlineRecordDetail(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise listHotlineRecordDetailAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result listRoles(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise listRolesAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result makeCall(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise makeCallAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result queryHotlineInQueue(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise queryHotlineInQueueAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result queryOutboundTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise queryOutboundTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result queryTaskDetail(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise queryTaskDetailAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result queryTickets(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise queryTicketsAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result restartOutboundTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise restartOutboundTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result startCallV2(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise startCallV2Async($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result startChatWork(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise startChatWorkAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result startMicroOutbound(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise startMicroOutboundAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result suspendOutboundTask(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise suspendOutboundTaskAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result updateOuterAccount(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise updateOuterAccountAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result transferCallToSkillGroup(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise transferCallToSkillGroupAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result addSkillGroup(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise addSkillGroupAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result deleteSkillGroup(array $arguments = []) {@since 2019-10-15}
 * @method \Http\Promise\Promise deleteSkillGroupAsync($arguments = []) {@since 2019-10-15}
 * @method \Dew\Acs\Result addBlacklist(array $arguments = [])
 * @method \Http\Promise\Promise addBlacklistAsync($arguments = [])
 * @method \Dew\Acs\Result addTask(array $arguments = [])
 * @method \Http\Promise\Promise addTaskAsync($arguments = [])
 * @method \Dew\Acs\Result agentCancelCall(array $arguments = [])
 * @method \Http\Promise\Promise agentCancelCallAsync($arguments = [])
 * @method \Dew\Acs\Result agentRecoverCall(array $arguments = [])
 * @method \Http\Promise\Promise agentRecoverCallAsync($arguments = [])
 * @method \Dew\Acs\Result details(array $arguments = [])
 * @method \Http\Promise\Promise detailsAsync($arguments = [])
 * @method \Dew\Acs\Result editTask(array $arguments = [])
 * @method \Http\Promise\Promise editTaskAsync($arguments = [])
 * @method \Dew\Acs\Result importNumber(array $arguments = [])
 * @method \Http\Promise\Promise importNumberAsync($arguments = [])
 * @method \Dew\Acs\Result importNumberV2(array $arguments = [])
 * @method \Http\Promise\Promise importNumberV2Async($arguments = [])
 * @method \Dew\Acs\Result page(array $arguments = [])
 * @method \Http\Promise\Promise pageAsync($arguments = [])
 * @method \Dew\Acs\Result smsTemplateCreate(array $arguments = [])
 * @method \Http\Promise\Promise smsTemplateCreateAsync($arguments = [])
 * @method \Dew\Acs\Result smsTemplatePageList(array $arguments = [])
 * @method \Http\Promise\Promise smsTemplatePageListAsync($arguments = [])
 * @method \Dew\Acs\Result taskCallChats(array $arguments = [])
 * @method \Http\Promise\Promise taskCallChatsAsync($arguments = [])
 * @method \Dew\Acs\Result taskCallInfo(array $arguments = [])
 * @method \Http\Promise\Promise taskCallInfoAsync($arguments = [])
 * @method \Dew\Acs\Result taskCallList(array $arguments = [])
 * @method \Http\Promise\Promise taskCallListAsync($arguments = [])
 * @method \Dew\Acs\Result taskCancelCall(array $arguments = [])
 * @method \Http\Promise\Promise taskCancelCallAsync($arguments = [])
 * @method \Dew\Acs\Result taskList(array $arguments = [])
 * @method \Http\Promise\Promise taskListAsync($arguments = [])
 * @method \Dew\Acs\Result taskRecoverCall(array $arguments = [])
 * @method \Http\Promise\Promise taskRecoverCallAsync($arguments = [])
 * @method \Dew\Acs\Result templateList(array $arguments = [])
 * @method \Http\Promise\Promise templateListAsync($arguments = [])
 * @method \Dew\Acs\Result updateAgentStatus(array $arguments = [])
 * @method \Http\Promise\Promise updateAgentStatusAsync($arguments = [])
 * @method \Dew\Acs\Result updateTaskCustomer(array $arguments = [])
 * @method \Http\Promise\Promise updateTaskCustomerAsync($arguments = [])
 */
final class AiccsClient extends AcsClient
{
    //
}
