<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto

namespace Dew\Acs\Sls\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.sls.Log</code>
 */
class Log extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>required uint32 time = 1;</code>
     */
    protected $time = null;
    /**
     * Generated from protobuf field <code>repeated .acs.sls.LogContent contents = 2;</code>
     */
    private $contents;
    /**
     * Generated from protobuf field <code>optional fixed32 time_ns = 4;</code>
     */
    protected $time_ns = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $time
     *     @type array<\Dew\Acs\Sls\Messages\LogContent>|\Google\Protobuf\Internal\RepeatedField $contents
     *     @type int $time_ns
     * }
     */
    public function __construct($data = NULL) {
        \Dew\Acs\Sls\Metadata\Log::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>required uint32 time = 1;</code>
     * @return int
     */
    public function getTime()
    {
        return isset($this->time) ? $this->time : 0;
    }

    public function hasTime()
    {
        return isset($this->time);
    }

    public function clearTime()
    {
        unset($this->time);
    }

    /**
     * Generated from protobuf field <code>required uint32 time = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkUint32($var);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .acs.sls.LogContent contents = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getContents()
    {
        return $this->contents;
    }

    /**
     * Generated from protobuf field <code>repeated .acs.sls.LogContent contents = 2;</code>
     * @param array<\Dew\Acs\Sls\Messages\LogContent>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setContents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dew\Acs\Sls\Messages\LogContent::class);
        $this->contents = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional fixed32 time_ns = 4;</code>
     * @return int
     */
    public function getTimeNs()
    {
        return isset($this->time_ns) ? $this->time_ns : 0;
    }

    public function hasTimeNs()
    {
        return isset($this->time_ns);
    }

    public function clearTimeNs()
    {
        unset($this->time_ns);
    }

    /**
     * Generated from protobuf field <code>optional fixed32 time_ns = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeNs($var)
    {
        GPBUtil::checkUint32($var);
        $this->time_ns = $var;

        return $this;
    }

}

