<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto

namespace Dew\Acs\Sls\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>acs.sls.LogGroup</code>
 */
class LogGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .acs.sls.Log logs = 1;</code>
     */
    private $logs;
    /**
     * Generated from protobuf field <code>optional string topic = 3;</code>
     */
    protected $topic = null;
    /**
     * Generated from protobuf field <code>optional string source = 4;</code>
     */
    protected $source = null;
    /**
     * Generated from protobuf field <code>optional string machine_uuid = 5;</code>
     */
    protected $machine_uuid = null;
    /**
     * Generated from protobuf field <code>repeated .acs.sls.LogTag tags = 6;</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Dew\Acs\Sls\Messages\Log>|\Google\Protobuf\Internal\RepeatedField $logs
     *     @type string $topic
     *     @type string $source
     *     @type string $machine_uuid
     *     @type array<\Dew\Acs\Sls\Messages\LogTag>|\Google\Protobuf\Internal\RepeatedField $tags
     * }
     */
    public function __construct($data = NULL) {
        \Dew\Acs\Sls\Metadata\Log::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .acs.sls.Log logs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLogs()
    {
        return $this->logs;
    }

    /**
     * Generated from protobuf field <code>repeated .acs.sls.Log logs = 1;</code>
     * @param array<\Dew\Acs\Sls\Messages\Log>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dew\Acs\Sls\Messages\Log::class);
        $this->logs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string topic = 3;</code>
     * @return string
     */
    public function getTopic()
    {
        return isset($this->topic) ? $this->topic : '';
    }

    public function hasTopic()
    {
        return isset($this->topic);
    }

    public function clearTopic()
    {
        unset($this->topic);
    }

    /**
     * Generated from protobuf field <code>optional string topic = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string source = 4;</code>
     * @return string
     */
    public function getSource()
    {
        return isset($this->source) ? $this->source : '';
    }

    public function hasSource()
    {
        return isset($this->source);
    }

    public function clearSource()
    {
        unset($this->source);
    }

    /**
     * Generated from protobuf field <code>optional string source = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string machine_uuid = 5;</code>
     * @return string
     */
    public function getMachineUuid()
    {
        return isset($this->machine_uuid) ? $this->machine_uuid : '';
    }

    public function hasMachineUuid()
    {
        return isset($this->machine_uuid);
    }

    public function clearMachineUuid()
    {
        unset($this->machine_uuid);
    }

    /**
     * Generated from protobuf field <code>optional string machine_uuid = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMachineUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->machine_uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .acs.sls.LogTag tags = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>repeated .acs.sls.LogTag tags = 6;</code>
     * @param array<\Dew\Acs\Sls\Messages\LogTag>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dew\Acs\Sls\Messages\LogTag::class);
        $this->tags = $arr;

        return $this;
    }

}

