<?php

declare(strict_types=1);

namespace Dew\Acs\EfloController;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result createCluster(array $arguments = [])
 * @method \Http\Promise\Promise createClusterAsync($arguments = [])
 * @method \Dew\Acs\Result deleteCluster(array $arguments = [])
 * @method \Http\Promise\Promise deleteClusterAsync($arguments = [])
 * @method \Dew\Acs\Result describeCluster(array $arguments = [])
 * @method \Http\Promise\Promise describeClusterAsync($arguments = [])
 * @method \Dew\Acs\Result extendCluster(array $arguments = [])
 * @method \Http\Promise\Promise extendClusterAsync($arguments = [])
 * @method \Dew\Acs\Result listClusters(array $arguments = [])
 * @method \Http\Promise\Promise listClustersAsync($arguments = [])
 * @method \Dew\Acs\Result listClusterNodes(array $arguments = [])
 * @method \Http\Promise\Promise listClusterNodesAsync($arguments = [])
 * @method \Dew\Acs\Result shrinkCluster(array $arguments = [])
 * @method \Http\Promise\Promise shrinkClusterAsync($arguments = [])
 * @method \Dew\Acs\Result describeNode(array $arguments = [])
 * @method \Http\Promise\Promise describeNodeAsync($arguments = [])
 * @method \Dew\Acs\Result listFreeNodes(array $arguments = [])
 * @method \Http\Promise\Promise listFreeNodesAsync($arguments = [])
 * @method \Dew\Acs\Result rebootNodes(array $arguments = [])
 * @method \Http\Promise\Promise rebootNodesAsync($arguments = [])
 * @method \Dew\Acs\Result reimageNodes(array $arguments = [])
 * @method \Http\Promise\Promise reimageNodesAsync($arguments = [])
 * @method \Dew\Acs\Result untagResources(array $arguments = [])
 * @method \Http\Promise\Promise untagResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result tagResources(array $arguments = [])
 * @method \Http\Promise\Promise tagResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result listTagResources(array $arguments = [])
 * @method \Http\Promise\Promise listTagResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result describeZones(array $arguments = [])
 * @method \Http\Promise\Promise describeZonesAsync($arguments = [])
 * @method \Dew\Acs\Result describeTask(array $arguments = [])
 * @method \Http\Promise\Promise describeTaskAsync($arguments = [])
 * @method \Dew\Acs\Result describeRegions(array $arguments = [])
 * @method \Http\Promise\Promise describeRegionsAsync($arguments = [])
 * @method \Dew\Acs\Result changeResourceGroup(array $arguments = [])
 * @method \Http\Promise\Promise changeResourceGroupAsync($arguments = [])
 * @method \Dew\Acs\Result approveOperation(array $arguments = [])
 * @method \Http\Promise\Promise approveOperationAsync($arguments = [])
 * @method \Dew\Acs\Result stopInvocation(array $arguments = [])
 * @method \Http\Promise\Promise stopInvocationAsync($arguments = [])
 * @method \Dew\Acs\Result runCommand(array $arguments = [])
 * @method \Http\Promise\Promise runCommandAsync($arguments = [])
 * @method \Dew\Acs\Result describeInvocations(array $arguments = [])
 * @method \Http\Promise\Promise describeInvocationsAsync($arguments = [])
 * @method \Dew\Acs\Result describeSendFileResults(array $arguments = [])
 * @method \Http\Promise\Promise describeSendFileResultsAsync($arguments = [])
 * @method \Dew\Acs\Result sendFile(array $arguments = [])
 * @method \Http\Promise\Promise sendFileAsync($arguments = [])
 * @method \Dew\Acs\Result listMachineTypes(array $arguments = [])
 * @method \Http\Promise\Promise listMachineTypesAsync($arguments = [])
 * @method \Dew\Acs\Result createDiagnosticTask(array $arguments = [])
 * @method \Http\Promise\Promise createDiagnosticTaskAsync($arguments = [])
 * @method \Dew\Acs\Result listNodeGroups(array $arguments = [])
 * @method \Http\Promise\Promise listNodeGroupsAsync($arguments = [])
 * @method \Dew\Acs\Result stopNodes(array $arguments = [])
 * @method \Http\Promise\Promise stopNodesAsync($arguments = [])
 * @method \Dew\Acs\Result listImages(array $arguments = [])
 * @method \Http\Promise\Promise listImagesAsync($arguments = [])
 * @method \Dew\Acs\Result closeSession(array $arguments = [])
 * @method \Http\Promise\Promise closeSessionAsync($arguments = [])
 * @method \Dew\Acs\Result createSession(array $arguments = [])
 * @method \Http\Promise\Promise createSessionAsync($arguments = [])
 * @method \Dew\Acs\Result createNetTestTask(array $arguments = [])
 * @method \Http\Promise\Promise createNetTestTaskAsync($arguments = [])
 * @method \Dew\Acs\Result listUserClusterTypes(array $arguments = [])
 * @method \Http\Promise\Promise listUserClusterTypesAsync($arguments = [])
 * @method \Dew\Acs\Result listNetTestResults(array $arguments = [])
 * @method \Http\Promise\Promise listNetTestResultsAsync($arguments = [])
 * @method \Dew\Acs\Result listDiagnosticResults(array $arguments = [])
 * @method \Http\Promise\Promise listDiagnosticResultsAsync($arguments = [])
 * @method \Dew\Acs\Result describeNetTestResult(array $arguments = [])
 * @method \Http\Promise\Promise describeNetTestResultAsync($arguments = [])
 * @method \Dew\Acs\Result listMachineNetworkInfo(array $arguments = [])
 * @method \Http\Promise\Promise listMachineNetworkInfoAsync($arguments = [])
 */
final class EfloControllerClient extends AcsClient
{
    //
}
