<?php

declare(strict_types=1);

namespace Dew\Acs\AliGenie;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result getBusAppConfig(array $arguments = []) {@since iap_1.0}
 * @method \Http\Promise\Promise getBusAppConfigAsync($arguments = []) {@since iap_1.0}
 * @method \Dew\Acs\Result appUseTimeReport(array $arguments = []) {@since iap_1.0}
 * @method \Http\Promise\Promise appUseTimeReportAsync($arguments = []) {@since iap_1.0}
 * @method \Dew\Acs\Result pullCashier(array $arguments = []) {@since iap_1.0}
 * @method \Http\Promise\Promise pullCashierAsync($arguments = []) {@since iap_1.0}
 * @method \Dew\Acs\Result videoAppReport(array $arguments = []) {@since iap_1.0}
 * @method \Http\Promise\Promise videoAppReportAsync($arguments = []) {@since iap_1.0}
 * @method \Dew\Acs\Result getAccountForApp(array $arguments = []) {@since iap_1.0}
 * @method \Http\Promise\Promise getAccountForAppAsync($arguments = []) {@since iap_1.0}
 * @method \Dew\Acs\Result getPhoneNumber(array $arguments = []) {@since iap_1.0}
 * @method \Http\Promise\Promise getPhoneNumberAsync($arguments = []) {@since iap_1.0}
 * @method \Dew\Acs\Result createReminder(array $arguments = []) {@since iap_1.0}
 * @method \Http\Promise\Promise createReminderAsync($arguments = []) {@since iap_1.0}
 * @method \Dew\Acs\Result getReminder(array $arguments = []) {@since iap_1.0}
 * @method \Http\Promise\Promise getReminderAsync($arguments = []) {@since iap_1.0}
 * @method \Dew\Acs\Result listReminders(array $arguments = []) {@since iap_1.0}
 * @method \Http\Promise\Promise listRemindersAsync($arguments = []) {@since iap_1.0}
 * @method \Dew\Acs\Result updateReminder(array $arguments = []) {@since iap_1.0}
 * @method \Http\Promise\Promise updateReminderAsync($arguments = []) {@since iap_1.0}
 * @method \Dew\Acs\Result deleteReminder(array $arguments = []) {@since iap_1.0}
 * @method \Http\Promise\Promise deleteReminderAsync($arguments = []) {@since iap_1.0}
 * @method \Dew\Acs\Result wakeUpApp(array $arguments = []) {@since iap_1.0}
 * @method \Http\Promise\Promise wakeUpAppAsync($arguments = []) {@since iap_1.0}
 * @method \Dew\Acs\Result pushNotifications(array $arguments = []) {@since iap_1.0}
 * @method \Http\Promise\Promise pushNotificationsAsync($arguments = []) {@since iap_1.0}
 * @method \Dew\Acs\Result sendNotifications(array $arguments = []) {@since iap_1.0}
 * @method \Http\Promise\Promise sendNotificationsAsync($arguments = []) {@since iap_1.0}
 * @method \Dew\Acs\Result checkThirdRightSendPlan(array $arguments = []) {@since iap_1.0}
 * @method \Http\Promise\Promise checkThirdRightSendPlanAsync($arguments = []) {@since iap_1.0}
 * @method \Dew\Acs\Result callBackThirdRightSendPlan(array $arguments = []) {@since iap_1.0}
 * @method \Http\Promise\Promise callBackThirdRightSendPlanAsync($arguments = []) {@since iap_1.0}
 * @method \Dew\Acs\Result authLoginWithThirdUserInfo(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise authLoginWithThirdUserInfoAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result ecologyOpennessSendVerificationCode(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise ecologyOpennessSendVerificationCodeAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result findUserlistToAuthLoginWithPhoneNumber(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise findUserlistToAuthLoginWithPhoneNumberAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result authLoginWithAligenieUserInfo(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise authLoginWithAligenieUserInfoAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result authLoginWithAligenieUserInfoGeneratedByPhoneNumber(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise authLoginWithAligenieUserInfoGeneratedByPhoneNumberAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result authLoginWithTaobaoUserInfo(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise authLoginWithTaobaoUserInfoAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result ecologyOpennessAuthenticate(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise ecologyOpennessAuthenticateAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getAligenieUserInfo(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getAligenieUserInfoAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result unbindAligenieUser(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise unbindAligenieUserAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result queryUserDeviceListByTmeUserId(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise queryUserDeviceListByTmeUserIdAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result invalidateThirdPartyAppLoginState(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise invalidateThirdPartyAppLoginStateAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result checkAuthCodeBindForExt(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise checkAuthCodeBindForExtAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getCodeEnhance(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getCodeEnhanceAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result scanCodeBind(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise scanCodeBindAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getUserByDeviceId(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getUserByDeviceIdAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listDeviceByUserId(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listDeviceByUserIdAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result unbindDevice(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise unbindDeviceAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listDeviceByUserIdAndChanel(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listDeviceByUserIdAndChanelAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getDeviceIdByIdentity(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getDeviceIdByIdentityAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listDeviceIdByIdentities(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listDeviceIdByIdentitiesAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getDeviceBasicInfo(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getDeviceBasicInfoAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listDeviceBasicInfo(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listDeviceBasicInfoAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getDeviceStatusInfo(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getDeviceStatusInfoAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getDeviceTag(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getDeviceTagAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result deviceControl(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise deviceControlAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getDeviceSetting(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getDeviceSettingAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getDeviceStatusDetail(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getDeviceStatusDetailAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result setDeviceSetting(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise setDeviceSettingAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getJiangSuTelecomData(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getJiangSuTelecomDataAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result scgSearch(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise scgSearchAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result addAndRemoveFavoriteContent(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise addAndRemoveFavoriteContentAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result createPlayingList(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise createPlayingListAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getAlbum(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getAlbumAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getContent(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getContentAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getCurrentPlayingItem(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getCurrentPlayingItemAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getCurrentPlayingList(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getCurrentPlayingListAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result indexControlPlayingList(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise indexControlPlayingListAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listAlbumDetail(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listAlbumDetailAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listCateContent(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listCateContentAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listCateInfo(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listCateInfoAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listCommonCateFirstFloor(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listCommonCateFirstFloorAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listCommonCateSecondFloor(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listCommonCateSecondFloorAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listPlayHistory(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listPlayHistoryAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listRecommendContent(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listRecommendContentAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result playAndPauseControl(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise playAndPauseControlAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result playModeControl(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise playModeControlAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result previousAndNextControl(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise previousAndNextControlAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result progressControl(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise progressControlAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result searchContent(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise searchContentAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result cloudPlayer(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise cloudPlayerAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result mobileRecommend(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise mobileRecommendAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result addSub(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise addSubAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result deleteSub(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise deleteSubAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listAlbumIsAdded(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listAlbumIsAddedAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listSub(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listSubAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listSubAlbum(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listSubAlbumAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listSubscriptionAlbumCategory(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listSubscriptionAlbumCategoryAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getAlbumDetailById(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getAlbumDetailByIdAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getUnreadMessageCount(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getUnreadMessageCountAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listUserMessage(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listUserMessageAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result readMessage(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise readMessageAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result sendMessage(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise sendMessageAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result createAlarm(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise createAlarmAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result deleteAlarms(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise deleteAlarmsAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getAlarm(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getAlarmAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listAlarms(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listAlarmsAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result listMusic(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise listMusicAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result queryMusicType(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise queryMusicTypeAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result updateAlarm(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise updateAlarmAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result createScheduleTask(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise createScheduleTaskAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result deleteScheduleTask(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise deleteScheduleTaskAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getScheduleTask(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getScheduleTaskAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getWeather(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise getWeatherAsync($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result createPlayingListOAuth2(array $arguments = []) {@since ssp_1.0}
 * @method \Http\Promise\Promise createPlayingListOAuth2Async($arguments = []) {@since ssp_1.0}
 * @method \Dew\Acs\Result getRelationProductList(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getRelationProductListAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result createHotel(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise createHotelAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result updateHotel(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise updateHotelAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result removeHotel(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise removeHotelAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listHotelInfo(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listHotelInfoAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listHotels(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listHotelsAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result auditHotel(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise auditHotelAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listHotelRooms(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listHotelRoomsAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result batchAddHotelRoom(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise batchAddHotelRoomAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result batchDeleteHotelRoom(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise batchDeleteHotelRoomAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result checkoutWithAK(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise checkoutWithAKAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result queryHotelRoomDetail(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise queryHotelRoomDetailAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listSceneCategory(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listSceneCategoryAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listDialogueTemplate(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listDialogueTemplateAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result insertHotelSceneBookItem(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise insertHotelSceneBookItemAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result deleteHotelSceneBookItem(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise deleteHotelSceneBookItemAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result updateHotelSceneBookItem(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise updateHotelSceneBookItemAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listHotelSceneBookItems(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listHotelSceneBookItemsAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listHotelSceneItems(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listHotelSceneItemsAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result updateHotelSceneItem(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise updateHotelSceneItemAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result getHotelSceneItemDetail(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getHotelSceneItemDetailAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result invokeRobotPush(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise invokeRobotPushAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result importHotelConfig(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise importHotelConfigAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result importRoomControlDevices(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise importRoomControlDevicesAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result importRoomGenieScenes(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise importRoomGenieScenesAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result pageGetHotelRoomDevices(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise pageGetHotelRoomDevicesAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result queryRoomControlDevices(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise queryRoomControlDevicesAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result getHotelRoomDevice(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getHotelRoomDeviceAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result controlRoomDevice(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise controlRoomDeviceAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result pushVoiceBoxCommands(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise pushVoiceBoxCommandsAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result syncDeviceStatusWithAk(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise syncDeviceStatusWithAkAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result createRcuScene(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise createRcuSceneAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result deleteRcuScene(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise deleteRcuSceneAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result updateRcuScene(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise updateRcuSceneAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result executeScene(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise executeSceneAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result querySceneList(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise querySceneListAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result queryRoomStatus(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise queryRoomStatusAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result queryRoomControlDevicesAndStatus(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise queryRoomControlDevicesAndStatusAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listAllProvinces(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listAllProvincesAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listCitiesByProvince(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listCitiesByProvinceAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listSTBServiceProviders(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listSTBServiceProvidersAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listInfraredDeviceBrands(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listInfraredDeviceBrandsAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listInfraredRemoteControllers(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listInfraredRemoteControllersAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listCustomQA(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listCustomQAAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result addCustomQA(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise addCustomQAAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result addCustomQAV2(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise addCustomQAV2Async($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result updateCustomQA(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise updateCustomQAAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result deleteCustomQA(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise deleteCustomQAAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result getBasicInfoQA(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getBasicInfoQAAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result updateBasicInfoQA(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise updateBasicInfoQAAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listServiceQA(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listServiceQAAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result updateServiceQA(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise updateServiceQAAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result addCartoon(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise addCartoonAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result getCartoon(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getCartoonAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result deleteCartoon(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise deleteCartoonAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result getHotelScreenSaverStyle(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getHotelScreenSaverStyleAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result addOrUpdateHotelSetting(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise addOrUpdateHotelSettingAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result getHotelSetting(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getHotelSettingAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result deleteHotelSetting(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise deleteHotelSettingAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result addOrUpdateWelcomeText(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise addOrUpdateWelcomeTextAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result getWelcomeTextAndMusic(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getWelcomeTextAndMusicAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result resetWelcomeTextAndMusic(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise resetWelcomeTextAndMusicAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result pushWelcomeTextAndMusic(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise pushWelcomeTextAndMusicAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result pushWelcome(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise pushWelcomeAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result addMessageTemplate(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise addMessageTemplateAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listHotelMessageTemplate(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listHotelMessageTemplateAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result deleteMessageTemplate(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise deleteMessageTemplateAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result updateMessageTemplate(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise updateMessageTemplateAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result pushHotelMessage(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise pushHotelMessageAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listTickets(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listTicketsAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result updateTicket(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise updateTicketAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result deleteHotelAlarm(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise deleteHotelAlarmAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listHotelAlarm(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listHotelAlarmAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result createHotelAlarm(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise createHotelAlarmAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result updateHotelAlarm(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise updateHotelAlarmAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result childAccountAuth(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise childAccountAuthAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result removeChildAccountAuth(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise removeChildAccountAuthAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result pmsEventReport(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise pmsEventReportAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result queryDeviceStatus(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise queryDeviceStatusAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listHotelControlDevice(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listHotelControlDeviceAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result deviceControl(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise deviceControlAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listHotelSceneItem(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listHotelSceneItemAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listHotelServiceCategory(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listHotelServiceCategoryAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result getHotelOrderDetail(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getHotelOrderDetailAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result listHotelOrder(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise listHotelOrderAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result submitHotelOrder(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise submitHotelOrderAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result getHotelNotice(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getHotelNoticeAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result getHotelNoticeV2(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getHotelNoticeV2Async($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result getHotelHomeBackImageAndModes(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getHotelHomeBackImageAndModesAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result getHotelSampleUtterances(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getHotelSampleUtterancesAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result getHotelScreenSaver(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getHotelScreenSaverAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result roomCheckOut(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise roomCheckOutAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result getHotelContacts(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getHotelContactsAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result getHotelContactByNumber(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getHotelContactByNumberAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result getHotelContactByGenieDevice(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getHotelContactByGenieDeviceAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result addOrUpdateScreenSaver(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise addOrUpdateScreenSaverAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result addOrUpdateDisPlayModes(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise addOrUpdateDisPlayModesAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result getUnionId(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise getUnionIdAsync($arguments = []) {@since ip_1.0}
 * @method \Dew\Acs\Result hotelQrBind(array $arguments = []) {@since ip_1.0}
 * @method \Http\Promise\Promise hotelQrBindAsync($arguments = []) {@since ip_1.0}
 */
final class AliGenieClient extends AcsClient
{
    //
}
