<?php

declare(strict_types=1);

namespace Dew\Acs\Facebody;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result addFaceEntity(array $arguments = [])
 * @method \Http\Promise\Promise addFaceEntityAsync($arguments = [])
 * @method \Dew\Acs\Result addFace(array $arguments = [])
 * @method \Http\Promise\Promise addFaceAsync($arguments = [])
 * @method \Dew\Acs\Result createFaceDb(array $arguments = [])
 * @method \Http\Promise\Promise createFaceDbAsync($arguments = [])
 * @method \Dew\Acs\Result deleteFace(array $arguments = [])
 * @method \Http\Promise\Promise deleteFaceAsync($arguments = [])
 * @method \Dew\Acs\Result deleteFaceDb(array $arguments = [])
 * @method \Http\Promise\Promise deleteFaceDbAsync($arguments = [])
 * @method \Dew\Acs\Result deleteFaceEntity(array $arguments = [])
 * @method \Http\Promise\Promise deleteFaceEntityAsync($arguments = [])
 * @method \Dew\Acs\Result updateFaceEntity(array $arguments = [])
 * @method \Http\Promise\Promise updateFaceEntityAsync($arguments = [])
 * @method \Dew\Acs\Result searchFace(array $arguments = [])
 * @method \Http\Promise\Promise searchFaceAsync($arguments = [])
 * @method \Dew\Acs\Result getFaceEntity(array $arguments = [])
 * @method \Http\Promise\Promise getFaceEntityAsync($arguments = [])
 * @method \Dew\Acs\Result listFaceEntities(array $arguments = [])
 * @method \Http\Promise\Promise listFaceEntitiesAsync($arguments = [])
 * @method \Dew\Acs\Result listFaceDbs(array $arguments = [])
 * @method \Http\Promise\Promise listFaceDbsAsync($arguments = [])
 * @method \Dew\Acs\Result addFaceImageTemplate(array $arguments = [])
 * @method \Http\Promise\Promise addFaceImageTemplateAsync($arguments = [])
 * @method \Dew\Acs\Result deleteFaceImageTemplate(array $arguments = [])
 * @method \Http\Promise\Promise deleteFaceImageTemplateAsync($arguments = [])
 * @method \Dew\Acs\Result queryFaceImageTemplate(array $arguments = [])
 * @method \Http\Promise\Promise queryFaceImageTemplateAsync($arguments = [])
 * @method \Dew\Acs\Result blurFace(array $arguments = [])
 * @method \Http\Promise\Promise blurFaceAsync($arguments = [])
 * @method \Dew\Acs\Result compareFace(array $arguments = [])
 * @method \Http\Promise\Promise compareFaceAsync($arguments = [])
 * @method \Dew\Acs\Result detectFace(array $arguments = [])
 * @method \Http\Promise\Promise detectFaceAsync($arguments = [])
 * @method \Dew\Acs\Result detectLivingFace(array $arguments = [])
 * @method \Http\Promise\Promise detectLivingFaceAsync($arguments = [])
 * @method \Dew\Acs\Result faceBeauty(array $arguments = [])
 * @method \Http\Promise\Promise faceBeautyAsync($arguments = [])
 * @method \Dew\Acs\Result faceFilter(array $arguments = [])
 * @method \Http\Promise\Promise faceFilterAsync($arguments = [])
 * @method \Dew\Acs\Result faceMakeup(array $arguments = [])
 * @method \Http\Promise\Promise faceMakeupAsync($arguments = [])
 * @method \Dew\Acs\Result faceTidyup(array $arguments = [])
 * @method \Http\Promise\Promise faceTidyupAsync($arguments = [])
 * @method \Dew\Acs\Result enhanceFace(array $arguments = [])
 * @method \Http\Promise\Promise enhanceFaceAsync($arguments = [])
 * @method \Dew\Acs\Result recognizeFace(array $arguments = [])
 * @method \Http\Promise\Promise recognizeFaceAsync($arguments = [])
 * @method \Dew\Acs\Result recognizePublicFace(array $arguments = [])
 * @method \Http\Promise\Promise recognizePublicFaceAsync($arguments = [])
 * @method \Dew\Acs\Result mergeImageFace(array $arguments = [])
 * @method \Http\Promise\Promise mergeImageFaceAsync($arguments = [])
 * @method \Dew\Acs\Result bodyPosture(array $arguments = [])
 * @method \Http\Promise\Promise bodyPostureAsync($arguments = [])
 * @method \Dew\Acs\Result detectBodyCount(array $arguments = [])
 * @method \Http\Promise\Promise detectBodyCountAsync($arguments = [])
 * @method \Dew\Acs\Result detectPedestrian(array $arguments = [])
 * @method \Http\Promise\Promise detectPedestrianAsync($arguments = [])
 * @method \Dew\Acs\Result detectPedestrianIntrusion(array $arguments = [])
 * @method \Http\Promise\Promise detectPedestrianIntrusionAsync($arguments = [])
 * @method \Dew\Acs\Result pedestrianDetectAttribute(array $arguments = [])
 * @method \Http\Promise\Promise pedestrianDetectAttributeAsync($arguments = [])
 * @method \Dew\Acs\Result recognizeHandGesture(array $arguments = [])
 * @method \Http\Promise\Promise recognizeHandGestureAsync($arguments = [])
 * @method \Dew\Acs\Result getRealPersonVerificationResult(array $arguments = [])
 * @method \Http\Promise\Promise getRealPersonVerificationResultAsync($arguments = [])
 * @method \Dew\Acs\Result genRealPersonVerificationToken(array $arguments = [])
 * @method \Http\Promise\Promise genRealPersonVerificationTokenAsync($arguments = [])
 * @method \Dew\Acs\Result detectCelebrity(array $arguments = [])
 * @method \Http\Promise\Promise detectCelebrityAsync($arguments = [])
 * @method \Dew\Acs\Result detectVideoLivingFace(array $arguments = [])
 * @method \Http\Promise\Promise detectVideoLivingFaceAsync($arguments = [])
 * @method \Dew\Acs\Result generateHumanAnimeStyle(array $arguments = [])
 * @method \Http\Promise\Promise generateHumanAnimeStyleAsync($arguments = [])
 * @method \Dew\Acs\Result generateHumanSketchStyle(array $arguments = [])
 * @method \Http\Promise\Promise generateHumanSketchStyleAsync($arguments = [])
 * @method \Dew\Acs\Result recognizeAction(array $arguments = [])
 * @method \Http\Promise\Promise recognizeActionAsync($arguments = [])
 * @method \Dew\Acs\Result handPosture(array $arguments = [])
 * @method \Http\Promise\Promise handPostureAsync($arguments = [])
 * @method \Dew\Acs\Result recognizeExpression(array $arguments = [])
 * @method \Http\Promise\Promise recognizeExpressionAsync($arguments = [])
 * @method \Dew\Acs\Result batchAddFaces(array $arguments = [])
 * @method \Http\Promise\Promise batchAddFacesAsync($arguments = [])
 * @method \Dew\Acs\Result extractFingerPrint(array $arguments = [])
 * @method \Http\Promise\Promise extractFingerPrintAsync($arguments = [])
 * @method \Dew\Acs\Result liquifyFace(array $arguments = [])
 * @method \Http\Promise\Promise liquifyFaceAsync($arguments = [])
 * @method \Dew\Acs\Result monitorExamination(array $arguments = [])
 * @method \Http\Promise\Promise monitorExaminationAsync($arguments = [])
 * @method \Dew\Acs\Result retouchBody(array $arguments = [])
 * @method \Http\Promise\Promise retouchBodyAsync($arguments = [])
 * @method \Dew\Acs\Result retouchSkin(array $arguments = [])
 * @method \Http\Promise\Promise retouchSkinAsync($arguments = [])
 * @method \Dew\Acs\Result compareFaceWithMask(array $arguments = [])
 * @method \Http\Promise\Promise compareFaceWithMaskAsync($arguments = [])
 * @method \Dew\Acs\Result detectInfraredLivingFace(array $arguments = [])
 * @method \Http\Promise\Promise detectInfraredLivingFaceAsync($arguments = [])
 * @method \Dew\Acs\Result deepfakeFace(array $arguments = [])
 * @method \Http\Promise\Promise deepfakeFaceAsync($arguments = [])
 */
final class FacebodyClient extends AcsClient
{
    //
}
