<?php

declare(strict_types=1);

namespace Dew\Acs\SysOM;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result authDiagnosis(array $arguments = [])
 * @method \Http\Promise\Promise authDiagnosisAsync($arguments = [])
 * @method \Dew\Acs\Result invokeDiagnosis(array $arguments = [])
 * @method \Http\Promise\Promise invokeDiagnosisAsync($arguments = [])
 * @method \Dew\Acs\Result getDiagnosisResult(array $arguments = [])
 * @method \Http\Promise\Promise getDiagnosisResultAsync($arguments = [])
 * @method \Dew\Acs\Result generateCopilotResponse(array $arguments = [])
 * @method \Http\Promise\Promise generateCopilotResponseAsync($arguments = [])
 * @method \Dew\Acs\Result getAbnormalEventsCount(array $arguments = [])
 * @method \Http\Promise\Promise getAbnormalEventsCountAsync($arguments = [])
 * @method \Dew\Acs\Result getHealthPercentage(array $arguments = [])
 * @method \Http\Promise\Promise getHealthPercentageAsync($arguments = [])
 * @method \Dew\Acs\Result listDiagnosis(array $arguments = [])
 * @method \Http\Promise\Promise listDiagnosisAsync($arguments = [])
 * @method \Dew\Acs\Result getCopilotHistory(array $arguments = [])
 * @method \Http\Promise\Promise getCopilotHistoryAsync($arguments = [])
 * @method \Dew\Acs\Result initialSysom(array $arguments = [])
 * @method \Http\Promise\Promise initialSysomAsync($arguments = [])
 * @method \Dew\Acs\Result listRegions(array $arguments = [])
 * @method \Http\Promise\Promise listRegionsAsync($arguments = [])
 * @method \Dew\Acs\Result installAgent(array $arguments = [])
 * @method \Http\Promise\Promise installAgentAsync($arguments = [])
 * @method \Dew\Acs\Result uninstallAgent(array $arguments = [])
 * @method \Http\Promise\Promise uninstallAgentAsync($arguments = [])
 * @method \Dew\Acs\Result upgradeAgent(array $arguments = [])
 * @method \Http\Promise\Promise upgradeAgentAsync($arguments = [])
 * @method \Dew\Acs\Result getAgentTask(array $arguments = [])
 * @method \Http\Promise\Promise getAgentTaskAsync($arguments = [])
 * @method \Dew\Acs\Result listAgentInstallRecords(array $arguments = [])
 * @method \Http\Promise\Promise listAgentInstallRecordsAsync($arguments = [])
 * @method \Dew\Acs\Result listAgents(array $arguments = [])
 * @method \Http\Promise\Promise listAgentsAsync($arguments = [])
 * @method \Dew\Acs\Result getHotspotCompare(array $arguments = [])
 * @method \Http\Promise\Promise getHotspotCompareAsync($arguments = [])
 * @method \Dew\Acs\Result getHostCount(array $arguments = [])
 * @method \Http\Promise\Promise getHostCountAsync($arguments = [])
 * @method \Dew\Acs\Result listAbnormalyEvents(array $arguments = [])
 * @method \Http\Promise\Promise listAbnormalyEventsAsync($arguments = [])
 * @method \Dew\Acs\Result listInstances(array $arguments = [])
 * @method \Http\Promise\Promise listInstancesAsync($arguments = [])
 * @method \Dew\Acs\Result getHotspotAnalysis(array $arguments = [])
 * @method \Http\Promise\Promise getHotspotAnalysisAsync($arguments = [])
 * @method \Dew\Acs\Result getHotspotPidList(array $arguments = [])
 * @method \Http\Promise\Promise getHotspotPidListAsync($arguments = [])
 * @method \Dew\Acs\Result listInstanceStatus(array $arguments = [])
 * @method \Http\Promise\Promise listInstanceStatusAsync($arguments = [])
 * @method \Dew\Acs\Result listInstanceHealth(array $arguments = [])
 * @method \Http\Promise\Promise listInstanceHealthAsync($arguments = [])
 * @method \Dew\Acs\Result getHotspotInstanceList(array $arguments = [])
 * @method \Http\Promise\Promise getHotspotInstanceListAsync($arguments = [])
 * @method \Dew\Acs\Result getProblemPercentage(array $arguments = [])
 * @method \Http\Promise\Promise getProblemPercentageAsync($arguments = [])
 * @method \Dew\Acs\Result getResources(array $arguments = [])
 * @method \Http\Promise\Promise getResourcesAsync($arguments = [])
 * @method \Dew\Acs\Result getHotspotTracking(array $arguments = [])
 * @method \Http\Promise\Promise getHotspotTrackingAsync($arguments = [])
 * @method \Dew\Acs\Result getInstantScore(array $arguments = [])
 * @method \Http\Promise\Promise getInstantScoreAsync($arguments = [])
 * @method \Dew\Acs\Result getRangeScore(array $arguments = [])
 * @method \Http\Promise\Promise getRangeScoreAsync($arguments = [])
 * @method \Dew\Acs\Result getAgent(array $arguments = [])
 * @method \Http\Promise\Promise getAgentAsync($arguments = [])
 * @method \Dew\Acs\Result invokeAnomalyDiagnosis(array $arguments = [])
 * @method \Http\Promise\Promise invokeAnomalyDiagnosisAsync($arguments = [])
 * @method \Dew\Acs\Result getListRecord(array $arguments = [])
 * @method \Http\Promise\Promise getListRecordAsync($arguments = [])
 * @method \Dew\Acs\Result getAIQueryResult(array $arguments = [])
 * @method \Http\Promise\Promise getAIQueryResultAsync($arguments = [])
 * @method \Dew\Acs\Result startAIAnalysis(array $arguments = [])
 * @method \Http\Promise\Promise startAIAnalysisAsync($arguments = [])
 */
final class SysOMClient extends AcsClient
{
    //
}
