<?php

declare(strict_types=1);

namespace Dew\Acs\WafOpenapi;

use Dew\Acs\AcsClient;

/**
 * @method \Dew\Acs\Result describeInstanceInfo(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeInstanceInfoAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result describeInstanceSpecInfo(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeInstanceSpecInfoAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result deleteInstance(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise deleteInstanceAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result describeDomainNames(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeDomainNamesAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result describeDomain(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeDomainAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result createDomain(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise createDomainAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result modifyDomain(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise modifyDomainAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result deleteDomain(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise deleteDomainAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result describeCertificates(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeCertificatesAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result describeCertMatchStatus(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeCertMatchStatusAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result createCertificate(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise createCertificateAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result createCertificateByCertificateId(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise createCertificateByCertificateIdAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result describeDomainBasicConfigs(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeDomainBasicConfigsAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result describeDomainAdvanceConfigs(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeDomainAdvanceConfigsAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result describeDomainList(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeDomainListAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result describeProtectionModuleMode(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeProtectionModuleModeAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result modifyDomainIpv6Status(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise modifyDomainIpv6StatusAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result describeProtectionModuleStatus(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeProtectionModuleStatusAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result modifyProtectionModuleStatus(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise modifyProtectionModuleStatusAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result modifyProtectionModuleMode(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise modifyProtectionModuleModeAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result describeProtectionModuleRules(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeProtectionModuleRulesAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result createProtectionModuleRule(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise createProtectionModuleRuleAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result modifyProtectionModuleRule(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise modifyProtectionModuleRuleAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result modifyProtectionRuleStatus(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise modifyProtectionRuleStatusAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result describeDomainRuleGroup(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeDomainRuleGroupAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result setDomainRuleGroup(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise setDomainRuleGroupAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result modifyProtectionRuleCacheStatus(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise modifyProtectionRuleCacheStatusAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result deleteProtectionModuleRule(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise deleteProtectionModuleRuleAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result describeProtectionModuleCodeConfig(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeProtectionModuleCodeConfigAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result describeRuleGroups(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeRuleGroupsAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result describeRules(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeRulesAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result modifyLogRetrievalStatus(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise modifyLogRetrievalStatusAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result modifyLogServiceStatus(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise modifyLogServiceStatusAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result describeLogServiceStatus(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeLogServiceStatusAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result describeWafSourceIpSegment(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise describeWafSourceIpSegmentAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result moveResourceGroup(array $arguments = []) {@since 2019-09-10}
 * @method \Http\Promise\Promise moveResourceGroupAsync($arguments = []) {@since 2019-09-10}
 * @method \Dew\Acs\Result createPostpaidInstance(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise createPostpaidInstanceAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeInstance(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeInstanceAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result releaseInstance(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise releaseInstanceAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeAbnormalCloudResources(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeAbnormalCloudResourcesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result reCreateCloudResource(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise reCreateCloudResourceAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result syncProductInstance(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise syncProductInstanceAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeCloudResources(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeCloudResourcesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeProductInstances(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeProductInstancesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeResourceSupportRegions(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeResourceSupportRegionsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeResourceRegionId(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeResourceRegionIdAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeResourceInstanceCerts(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeResourceInstanceCertsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result createCloudResource(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise createCloudResourceAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyCloudResource(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyCloudResourceAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result deleteCloudResource(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise deleteCloudResourceAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeCloudResourceAccessedPorts(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeCloudResourceAccessedPortsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeCloudResourceAccessPortDetails(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeCloudResourceAccessPortDetailsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDomainUsedPorts(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDomainUsedPortsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDomains(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDomainsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDomainDetail(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDomainDetailAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describePunishedDomains(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describePunishedDomainsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyDomainPunishStatus(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyDomainPunishStatusAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeCertDetail(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeCertDetailAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeCerts(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeCertsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDomainDNSRecord(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDomainDNSRecordAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeResourcePort(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeResourcePortAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDDoSStatus(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDDoSStatusAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result createSM2Cert(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise createSM2CertAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeCnameCount(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeCnameCountAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDefaultHttps(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDefaultHttpsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyDefaultHttps(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyDefaultHttpsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result createCerts(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise createCertsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeHybridCloudResources(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeHybridCloudResourcesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result createDefenseResource(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise createDefenseResourceAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result deleteDefenseResource(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise deleteDefenseResourceAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result createDefenseResourceGroup(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise createDefenseResourceGroupAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyDefenseResourceGroup(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyDefenseResourceGroupAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result deleteDefenseResourceGroup(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise deleteDefenseResourceGroupAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDefenseResourceGroup(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDefenseResourceGroupAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDefenseResourceGroups(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDefenseResourceGroupsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDefenseResourceGroupNames(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDefenseResourceGroupNamesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDefenseResource(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDefenseResourceAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDefenseResources(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDefenseResourcesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDefenseResourceNames(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDefenseResourceNamesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDefenseResourceOwnerUid(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDefenseResourceOwnerUidAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyDefenseResourceXff(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyDefenseResourceXffAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describePauseProtectionStatus(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describePauseProtectionStatusAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result createDefenseTemplate(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise createDefenseTemplateAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyDefenseTemplate(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyDefenseTemplateAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyDefenseTemplateStatus(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyDefenseTemplateStatusAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result copyDefenseTemplate(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise copyDefenseTemplateAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result deleteDefenseTemplate(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise deleteDefenseTemplateAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDefenseTemplate(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDefenseTemplateAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDefenseTemplates(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDefenseTemplatesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyTemplateResources(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyTemplateResourcesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeTemplateResources(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeTemplateResourcesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeTemplateResourceCount(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeTemplateResourceCountAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDefenseTemplateValidGroups(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDefenseTemplateValidGroupsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDefenseResourceTemplates(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDefenseResourceTemplatesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result createDefenseRule(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise createDefenseRuleAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyDefenseRule(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyDefenseRuleAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyDefenseRuleStatus(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyDefenseRuleStatusAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result deleteDefenseRule(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise deleteDefenseRuleAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDefenseRules(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDefenseRulesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDefenseRule(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDefenseRuleAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyDefenseRuleCache(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyDefenseRuleCacheAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result deleteDefenseRuleBlockIp(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise deleteDefenseRuleBlockIpAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeIpAbroadCountryInfos(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeIpAbroadCountryInfosAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyDefenseSceneConfig(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyDefenseSceneConfigAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeDefenseSceneConfig(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeDefenseSceneConfigAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result createMajorProtectionBlackIp(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise createMajorProtectionBlackIpAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyMajorProtectionBlackIp(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyMajorProtectionBlackIpAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result deleteMajorProtectionBlackIp(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise deleteMajorProtectionBlackIpAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result clearMajorProtectionBlackIp(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise clearMajorProtectionBlackIpAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeMajorProtectionBlackIps(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeMajorProtectionBlackIpsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result deleteApisecAbnormals(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise deleteApisecAbnormalsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyApisecAbnormals(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyApisecAbnormalsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApisecAssetTrend(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApisecAssetTrendAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApisecAbnormalDomainStatistic(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApisecAbnormalDomainStatisticAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApisecEventDomainStatistic(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApisecEventDomainStatisticAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApisecSensitiveDomainStatistic(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApisecSensitiveDomainStatisticAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyApisecEvents(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyApisecEventsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result deleteApisecEvents(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise deleteApisecEventsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyApisecLogDeliveryStatus(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyApisecLogDeliveryStatusAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result createApiExport(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise createApiExportAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApiExports(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApiExportsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApisecAbnormals(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApisecAbnormalsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApisecApiResources(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApisecApiResourcesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyApisecStatus(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyApisecStatusAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyApisecModuleStatus(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyApisecModuleStatusAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyApisecApiResource(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyApisecApiResourceAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeUserEventType(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeUserEventTypeAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeUserEventTrend(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeUserEventTrendAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeUserAsset(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeUserAssetAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeUserApiRequest(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeUserApiRequestAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeUserAbnormalType(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeUserAbnormalTypeAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeUserAbnormalTrend(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeUserAbnormalTrendAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeSensitiveStatistic(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeSensitiveStatisticAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeSensitiveRequests(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeSensitiveRequestsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeSensitiveRequestLog(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeSensitiveRequestLogAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeSensitiveOutboundTrend(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeSensitiveOutboundTrendAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeSensitiveOutboundStatistic(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeSensitiveOutboundStatisticAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeSensitiveOutboundDistribution(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeSensitiveOutboundDistributionAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeSensitiveDetectionResult(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeSensitiveDetectionResultAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeSensitiveApiStatistic(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeSensitiveApiStatisticAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeFreeUserEvents(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeFreeUserEventsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeFreeUserEventTypes(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeFreeUserEventTypesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeFreeUserEventCount(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeFreeUserEventCountAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeFreeUserAssetCount(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeFreeUserAssetCountAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApisecUserOperations(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApisecUserOperationsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApisecSuggestions(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApisecSuggestionsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApisecStatistics(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApisecStatisticsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApisecRules(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApisecRulesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApisecProtectionResources(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApisecProtectionResourcesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApisecProtectionGroups(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApisecProtectionGroupsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApisecMatchedHosts(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApisecMatchedHostsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApisecEvents(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApisecEventsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeNetworkFlowTimeSeriesMetric(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeNetworkFlowTimeSeriesMetricAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeSecurityEventTopNMetric(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeSecurityEventTopNMetricAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeSecurityEventTimeSeriesMetric(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeSecurityEventTimeSeriesMetricAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeSecurityEventLogs(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeSecurityEventLogsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeNetworkFlowTopNMetric(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeNetworkFlowTopNMetricAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeFlowChart(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeFlowChartAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describePeakTrend(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describePeakTrendAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeResponseCodeTrendGraph(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeResponseCodeTrendGraphAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeVisitUas(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeVisitUasAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeVisitTopIp(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeVisitTopIpAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeRuleHitsTopResource(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeRuleHitsTopResourceAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeRuleHitsTopRuleId(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeRuleHitsTopRuleIdAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeRuleHitsTopTuleType(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeRuleHitsTopTuleTypeAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeRuleHitsTopUrl(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeRuleHitsTopUrlAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeRuleHitsTopClientIp(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeRuleHitsTopClientIpAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeFlowTopResource(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeFlowTopResourceAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeRuleHitsTopUa(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeRuleHitsTopUaAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeFlowTopUrl(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeFlowTopUrlAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeUserSlsLogRegions(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeUserSlsLogRegionsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeUserWafLogStatus(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeUserWafLogStatusAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeSlsAuthStatus(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeSlsAuthStatusAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeSlsLogStoreStatus(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeSlsLogStoreStatusAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeSlsLogStore(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeSlsLogStoreAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyResourceLogStatus(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyResourceLogStatusAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeResourceLogStatus(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeResourceLogStatusAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeHybridCloudServerRegions(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeHybridCloudServerRegionsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeHybridCloudUnassignedMachines(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeHybridCloudUnassignedMachinesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyHybridCloudClusterBypassStatus(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyHybridCloudClusterBypassStatusAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeHybridCloudUser(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeHybridCloudUserAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeHybridCloudGroups(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeHybridCloudGroupsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result createHybridCloudGroup(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise createHybridCloudGroupAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeHybridCloudClusterRule(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeHybridCloudClusterRuleAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeHybridCloudClusters(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeHybridCloudClustersAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyHybridCloudClusterRule(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyHybridCloudClusterRuleAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyHybridCloudGroup(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyHybridCloudGroupAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyHybridCloudGroupExpansionServer(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyHybridCloudGroupExpansionServerAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyHybridCloudGroupShrinkServer(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyHybridCloudGroupShrinkServerAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyHybridCloudSdkPullinStatus(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyHybridCloudSdkPullinStatusAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyHybridCloudServer(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyHybridCloudServerAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result deleteHybridCloudClusterRule(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise deleteHybridCloudClusterRuleAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result createHybridCloudClusterRule(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise createHybridCloudClusterRuleAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeHybridCloudClusterRules(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeHybridCloudClusterRulesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result createMemberAccounts(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise createMemberAccountsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyMemberAccount(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyMemberAccountAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result deleteMemberAccount(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise deleteMemberAccountAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeAccountDelegatedStatus(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeAccountDelegatedStatusAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeMemberAccounts(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeMemberAccountsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result changeResourceGroup(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise changeResourceGroupAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result listTagKeys(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise listTagKeysAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result untagResources(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise untagResourcesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result listTagResources(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise listTagResourcesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result listTagValues(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise listTagValuesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result tagResources(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise tagResourcesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApisecLogDeliveries(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApisecLogDeliveriesAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApisecSlsLogStores(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApisecSlsLogStoresAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result describeApisecSlsProjects(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise describeApisecSlsProjectsAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyApisecLogDelivery(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyApisecLogDeliveryAsync($arguments = []) {@since 2021-10-01}
 * @method \Dew\Acs\Result modifyPauseProtectionStatus(array $arguments = []) {@since 2021-10-01}
 * @method \Http\Promise\Promise modifyPauseProtectionStatusAsync($arguments = []) {@since 2021-10-01}
 */
final class WafOpenapiClient extends AcsClient
{
    //
}
