name: Update OpenAPI metadata

on:
  schedule:
    - cron: "30 3 * * 6"   # At 03:30 on Saturday
  workflow_dispatch:
  pull_request:
    types:
      - labeled

jobs:
  metadata:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'update-metadata')

    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer update --prefer-stable --no-interaction --no-progress --ansi

      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch metadata
        run: make fetch-meta

      - name: Commit metadata changes
        run: |
          git add .
          git commit -m "update metadata"

      - name: Build clients
        run: make build-clients

      - name: Commit updated clients
        run: |
          git add .
          git commit -m "build clients"

      - name: Create a Pull Request
        run: |
          gh pr create \
            --base main \
            --title "Update OpenAPI metadata $(date '+%Y%m%d')" \
            --body "Here are the API changes during the week, check the metadata and update with the latest Alibaba Cloud APIs."
